### ISSUE TITLE
Manual IP Configuration For Second Nic Fails

### ISSUE THREAD

**Issue by djeraseit** [rockstor/rockstor-core#1039]
First Box: Manual
Second Box: 10.99.0.11
Netmask: 255.255.0.0

Error!

execv() arg 2 must contain only strings

**Comment by djeraseit** [comment]
Manually assigning IP address in Centos and rebooting gives the following error:

Unknown client error doing a GET to /api/dashboardconfig/ 

Will update issue as I continue troubleshooting

**Comment by djeraseit** [comment]
rockstor.log file:

[02/Dec/2015 09:32:51] ERROR [storageadmin.util:38] request path: /api/network/eth1 method: PUT data: {u'dns_servers': u'', u'itype': u'', u'name': u'eth1', u'ipaddr': u'10.99.0.11', u'method': u'manual', u'netmask': u'255.255.0.0', u'gateway': u''}
[02/Dec/2015 09:32:52] ERROR [storageadmin.util:39] exception: execv() arg 2 must contain only strings
Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/rest_framework_custom/generic_view.py", line 40, in _handle_exception
    yield
  File "/opt/rockstor/src/rockstor/storageadmin/views/network.py", line 192, in put
    gateway=gateway, dns_servers=dns_servers)
  File "/opt/rockstor/src/rockstor/system/osi.py", line 221, in config_network_device
    run_command(add_cmd)
  File "/opt/rockstor/src/rockstor/system/osi.py", line 73, in run_command
    p = subprocess.Popen(cmd, shell=shell, stdout=stdout, stderr=stderr)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1308, in _execute_child
    raise child_exception
TypeError: execv() arg 2 must contain only strings

**Comment by schakrava** [comment]
Thanks for reporting this issue. What version of Rockstor are you on?

**Comment by schakrava** [comment]
Fixed by #1049

**Comment by schakrava** [comment]
Thanks for filing this issue @djeraseit , it's fixed in 3.8-9.09 update
