### ISSUE TITLE
Changing hostname causes problems with Dashboard loading

### ISSUE THREAD

**Issue by djeraseit** [rockstor/rockstor-core#1042]
Note: "107" was hostname given automatically by VPS provider.

Changing hostname causes dashboard and mounting issue.
Changing hostname to rockstor fixes problem.

rockstor.log

[02/Dec/2015 14:07:21] ERROR [smart_manager.data_collector:354] Failed to update disk state.. exception: duplicate key value violates unique constraint "storageadmin_pool_name_key"
DETAIL:  Key (name)=(rockstor_rockstor) already exists.

[02/Dec/2015 14:07:21] ERROR [storageadmin.middleware:35] Exception occured while processing a request. Path: /api/commands/refresh-pool-state method: POST
[02/Dec/2015 14:07:21] ERROR [storageadmin.middleware:36] Error running a command. cmd = ['/sbin/btrfs', 'fi', 'df', '/mnt2/rockstor_107']. rc = 1. stdout = ['']. stderr = ["ERROR: can't access '/mnt2/rockstor_107'", '']
Traceback (most recent call last):
  File "/opt/rockstor/eggs/Django-1.6.11-py2.7.egg/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/rockstor/eggs/Django-1.6.11-py2.7.egg/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.6.11-py2.7.egg/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/views.py", line 452, in dispatch
    response = self.handle_exception(exc)
  File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/views.py", line 449, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.6.11-py2.7.egg/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/opt/rockstor/src/rockstor/storageadmin/views/command.py", line 234, in post
    p.raid = pool_raid('%s%s' % (settings.MNT_PT, p.name))['data']
  File "/opt/rockstor/src/rockstor/fs/btrfs.py", line 82, in pool_raid
    o, e, rc = run_command([BTRFS, 'fi', 'df', mnt_pt])
  File "/opt/rockstor/src/rockstor/system/osi.py", line 89, in run_command
    raise CommandException(cmd, out, err, rc)
CommandException: Error running a command. cmd = ['/sbin/btrfs', 'fi', 'df', '/mnt2/rockstor_107']. rc = 1. stdout = ['']. stderr = ["ERROR: can't access '/mnt2/rockstor_107'", '']

**Comment by schakrava** [comment]
@djeraseit Thanks for filing this issue with necessary detail. I can see how it seems like the issue is related to hostname, but it's not. I think the issue is the same(or mostly the same) as #921.

I'll close the issue for now, but If you are able to reproduce it in versions 3.8.11-05 or greater, please do reopen it.
