### ISSUE TITLE
exporting arbitrary directories via NFS

### ISSUE THREAD

**Issue by schakrava** [rockstor/rockstor-core#1078]
Currently, we don't support exporting arbitrary directories via NFS. Users have to manually edit /etc/exports and if they do, it gets overwritten at a later point. The current workaround is to create a special /etc/exports.d/foo.exports file. Perhaps Rockstor should have it's own exports file instead of /etc/exports.

**Comment by tobiashochguertel** [comment]
Does this relates to the "Enter manual export entries below." in NFS Advance dialog?

I tried to export an directory which is stored on an share.

```
Houston, we've had a problem.
Share with name: atomic.hochguertel.local does not exist
```

```
            Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/storageadmin/views/share_helpers.py", line 42, in validate_share
    return Share.objects.get(name=sname)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: Share matching query does not exist.
```

![2017-03-10 23_28_55-greenshot](https://cloud.githubusercontent.com/assets/3332669/23815656/56fa7656-05e9-11e7-8d38-87745751533b.png)

**Comment by FroggyFlox** [comment]
This issue was brought to light again by forum user **Walt**: [https://forum.rockstor.com/t/nfs-advanced-edit-incorrectly-checks-existence-of-shares/8658](https://forum.rockstor.com/t/nfs-advanced-edit-incorrectly-checks-existence-of-shares/8658?u=flox).

In the "Advanced edit" dialog, we indeed only support the export of a share's top level. This is because we verify the share's existence based on the last level of the path entered in the Advanced edit window:
https://github.com/rockstor/rockstor-core/blob/5ea4b206d068cf095277b0fee6238d71d16dadb3/src/rockstor/storageadmin/views/nfs_exports.py#L68-L69
