### ISSUE TITLE
Fatal error: Too many clients error when connecting with https after a while

### ISSUE THREAD

**Issue by henfri** [rockstor/rockstor-core#1120]
Hello,

Quote:I connect to the http interface on my local network, and everything works, (https://10.1.2,3 or whatever). The problem is I connect a few times a day from different systems. After a while I noticed that I started getting error messages and the ui wouldn't load.

I don't think I'm opening even 30 different connections. This seems like a strange fragility that I can't open say 5 or 10 different connections.

In the error file, I see different: FATAL: sorry, too many clients already. I see this with any of the pages at my local network after the problem. Restarting the vm fixes it. Here's the top of one of the stack frames:

[11/Jan/2016 09:10:40] ERROR [storageadmin.middleware:35] Exception occured while processing a request. Path: / method: GET
[11/Jan/2016 09:10:40] ERROR [storageadmin.middleware:36] FATAL: sorry, too many clients already
Traceback (most recent call last):
File "/opt/rockstor/eggs/Django-1.6.11-py2.7.egg/django/core/handlers/base.py", line 112, in get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/opt/rockstor/src/rockstor/storageadmin/views/home.py", line 59, in home
setup = Setup.objects.all()[0]
File "/opt/rockstor/eggs/Django-1.6.11-py2.7.egg/django/db/models/query.py", line 132, in getitem

please refer to this forum post:
http://forum.rockstor.com/t/fatal-error-too-many-clients-error-when-connecting-with-https-after-a-while/906

Greetings,
Hendrik

**Comment by MFlyer** [comment]
@schakrava this seems to closed

**Comment by norm1710** [comment]
No it's not.  Happening to me last week.  The systemctl restart rockstor fixed it but this was the second in only 10 days from install.

I'm collecting background info on what might be causing it.  At the moment the culprit appears to be multiple zero proc time postgres processes.  The clean up routine closes down processes that have proc time against them but not the zero time ones.  Just a thought at the moment.

Rgds Ian

**Comment by MFlyer** [comment]
Hi @norm1710 , any news about this one??

M.

**Comment by schakrava** [comment]
postgres processes have decreased in count over last couple of updates because we decreased the usage of django ORM outside of backend, eg: data-collector and other services. But they may still be room for optimization. I myself have not seen this error in several months. 

@Ian-T-Price are you still seeing this?

**Comment by phillxnet** [comment]
I haven't seen this myself for a good while and there hasn't been mention of it on the forum either.
I propose it it be closed.

**Comment by Ian-T-Price** [comment]
Found another way of doing this so closed due to lack of interest...
