### ISSUE TITLE
Install fails for RockStor 3.8.12

### ISSUE THREAD

**Issue by chlige** [rockstor/rockstor-core#1257]
Receive the following error when trying to install RockStor v3.8.12

Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/pyanaconda/threads.py", line 211, in run
    threading.Thread.run(self, *args, **kwargs)
  File "/usr/lib64/python2.7/threading.py", line 764, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib64/python2.7/site-packages/pyanaconda/install.py", line 223, in doInstall
    payload.preInstall(packages=packages, groups=payload.languageGroups())
  File "/usr/lib64/python2.7/site-packages/pyanaconda/packaging/yumpayload.py", line 1609, in preInstall
    self.checkSoftwareSelection()
  File "/usr/lib64/python2.7/site-packages/pyanaconda/packaging/yumpayload.py", line 1523, in checkSoftwareSelection
    self._applyYumSelections()
  File "/usr/lib64/python2.7/site-packages/pyanaconda/packaging/yumpayload.py", line 1467, in _applyYumSelections
    self.selectRequiredPackages()
  File "/usr/lib64/python2.7/site-packages/pyanaconda/packaging/yumpayload.py", line 1583, in selectRequiredPackages
    map(self._selectYumPackage, self._requiredPackages)
  File "/usr/lib64/python2.7/site-packages/pyanaconda/packaging/yumpayload.py", line 1345, in _selectYumPackage
    raise NoSuchPackage(pkgid)
NoSuchPackage: dmraid

When looking on the installation media I notice the following in Packages.

...
11/25/2015  09:25 AM           175,760 dhcp-common-4.2.5-42.el7.centos.x86_64.rpm
11/25/2015  09:25 AM           131,088 dhcp-libs-4.2.5-42.el7.centos.x86_64.rpm
07/03/2014  08:08 PM           329,656 diffutils-3.3-4.el7.x86_64.rpm
11/25/2015  09:26 AM            84,156 dmidecode-2.12-9.el7.x86_64.rpm
08/05/2015  09:09 PM           234,140 dnsmasq-2.66-14.el7_1.x86_64.rpm
12/23/2015  07:50 PM         8,570,368 docker-engine-1.9.1-1.el7.centos.x86_64.rpm
12/23/2015  07:50 PM            21,200 docker-engine-selinux-1.9.1-1.el7.centos.noarch.rpm
07/03/2014  08:09 PM           103,496 dosfstools-3.0.20-9.el7.x86_64.rpm
....

**Comment by chlige** [comment]
I was able to remedy the issue by adding the main CentOS repository as an additional repository.

1. From installation menu click on "Installation Source" icon
![screenshot_1](https://cloud.githubusercontent.com/assets/4840583/14441440/59bdf160-fffa-11e5-88e3-7de6c3075cda.png)
2. Click on "+" in "Additional repositories" section
3. Add centos repository with URL http://mirror.centos.org/centos/7/os/x86_64
![screenshot_2](https://cloud.githubusercontent.com/assets/4840583/14441451/72cd713a-fffa-11e5-9f10-4189029f1d31.png)
4. Click "Done" and continue with installation.

**Comment by chrstphrchvz** [comment]
I encountered this issue on 3.8.13, however the Installation Source dialog was different (possibly since I was installing from a USB drive instead of a disc): the only option present for installation source was "On the network", so I had to select http:// instead of "Closest mirror" and then specify the centos repository URL, rather than enter it as an additional repository in @chlige's screenshot for step 3.
