### ISSUE TITLE
Checking for Rock-ons metadata even with the service disabled

### ISSUE THREAD

**Issue by ScarabMonkey** [rockstor/rockstor-core#1286]
I have never enabled the Rock-on service but my logs are full of failed attempts to connect to the rockons metastore.

```
[22/Apr/2016 13:41:48] ERROR [storageadmin.util:41] Error while processing remote metastore at http://rockstor.com/rockons/root.json. Lower level exception: HTTPConnectionPool(host='rockstor.com', port=80): Request timed out. (timeout=10)
[22/Apr/2016 13:41:48] ERROR [storageadmin.util:46] request path: /api/rockons/update method: POST data: <QueryDict: {}>
[22/Apr/2016 13:41:48] ERROR [storageadmin.util:47] exception: HTTPConnectionPool(host='rockstor.com', port=80): Request timed out. (timeout=10)
Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/rest_framework_custom/generic_view.py", line 40, in _handle_exception
    yield
  File "/opt/rockstor/src/rockstor/storageadmin/views/rockon.py", line 353, in _get_available
    response = requests.get(remote_root, timeout=10)
  File "/opt/rockstor/eggs/requests-1.1.0-py2.7.egg/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/opt/rockstor/eggs/requests-1.1.0-py2.7.egg/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/rockstor/eggs/requests-1.1.0-py2.7.egg/requests/sessions.py", line 279, in request
    resp = self.send(prep, stream=stream, timeout=timeout, verify=verify, cert=cert, proxies=proxies)
  File "/opt/rockstor/eggs/requests-1.1.0-py2.7.egg/requests/sessions.py", line 374, in send
    r = adapter.send(request, **kwargs)
  File "/opt/rockstor/eggs/requests-1.1.0-py2.7.egg/requests/adapters.py", line 215, in send
    raise Timeout(e)
Timeout: HTTPConnectionPool(host='rockstor.com', port=80): Request timed out. (timeout=10)
[22/Apr/2016 13:41:48] DEBUG [storageadmin.util:48] Current Rockstor version: 3.8-13
[22/Apr/2016 13:41:48] ERROR [smart_manager.data_collector:320] failed to update Rock-on metadata. low-level exception: Error while processing remote metastore at http://rockstor.com/rockons/root.json. Lower level exception: HTTPConnectionPool(host='rockstor.com', port=80): Request timed out. (timeout=10)
```

**Comment by phillxnet** [comment]
@ScarabMonkey  Another nice find. Thanks for opening an issue on this.

**Comment by MFlyer** [comment]
Cross ref to other issue #1281 because of network problems.

My opinion: My Rockstor dev env was under Watchguard firewall and i had similar problems till i moved it from "Trusted group" (having 4/5 particular block policies) to "optional group" (without blocking rules for zip, etc etc etc)

Flyer

**Comment by ScarabMonkey** [comment]
@MFlyer We keep all our internal servers secured from the Internet as much as possible ;)

**Comment by MFlyer** [comment]
@ScarabMonkey and you do the right thing! :smile: - But some dependencies have particular requirements that probably break firewall rules (ex.: call for zip files)
