### ISSUE TITLE
Web UI unavailable after snapshots fail to create

### ISSUE THREAD

**Issue by chrstphrchvz** [rockstor/rockstor-core#1448]
I say "after" based on what appears in `/opt/rockstor/var/log/rockstor.log` (snapshot task scheduled at 10PM daily); I'm not sure what the underlying reason for why the snapshots failed to create (the snapshots indeed does not exist according to `btrfs subvol list -s /mnt2/backup/`).

complete `/opt/rockstor/var/log/`: [rslogs.zip](https://github.com/rockstor/rockstor-core/files/493820/rslogs.zip)

excerpt of `/opt/rockstor/var/log/rockstor.log`:

```
[22/Sep/2016 20:00:02] ERROR [scripts.scheduled_tasks.snapshot:110] Failed to create snapshot at shares/backup/snapshots/backup-snapshot_201609222000
[22/Sep/2016 20:00:02] ERROR [scripts.scheduled_tasks.snapshot:111] OauthApp matching query does not exist.
Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/scripts/scheduled_tasks/snapshot.py", line 105, in main
    aw.api_call(url, data=data, calltype='post', headers=headers, save_error=False)
  File "/opt/rockstor/src/rockstor/cli/api_wrapper.py", line 79, in api_call
    self.set_token()
  File "/opt/rockstor/src/rockstor/cli/api_wrapper.py", line 48, in set_token
    app = OauthApp.objects.get(name=settings.OAUTH_INTERNAL_APP)
  File "/opt/rockstor/eggs/Django-1.6.11-py2.7.egg/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.6.11-py2.7.egg/django/db/models/query.py", line 310, in get
    self.model._meta.object_name)
DoesNotExist: OauthApp matching query does not exist.
[23/Sep/2016 08:49:26] ERROR [smart_manager.data_collector:744] Failed to update disk state.. exception: OauthApp matching query does not exist.
[23/Sep/2016 08:49:26] ERROR [smart_manager.data_collector:744] Failed to update pool state.. exception: OauthApp matching query does not exist.
[23/Sep/2016 08:49:26] ERROR [smart_manager.data_collector:744] Failed to update share state.. exception: OauthApp matching query does not exist.
[23/Sep/2016 08:49:26] ERROR [smart_manager.data_collector:744] Failed to update snapshot state.. exception: OauthApp matching query does not exist.
[23/Sep/2016 08:49:26] ERROR [smart_manager.data_collector:722] failed to update Rock-on metadata. low-level exception: OauthApp matching query does not exist.
[23/Sep/2016 08:53:52] ERROR [smart_manager.data_collector:744] Failed to update disk state.. exception: OauthApp matching query does not exist.
[23/Sep/2016 08:53:52] ERROR [smart_manager.data_collector:744] Failed to update pool state.. exception: OauthApp matching query does not exist.
[23/Sep/2016 08:53:52] ERROR [smart_manager.data_collector:744] Failed to update share state.. exception: OauthApp matching query does not exist.
[23/Sep/2016 08:53:52] ERROR [smart_manager.data_collector:744] Failed to update snapshot state.. exception: OauthApp matching query does not exist.
[23/Sep/2016 08:53:52] ERROR [smart_manager.data_collector:722] failed to update Rock-on metadata. low-level exception: OauthApp matching query does not exist.
[23/Sep/2016 08:56:52] DEBUG [smart_manager.data_collector:807] Listening on port http://127.0.0.1:8080 and on port 10843 (flash policy server)
[23/Sep/2016 20:00:03] ERROR [scripts.scheduled_tasks.snapshot:110] Failed to create snapshot at shares/backup/snapshots/backup-snapshot_201609232000
[23/Sep/2016 20:00:03] ERROR [scripts.scheduled_tasks.snapshot:111] OauthApp matching query does not exist.
Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/scripts/scheduled_tasks/snapshot.py", line 105, in main
    aw.api_call(url, data=data, calltype='post', headers=headers, save_error=False)
  File "/opt/rockstor/src/rockstor/cli/api_wrapper.py", line 79, in api_call
    self.set_token()
  File "/opt/rockstor/src/rockstor/cli/api_wrapper.py", line 48, in set_token
    app = OauthApp.objects.get(name=settings.OAUTH_INTERNAL_APP)
  File "/opt/rockstor/eggs/Django-1.6.11-py2.7.egg/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.6.11-py2.7.egg/django/db/models/query.py", line 310, in get
    self.model._meta.object_name)
DoesNotExist: OauthApp matching query does not exist.
[24/Sep/2016 00:00:02] ERROR [scripts.scheduled_tasks.pool_scrub:75] Failed to start scrub at pools/data/scrub
[24/Sep/2016 00:00:02] ERROR [scripts.scheduled_tasks.pool_scrub:77] OauthApp matching query does not exist.
Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/scripts/scheduled_tasks/pool_scrub.py", line 71, in main
    aw.api_call(url, data=None, calltype='post', save_error=False)
  File "/opt/rockstor/src/rockstor/cli/api_wrapper.py", line 79, in api_call
    self.set_token()
  File "/opt/rockstor/src/rockstor/cli/api_wrapper.py", line 48, in set_token
    app = OauthApp.objects.get(name=settings.OAUTH_INTERNAL_APP)
  File "/opt/rockstor/eggs/Django-1.6.11-py2.7.egg/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.6.11-py2.7.egg/django/db/models/query.py", line 310, in get
    self.model._meta.object_name)
DoesNotExist: OauthApp matching query does not exist.
[24/Sep/2016 00:00:02] ERROR [scripts.scheduled_tasks.pool_scrub:40] Failed to get scrub status at pools/data/scrub/status
[24/Sep/2016 00:00:02] ERROR [scripts.scheduled_tasks.pool_scrub:42] OauthApp matching query does not exist.
Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/scripts/scheduled_tasks/pool_scrub.py", line 37, in update_state
    status = aw.api_call(url, data=None, calltype='post', save_error=False)
  File "/opt/rockstor/src/rockstor/cli/api_wrapper.py", line 79, in api_call
    self.set_token()
  File "/opt/rockstor/src/rockstor/cli/api_wrapper.py", line 48, in set_token
    app = OauthApp.objects.get(name=settings.OAUTH_INTERNAL_APP)
  File "/opt/rockstor/eggs/Django-1.6.11-py2.7.egg/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.6.11-py2.7.egg/django/db/models/query.py", line 310, in get
    self.model._meta.object_name)
DoesNotExist: OauthApp matching query does not exist.
[24/Sep/2016 00:00:03] DEBUG [scripts.scheduled_tasks.pool_scrub:86] task(1) finished with state(error).
[24/Sep/2016 20:00:02] ERROR [scripts.scheduled_tasks.snapshot:110] Failed to create snapshot at shares/backup/snapshots/backup-snapshot_201609242000
[24/Sep/2016 20:00:02] ERROR [scripts.scheduled_tasks.snapshot:111] OauthApp matching query does not exist.
Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/scripts/scheduled_tasks/snapshot.py", line 105, in main
    aw.api_call(url, data=data, calltype='post', headers=headers, save_error=False)
  File "/opt/rockstor/src/rockstor/cli/api_wrapper.py", line 79, in api_call
    self.set_token()
  File "/opt/rockstor/src/rockstor/cli/api_wrapper.py", line 48, in set_token
    app = OauthApp.objects.get(name=settings.OAUTH_INTERNAL_APP)
  File "/opt/rockstor/eggs/Django-1.6.11-py2.7.egg/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.6.11-py2.7.egg/django/db/models/query.py", line 310, in get
    self.model._meta.object_name)
DoesNotExist: OauthApp matching query does not exist.
[25/Sep/2016 20:00:02] ERROR [scripts.scheduled_tasks.snapshot:110] Failed to create snapshot at shares/backup/snapshots/backup-snapshot_201609252000
[25/Sep/2016 20:00:02] ERROR [scripts.scheduled_tasks.snapshot:111] OauthApp matching query does not exist.
Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/scripts/scheduled_tasks/snapshot.py", line 105, in main
    aw.api_call(url, data=data, calltype='post', headers=headers, save_error=False)
  File "/opt/rockstor/src/rockstor/cli/api_wrapper.py", line 79, in api_call
    self.set_token()
  File "/opt/rockstor/src/rockstor/cli/api_wrapper.py", line 48, in set_token
    app = OauthApp.objects.get(name=settings.OAUTH_INTERNAL_APP)
  File "/opt/rockstor/eggs/Django-1.6.11-py2.7.egg/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.6.11-py2.7.egg/django/db/models/query.py", line 310, in get
    self.model._meta.object_name)
DoesNotExist: OauthApp matching query does not exist.
[26/Sep/2016 08:55:51] DEBUG [smart_manager.data_collector:807] Listening on port http://127.0.0.1:8080 and on port 10843 (flash policy server)
```

`systemctl -l status rockstor-bootstrap` reports similar errors as in #1066 (I don't know how to check if there's an issue with database--I am asked for a password when I run `/opt/rockstor/bin/django dbshell`.

output of `systemctl -l status rockstor-bootstrap` after trying to restart it:

```
● rockstor-bootstrap.service - Rockstor bootstrapping tasks
   Loaded: loaded (/etc/systemd/system/rockstor-bootstrap.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2016-09-26 12:38:23 CDT; 24min ago
  Process: 14281 ExecStart=/opt/rockstor/bin/bootstrap (code=exited, status=1/FAILURE)
 Main PID: 14281 (code=exited, status=1/FAILURE)

Sep 26 12:38:23 nnbackup bootstrap[14281]: Exception occured while bootstrapping. This could be because rockstor.service is still starting up. will wait 2 seconds and try again. Exception: OauthApp matching query does not exist.
Sep 26 12:38:23 nnbackup bootstrap[14281]: Exception occured while bootstrapping. This could be because rockstor.service is still starting up. will wait 2 seconds and try again. Exception: OauthApp matching query does not exist.
Sep 26 12:38:23 nnbackup bootstrap[14281]: Exception occured while bootstrapping. This could be because rockstor.service is still starting up. will wait 2 seconds and try again. Exception: OauthApp matching query does not exist.
Sep 26 12:38:23 nnbackup bootstrap[14281]: Exception occured while bootstrapping. This could be because rockstor.service is still starting up. will wait 2 seconds and try again. Exception: OauthApp matching query does not exist.
Sep 26 12:38:23 nnbackup bootstrap[14281]: Exception occured while bootstrapping. This could be because rockstor.service is still starting up. will wait 2 seconds and try again. Exception: OauthApp matching query does not exist.
Sep 26 12:38:23 nnbackup bootstrap[14281]: Max attempts(15) reached. Connection errors persist. Failed to bootstrap. Error: OauthApp matching query does not exist.
Sep 26 12:38:23 nnbackup systemd[1]: rockstor-bootstrap.service: main process exited, code=exited, status=1/FAILURE
Sep 26 12:38:23 nnbackup systemd[1]: Failed to start Rockstor bootstrapping tasks.
Sep 26 12:38:23 nnbackup systemd[1]: Unit rockstor-bootstrap.service entered failed state.
Sep 26 12:38:23 nnbackup systemd[1]: rockstor-bootstrap.service failed.
```

**Comment by sfranzen** [comment]
Intriguing, this is indeed the same error I had and haven't had since then. Unfortunately I still don't know how to reproduce this, so you can try similar steps as I did in #1066. For reference, the db password is the same as the username.

**Comment by chrstphrchvz** [comment]
The database appears to have the same issue as in #1066:
```
storageadmin=# TABLE storageadmin_oauthapp;
 id | application_id | name | user_id 
----+----------------+------+---------
(0 rows)
```

Unforturnately, running `initrock` doesn't seem to fix the issue.

Output from `initrock`:

```
# /opt/rockstor/bin/initrock --help
2016-09-28 17:28:55,153: Supported kernel(/boot/vmlinuz-4.6.0-1.el7.elrepo.x86_64) is already the default
2016-09-28 17:28:55,286: /etc/rc.d/rc.local looks correct. Not updating.
2016-09-28 17:28:55,287: Checking for flash and Running flash optimizations if appropriate.
2016-09-28 17:28:59,846: Updating the timezone from the system
2016-09-28 17:28:59,847: system timezone = America/Chicago
2016-09-28 17:28:59,849: Updating sshd_config
2016-09-28 17:28:59,853: sshd_config already has the updates. Leaving it unchanged.
2016-09-28 17:28:59,853: Running prepdb...
2016-09-28 17:29:04,625: stopping firewalld...
2016-09-28 17:29:04,711: firewalld stopped and disabled
2016-09-28 17:29:04,848: Registered task: fs.btrfs.start_balance
2016-09-28 17:29:16,251: rockstor service looks correct. Not updating.
2016-09-28 17:29:16,252: rockstor-bootstrap.service looks correct. Not updating.
# 
```

**Comment by sfranzen** [comment]
You probably have to remove the hidden file `/opt/rockstor/.initrock` before running the script in order to get the database entry back.

Now, in hope of getting at the source of this bug, the output of `journalctl -u postgresql` may contain useful details. We know that something between the previous scheduled task on 21 September and the one on the 22nd has caused this database entry to gone missing... The best result would of course be the snapshot itself being the cause, so perhaps you should first try performing a manual snapshot identical to the scheduled one once your system is back up.

**Comment by chrstphrchvz** [comment]
Unfortunately I no longer have access to the affected system nor any other information for following up on this issue.

**Comment by phillxnet** [comment]
@chrstphrchvz Thanks for the update. As @sfranzen points out this is a strange one and the linked issue did have workarounds but as you say, without a reproducer we are a little at a loose end. At least the missing db entry is a start. And since this issue was opened I think we have moved from the prior south db migration system to the one build into Django itself so hopefully that should be an 'upgrade'. I haven't seen any more reports of this for a while but time will tell.

Thanks again @chrstphrchvz and @sfranzen for your efforts on this one.
