### ISSUE TITLE
Manual snapshot creation fails

### ISSUE THREAD

**Issue by sitic** [rockstor/rockstor-core#1465]
When creating a snapshot manually from the share view it fails regardless if writeable is set to yes or no with:

```
[07/Oct/2016 01:11:25] ERROR [storageadmin.util:47] exception: writable must be a boolean, not <type 'unicode'>
Traceback (most recent call last):
  File "/opt/rockstor/eggs/gunicorn-0.16.1-py2.7.egg/gunicorn/workers/sync.py", line 34, in run
    client, addr = self.socket.accept()
  File "/usr/lib64/python2.7/socket.py", line 202, in accept
    sock, addr = self._sock.accept()
error: [Errno 11] Resource temporarily unavailable
[07/Oct/2016 01:11:25] DEBUG [storageadmin.util:48] Current Rockstor version: 3.8-14.17
```

Seems to be introduced with 87998df6eb919a456c977b28b2378d3b82de3267, automatic snapshots work.

**Comment by FroggyFlox** [comment]
Closing this issue as legacy.
