### ISSUE TITLE
[Bug] Rockons don't update

### ISSUE THREAD

**Issue by maxhq** [rockstor/rockstor-core#1613]
I accidentially found the following log entries in `/opt/rockstor/var/log/rockstor.log`.

Especially interesting is the line saying _... Errors occurred while processing updates ..._, which obviously tells the reason why I never get any Rockon updates? Or am I misunderstanding this and Rockons never auto-update? The [documentation on Rockons](http://rockstor.com/docs/docker-based-rock-ons/overview.html) does not mention anything.
```
[11/Jan/2017 01:23:03] DEBUG [storageadmin.util:48] Current Rockstor version: 3.8.16-2
[11/Jan/2017 01:23:03] ERROR [storageadmin.util:47] exception: Cannot add/remove volume definitions of the container(plex-linuxserver.io) as it belongs to an installed Rock-on(Plex). Uninstall it first and try again.
Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/storageadmin/views/rockon.py", line 105, in post
    self._create_update_meta(r, rockons[r])
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/opt/rockstor/src/rockstor/storageadmin/views/rockon.py", line 263, in _create_update_meta
    handle_exception(Exception(e_msg), self.request)
  File "/opt/rockstor/src/rockstor/storageadmin/util.py", line 49, in handle_exception
    raise RockStorAPIException(detail=e_msg, trace=traceback.format_exc())
[11/Jan/2017 01:23:03] DEBUG [storageadmin.util:48] Current Rockstor version: 3.8.16-2
[11/Jan/2017 01:23:03] ERROR [storageadmin.util:47] exception: Errors occurred while processing updates for following Rock-ons. Plex: ['Cannot add/remove volume definitions of the container(plex-linuxserver.io) as it belongs to an installed Rock-on(Plex). Uninstall it first and try again.', 'Traceback (most recent call last):\n  File "/opt/rockstor/src/rockstor/storageadmin/views/rockon.py", line 105, in post\n    self._create_update_meta(r, rockons[r])\n  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/utils/decorators.py", line 145, in inner\n    return func(*args, **kwargs)\n  File "/opt/rockstor/src/rockstor/storageadmin/views/rockon.py", line 263, in _create_update_meta\n    handle_exception(Exception(e_msg), self.request)\n  File "/opt/rockstor/src/rockstor/storageadmin/util.py", line 49, in handle_exception\n    raise RockStorAPIException(detail=e_msg, trace=traceback.format_exc())\nRockStorAPIException: [\'Cannot add/remove volume definitions of the container(gogs) as it belongs to an installed Rock-on(Gogs). Uninstall it first and try again.\', \'Traceback (most recent call last):\\n  File "/opt/rockstor/eggs/gunicorn-0.16.1-py2.7.egg/gunicorn/workers/sync.py", line 34, in run\\n    client, addr = self.socket.accept()\\n  File "/usr/lib64/python2.7/socket.py", line 202, in accept\\n    sock, addr = self._sock.accept()\\nerror: [Errno 11] Resource temporarily unavailable\\n\']\n']
Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/storageadmin/views/rockon.py", line 105, in post
    self._create_update_meta(r, rockons[r])
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/opt/rockstor/src/rockstor/storageadmin/views/rockon.py", line 263, in _create_update_meta
    handle_exception(Exception(e_msg), self.request)
  File "/opt/rockstor/src/rockstor/storageadmin/util.py", line 49, in handle_exception
    raise RockStorAPIException(detail=e_msg, trace=traceback.format_exc())
RockStorAPIException: ['Cannot add/remove volume definitions of the container(plex-linuxserver.io) as it belongs to an installed Rock-on(Plex). Uninstall it first and try again.', 'Traceback (most recent call last):\n  File "/opt/rockstor/src/rockstor/storageadmin/views/rockon.py", line 105, in post\n    self._create_update_meta(r, rockons[r])\n  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/utils/decorators.py", line 145, in inner\n    return func(*args, **kwargs)\n  File "/opt/rockstor/src/rockstor/storageadmin/views/rockon.py", line 263, in _create_update_meta\n    handle_exception(Exception(e_msg), self.request)\n  File "/opt/rockstor/src/rockstor/storageadmin/util.py", line 49, in handle_exception\n    raise RockStorAPIException(detail=e_msg, trace=traceback.format_exc())\nRockStorAPIException: [\'Cannot add/remove volume definitions of the container(gogs) as it belongs to an installed Rock-on(Gogs). Uninstall it first and try again.\', \'Traceback (most recent call last):\\n  File "/opt/rockstor/eggs/gunicorn-0.16.1-py2.7.egg/gunicorn/workers/sync.py", line 34, in run\\n    client, addr = self.socket.accept()\\n  File "/usr/lib64/python2.7/socket.py", line 202, in accept\\n    sock, addr = self._sock.accept()\\nerror: [Errno 11] Resource temporarily unavailable\\n\']\n']
```

**Comment by Fredrik81** [comment]
This would explain why i never got updates to my rockons. For sabnzb i had to uninstall and reinstall to get the new version. I will dig thru logs to see if i have same entries.

**Comment by HBDK** [comment]
i get a similar error (although for nzbget instead of plex) and i can't start, stop or install  and rockons.

**Comment by d-fay** [comment]
I recently updated from an older version running on a older kernel and was able to start and stop rock-ons just fine. I've only turned one on (Plex) but I can no longer turn it off as it will immediately turn itself back on.

**Comment by phillxnet** [comment]
@d-fay I don't think your issue is the same as originally expressed in this issue. I'd like to request that you start a new forum post so that your particular report can be investigated:

https://forum.rockstor.com/

Put as much detail as you can about what you have done and what is not working as expected.

The issues here is likely not what you have reported and @maxhq's original report concerns Rock-on updates and the follow-ups indicate a requirement, in some cases (usually non linuxserver.io images) to uninstall and re-install to get an update. This behaviour is ongoing. But they are not experiencing the inability to turn a Rock-on off. Also note that if you your update was from a very old version of Rockstor then you may find that a simple reboot resolves your issue as we changed from an older docker to docker-ce quite some time ago. See if a reboot sorts your issue and if not then do start a fresh thread on the forum so our community members there can help resolve whats going wrong. Remember to post you exact Rockstor version:
```
yum info rockstor
```
to be sure. And a history of what lead to this situation.

Thanks for the report.

**Comment by FroggyFlox** [comment]
Closing this issue as we've made substantial improvements to our Rock-Ons code since this issue creation. Moreover, Rock-Ons update mechanism has now been added to our docs.
