### ISSUE TITLE
Timeout problem

### ISSUE THREAD

**Issue by PhilippeAB** [rockstor/rockstor-core#1644]
Rockstor timeout on btrfs command

When a snapshot take some time rockstor timeout and lost track off the snapshot
This could be dangerous because with lots off shares the snapshot number will bring down your server

**Comment by MFlyer** [comment]
Hi @PhilippeAB and thanks for opening this issue

Can you provide some logs or similar??

@schakrava - @phillxnet 

Mirko

**Comment by MFlyer** [comment]
Hi @PhilippeAB ,
investigating this checking our snapshot code without any further logs, my question: do you still experience snapshots timeout??

Let me explain:
taking snapshots itself is a small "atomic" operation (create btrfs snapshot + save snapshot data to Rockstor db), while deleting old snapshots can provide timeout.
Every Rockstor scheduled snapshots task has a max num of snapshots (ex. 20), so when creating a new snapshot first we check current total snapshots and delete every max_num_snapshots+n, then we create the new one.
Thinking about your recent issue probably Django got timeout on rest calls waiting to long while trying to delete 500more snapshots

M.

**Comment by PhilippeAB** [comment]
Not anymore the filesystem is dead.
I can't really explain, but after each snapshot operation btrfs-transacti was stuck à 100% cpu and blocking all other IO for few minutes at the end.
In the rockstor database there was less than 500 snapshot but more than 9000 on the filesystem.
In the database there was only old snapshot. (more than 1 month)
Either the deletion or creation have a timeout problem in rockstor.
we should have had 22 snapshots for each of our 15 shares

**Comment by MFlyer** [comment]
Hi @PhilippeAB,

> Not anymore the filesystem is dead.

you're right, sorry, didn't remember it!

That 9000more snaps vs 500db entries is quite impossible to understand without some logs:
snapshots > db entries for snapshots means something went wrong while tracking system snapshots and this probably made Rockstor not deleting old snapshots, but I can't understand it without further infos (expected results: snapshots ok -> log to db, so you should have snaps number always equal to db entries or, at least, db entries > snapshots if something failed and Rockstor waiting next snapshot cycle to fix it)
Back to my previous post: if old snapshots delete operation fails Rockstor stops and doesn't create new snapshots.
Do you remember how you had max snapshots for those shares? this hopefully will help a bit to understand this issue

Mirko

**Comment by PhilippeAB** [comment]
Filesystem is dead but I still have old rockstor log.
Hope this could help

[01/Feb/2017 12:01:02] ERROR [fs.btrfs:721] Error running a command. cmd = ['/sbin/btrfs', 'qgroup', 'assign', '0/49303', '2015/28', '/mnt2//DataPool']. rc = 1. stdout = ['']. stderr = ['ERROR: unable to assign quota group: Invalid argument', '']
Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/fs/btrfs.py", line 704, in qgroup_assign
    run_command([BTRFS, 'qgroup', 'assign', qid, pqid, mnt_pt])
  File "/opt/rockstor/src/rockstor/system/osi.py", line 109, in run_command
    raise CommandException(cmd, out, err, rc)
CommandException: Error running a command. cmd = ['/sbin/btrfs', 'qgroup', 'assign', '0/49303', '2015/28', '/mnt2//DataPool']. rc = 1. stdout = ['']. stderr = ['ERROR: unable to assign quota group: Invalid argument', '']
[01/Feb/2017 12:01:02] ERROR [storageadmin.util:47] exception: Error running a command. cmd = ['/sbin/btrfs', 'qgroup', 'assign', '0/49303', '2015/28', '/mnt2//DataPool']. rc = 1. stdout = ['']. stderr = ['ERROR: unable to assign quota group: Invalid argument', '']
Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/rest_framework_custom/generic_view.py", line 40, in _handle_exception
    yield
  File "/opt/rockstor/src/rockstor/storageadmin/views/snapshot.py", line 152, in post
    writable=writable)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/opt/rockstor/src/rockstor/storageadmin/views/snapshot.py", line 127, in _create
    qgroup_assign(qgroup_id, share.pqgroup, ('%s/%s' % (settings.MNT_PT, share.pool.name)))
  File "/opt/rockstor/src/rockstor/fs/btrfs.py", line 722, in qgroup_assign
    raise e
CommandException: Error running a command. cmd = ['/sbin/btrfs', 'qgroup', 'assign', '0/49303', '2015/28', '/mnt2//DataPool']. rc = 1. stdout = ['']. stderr = ['ERROR: unable to assign quota group: Invalid argument', '']
[01/Feb/2017 12:01:02] DEBUG [storageadmin.util:48] Current Rockstor version: 3.8.16-0
[01/Feb/2017 12:01:02] ERROR [scripts.scheduled_tasks.snapshot:111] Failed to create snapshot at shares/share1/snapshots/share1_Hourly_201702011201
[01/Feb/2017 12:01:02] ERROR [scripts.scheduled_tasks.snapshot:112] 500 Server Error: INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/scripts/scheduled_tasks/snapshot.py", line 106, in main
    aw.api_call(url, data=data, calltype='post', headers=headers, save_error=False)
  File "/opt/rockstor/src/rockstor/cli/api_wrapper.py", line 121, in api_call
    r.raise_for_status()
  File "/opt/rockstor/eggs/requests-1.1.0-py2.7.egg/requests/models.py", line 638, in raise_for_status
    raise http_error
HTTPError: 500 Server Error: INTERNAL SERVER ERROR

**Comment by MFlyer** [comment]
@schakrava & @phillxnet 

@PhilippeAB helped to find a flaw over snapshots creation:

From snapshot.py view

```python
    def _create(self, share, snap_name, request, uvisible,
                snap_type, writable):
        if (Snapshot.objects.filter(share=share, name=snap_name).exists()):
            e_msg = ('Snapshot(%s) already exists for the Share(%s).' %
                     (snap_name, share.name))
            handle_exception(Exception(e_msg), request)

        snap_size = 0
        qgroup_id = '0/na'
        if (snap_type == 'replication'):
            writable = False
        add_snap(share.pool, share.subvol_name, snap_name, writable)
        snap_id = share_id(share.pool, snap_name)
        qgroup_id = ('0/%s' % snap_id)
        qgroup_assign(qgroup_id, share.pqgroup, ('%s/%s' % (settings.MNT_PT,
                                                            share.pool.name)))
        snap_size, eusage = volume_usage(share.pool, qgroup_id)
        s = Snapshot(share=share, name=snap_name, real_name=snap_name,
                     size=snap_size, qgroup=qgroup_id,
                     uvisible=uvisible, snap_type=snap_type,
                     writable=writable)
        s.save()
        return Response(SnapshotSerializer(s).data)
```

When creating a new snapshot snapshot first we have it with `add_snap`, then we assign its qgroup to parent 2015/* qgroup with `qgroup_assign` (here @PhilippeAB environment failing) and finally save it to backend DB, but all these ops are atomic so like on this issue we can have snapshot created but not assigned to parent qgroup and saved to db, this generating infinite snapshots (current snapshots number always < user max snapshots)

My first suggestion: use `btrfs sub snapshot` with `-i` param (assign snapshot to qgroup while creating it), so if we fail on assign we fail on creation too and viceversa and so doing we don't need to check before saving to db - no snapshot -> no db write, only 2 ops

Back to @PhilippeAB :
that log really helped to find this flaw, but unfortunately doesn't help with your issue at all.
Now we know qgroup assign failed, but snapshot creation not (this is the reason why you have 9000 snapshots not stored on Rockstor db), but we can't say why it failed (snapshot qgroup error or parent qgroup error). My suspicion more on qgroup id (that associated to share)

Mirko

**Comment by MFlyer** [comment]
Meanwhile found this too #1645  (minor bug, blocking snapshots)

Mirko

**Comment by phillxnet** [comment]
@MFlyer and @PhilippeAB Nice find.

@MFlyer I like the suggestion to simplify the snapshot command as then, as you say, no snapshot, not db entry. This could be considered a retrograde step form the point of view that a snapshot is then not made when there is a related error but without this we have the observed possibility of snapshot overload which in turn is catastrophic to the whole pool anyway, and with no UI visibility until it's too late. I haven't looked at that code though but given you have then great. Not something I can get to soon though myself I'm afraid.

**Comment by MFlyer** [comment]
Hi @phillxnet ,
getting on this, it's a 2-3 lines patch, don't worry :wink:

**Comment by MFlyer** [comment]
To @schakrava patch for this will be on #1625 to avoid write/rebase/write on snapshot.py view (changed over share usage PR)

**Comment by phillxnet** [comment]
@MFlyer I'm assuming that this did not end up going into #1625, just trying to tidy up where we are at on this one as it looked like a really nice find.

**Comment by MFlyer** [comment]
Hi @phillxnet , to be honest: I don't remember xD will check it

**Comment by Hooverdan96** [comment]
@phillxnet, @MFlyer, upon checking whether the recommendation ever made it, it doesn't look like it (the last merged PR in that area seems to have been around 3 years ago and that was mostly related to formatting). Implementing the `-i` flag would have at least required changes in both the `snapshot.py` as well as in the `btrfs.py` coding, around here:

https://github.com/rockstor/rockstor-core/blob/4d60a2c683140aaa10a8e5b201157163cc9a898b/src/rockstor/fs/btrfs.py#L1212-L1223

which is called by
https://github.com/rockstor/rockstor-core/blob/b870fa2f0264a8696440cccbc2526c50617ef773/src/rockstor/fs/btrfs.py#L1240-L1250

which is called from the `snapshot.py`

For the snapshot usage of the `add_snap_helper` method one has to consider that it's also used by the `add_clone` method (also in the `btrfs.py` file) wich is called from `add_clone_helpers.py`.

It seems, (and I could be wrong) that there, the snapshot/clone process is also separated into the two activities of creating the clone first and then deal with the `qgroup` assignment. So, this perceived weakness could be addressed for both use cases (though only observed for one, probably due to lack of usage) by, e.g., passing a qgroup that can then be used by the `add_snap_helper` function to assign right away and return the appropriate error up the stack if either one of the steps (snap/clone vs. qgroup assignment) fails.

**Comment by phillxnet** [comment]
The findings here need to be re-issued for clarification on the proposed changes up-front, and this issue closed as it pertained, in part, to other issues related to a failing fs I think.

I.e. Issue @Hooverdan96 summary in the above https://github.com/rockstor/rockstor-core/issues/1644#issuecomment-1866974359 which in-tun built on @MFlyer 's exposition.

The original text here is too vague and we have since and are on-going with improvements re backgrounding (scheduling) the longer running btrfs commands.
