### ISSUE TITLE
Samba export's "Comment" field only allows ASCII chars

### ISSUE THREAD

**Issue by maxhq** [rockstor/rockstor-core#1648]
Trying to add e.g. a german umlaut (ü) into the comment field in "File Sharing" - "Samba" - "Add Samba Export" gives the following error:

```
Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/rest_framework_custom/generic_view.py", line 41, in _handle_exception
    yield
  File "/opt/rockstor/src/rockstor/storageadmin/views/samba.py", line 162, in post
    refresh_smb_config(list(SambaShare.objects.all()))
  File "/opt/rockstor/src/rockstor/system/samba.py", line 88, in refresh_smb_config
    rockstor_smb_config(tfo, exports)
  File "/opt/rockstor/src/rockstor/system/samba.py", line 60, in rockstor_smb_config
    fo.write('    comment = %s\n' % e.comment)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 27: ordinal not in range(128)
```

**Comment by MFlyer** [comment]
Once again thanks @maxhq ,
we've fixed it :)

Mirko

**Comment by maxhq** [comment]
Great!
