### ISSUE TITLE
Kernel update

### ISSUE THREAD

**Issue by ParkerPass** [rockstor/rockstor-core#1732]
After 2 recent updates system reporting an old kernel is beeing used
You are running an unsupported kernel(4.8.7-1.el7.elrepo.x86_64). Some features may not work properly. Please reboot and the system will automatically boot using the supported kernel(4.10.6-1.el7.elrepo.x86_64)

System HP mini server G7 with modified BIOS, 16gb RAM 32 gb boot SSD and 5x 3TB WD-Red
![image](https://user-images.githubusercontent.com/16073532/27211627-7d9e1e26-520f-11e7-8bfb-46bf92d02349.png)

**Comment by ParkerPass** [comment]
3.9.0-9 produced additional errors

            Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/rest_framework_custom/generic_view.py", line 41, in _handle_exception
    yield
  File "/opt/rockstor/src/rockstor/storageadmin/views/network.py", line 176, in get_queryset
    self._refresh_devices()
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/opt/rockstor/src/rockstor/storageadmin/views/network.py", line 144, in _refresh_devices
    dmap = network.devices()
  File "/opt/rockstor/src/rockstor/system/network.py", line 49, in devices
    o2, e2, r2 = run_command([NMCLI, 'd', 'show', dev])
  File "/opt/rockstor/src/rockstor/system/osi.py", line 115, in run_command
    raise CommandException(cmd, out, err, rc)
CommandException: Error running a command. cmd = /usr/bin/nmcli d show veth80ac00a. rc = 10. stdout = ['']. stderr = ["Error: Device 'veth80ac00a' not found.", '']

**Comment by MFlyer** [comment]
Hi @ParkerPass ,
before checking for kernel updates probably we need to fix your network.
Did you change network adapters?
M.
