### ISSUE TITLE
useradd error upon config restore

### ISSUE THREAD

**Issue by FroggyFlox** [rockstor/rockstor-core#1774]
1. In a first instance of rockstor 3.9.1-0, create a new user "testconfuser" with default settings.
2. Backup config and download .json.gz file.
3. In another install of Rockstor 3.9.1-0, import pool from previous install (was successfull), and then try to restore backup. No error is displayed on the webUI (thanks to #1773 fix), but the following can be seen in the logs:
- rockstor.log
```
[28/Jul/2017 12:25:59] ERROR [storageadmin.util:44] exception: Group(test) already exists. Choose a different one
Traceback (most recent call last):
  File "/opt/rockstor/eggs/gunicorn-0.16.1-py2.7.egg/gunicorn/workers/sync.py", line 34, in run
    client, addr = self.socket.accept()
  File "/usr/lib64/python2.7/socket.py", line 202, in accept
    sock, addr = self._sock.accept()
error: [Errno 11] Resource temporarily unavailable
[28/Jul/2017 12:25:59] ERROR [storageadmin.views.config_backup:49] Exception occured while creating resource: https://localhost/api/groups. payload: {u'admin': True, u'groupname': u'test', u'gid': 1000}. 
exception: 400 Client Error: BAD REQUEST. Moving on.
[28/Jul/2017 12:25:59] ERROR [storageadmin.util:44] exception: User(test) already exists. Please choose a different username
Traceback (most recent call last):
  File "/opt/rockstor/eggs/gunicorn-0.16.1-py2.7.egg/gunicorn/workers/sync.py", line 34, in run
    client, addr = self.socket.accept()
  File "/usr/lib64/python2.7/socket.py", line 202, in accept
    sock, addr = self._sock.accept()
error: [Errno 11] Resource temporarily unavailable
[28/Jul/2017 12:25:59] ERROR [storageadmin.views.config_backup:49] Exception occured while creating resource: https://localhost/api/users. payload: {u'username': u'test', u'public_key': None, u'shell': u'/bin/bash', u'group': 1, u'uid': 1000, u'admin': True, u'homedir': u'/home/test', u'gid': 1000, u'user': 1, 'password': 'rockstor', u'email': None, u'smb_shares': []}. exception: 400 Client Error: BAD REQUEST. Moving on.
[28/Jul/2017 12:26:00] ERROR [storageadmin.util:44] exception: Error running a command. cmd = /usr/sbin/useradd -s /bin/bash -m -u 1001 testconfuser. rc = 9. stdout = ['']. stderr = ['useradd: group testconfuser exists - if you want to add this user to that group, use -g.', '']
Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/rest_framework_custom/generic_view.py", line 41, in _handle_exception
    yield
  File "/opt/rockstor/src/rockstor/storageadmin/views/user.py", line 150, in post
    gid=invar['gid'])
  File "/opt/rockstor/src/rockstor/system/users.py", line 185, in useradd
    return run_command(cmd)
  File "/opt/rockstor/src/rockstor/system/osi.py", line 115, in run_command
    raise CommandException(cmd, out, err, rc)
CommandException: Error running a command. cmd = /usr/sbin/useradd -s /bin/bash -m -u 1001 testconfuser. rc = 9. stdout = ['']. stderr = ['useradd: group testconfuser exists - if you want to add this user to that group, use -g.', '']
[28/Jul/2017 12:26:00] ERROR [storageadmin.views.config_backup:49] Exception occured while creating resource: https://localhost/api/users. payload: {u'username': u'testconfuser', u'public_key': None, u'shell': u'/bin/bash', u'group': 2, u'uid': 1001, u'admin': False, u'homedir': u'/home/testconfuser', u'gid': 1001, u'user': None, 'password': 'rockstor', u'email': None, u'smb_shares': []}. exception: 500 Server Error: INTERNAL SERVER ERROR. Moving on.
```
Please note, the user "test" was the user created at first boot of both Rockstor instances. and thus already existed prior to restoring the config backup.

- journalctl -f
```Jul 28 12:25:59 rocktest3 groupadd[12258]: group added to /etc/group: name=testconfuser, GID=1001
Jul 28 12:25:59 rocktest3 groupadd[12258]: group added to /etc/gshadow: name=testconfuser
Jul 28 12:25:59 rocktest3 groupadd[12258]: new group: name=testconfuser, GID=1001
Jul 28 12:26:00 rocktest3 useradd[12265]: failed adding user 'testconfuser', exit code: 9
Jul 28 12:26:00 rocktest3 systemd[1]: Started Shell In A Box daemon.
Jul 28 12:26:00 rocktest3 systemd[1]: Starting Shell In A Box daemon...
```

In the "Groups" page of the webUI, the group "testconfuser" can be seen, but the user "testconfuser" cannot be seen in the "Users" page.

**Comment by FroggyFlox** [comment]
Also, please note the two lines related to Shell In A Box:
```
Jul 28 12:26:00 rocktest3 systemd[1]: Started Shell In A Box daemon.
Jul 28 12:26:00 rocktest3 systemd[1]: Starting Shell In A Box daemon...
```
These appeared upon restoring the backup... even though I never turned the "Shell In A Box" service on. How is that possible?

**Comment by phillxnet** [comment]
Currently having a look at this issue now.

**Comment by phillxnet** [comment]
So when restoring non existent user who was part of an existing group we are failing to apply the saved (in config backup file) gid of that user.
Then our adduser() function:
src/rockstor/system/users.py
doesn't know to apply the '-g gid' switch set which correlates with the observed issue error.
Tracing backwards to find gid loss.

**Comment by phillxnet** [comment]
Looks like UserMixin _validate_input() is swallowing / masking gid.
This doesn't affect user creation via web interface (when specifying group) as the key used then is 'group'. Whereas user restore function uses key 'gid'.

I will attempt to prepare a pr to address this issue shortly.

**Comment by phillxnet** [comment]
A proposed fix for this issue has involved debugging and enhancing the existing user create mechanism. A commit involving the code will be associated with this issue shortly (once more testing has taken place) and a pull request will follow shortly there after.

**Comment by phillxnet** [comment]
Re-based on current master to aid in final testing and pr preparation.
My prior GitHub resident branch was first deleted to avoid adding duplicate commits and then re-created after a local re-base.
