### ISSUE TITLE
3-9.0 shares fail to mount

### ISSUE THREAD

**Issue by dragon2611** [rockstor/rockstor-core#1778]
I suspect it's because I've had to turn quotas off in the past, or something didn't upgrade correctly

rockstor.log gets flooded with

```
 [30/Jul/2017 13:52:32] ERROR [storageadmin.middleware:32] Exception occured while processing a request. Path: /api/commands/bootstrap method: POST
[30/Jul/2017 13:52:32] ERROR [storageadmin.middleware:33] need more than 2 values to unpack
Traceback (most recent call last):
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/views.py", line 452, in dispatch
    response = self.handle_exception(exc)
  File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/views.py", line 449, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/opt/rockstor/src/rockstor/storageadmin/views/command.py", line 95, in post
    import_shares(p, request)
  File "/opt/rockstor/src/rockstor/storageadmin/views/share_helpers.py", line 83, in import_shares
    volume_usage(pool, share.qgroup, share.pqgroup)
ValueError: need more than 2 values to unpack
[30/Jul/2017 13:52:37] ERROR [storageadmin.middleware:32] Exception occured while processing a request. Path: /api/commands/bootstrap method: POST
[30/Jul/2017 13:52:37] ERROR [storageadmin.middleware:33] need more than 2 values to unpack

```

This causes rockstor-bootstrap to fail and the subvolumes don't get mounted.

**Comment by phillxnet** [comment]
@dragon2611 Thanks for the report. This looks very much like a duplicate of:
#1769 "rogue share.pqgroup db field fails share mounts"
which has a pending fix by way of changes in pull request:
#1770 "rogue share.pqgroup db field fails share mounts."
Hopefully the changes there will pass review and if they are in deed a fix then after they are applied a reboot should get you up and running again.

**Comment by dragon2611** [comment]
I manually mounted the sub-volumes so I can at least access the data via the share.
Ultimately it would be good if it was possible to disable quotas as they kill rockstor when deleting a lot of snapshots or re-balancing,

In the short term if there was a script to re-enable quotas and set them up the way rockstor is expecting that might help.

**Comment by phillxnet** [comment]
@dragon2611 The prior referenced pr to address your reported log error has now been merged and release as of testing channel update verion 3.9.1-3:
https://forum.rockstor.com/t/dev-log-for-3-9-2/3532/8
So hopefully that should also fix your system. A reboot will be required however, but yes quota manipulations can 'upset' Rockstor's system state reporting. But in your reported case I think the referenced fix should at least sort what the log is complaining about. If you no longer receive this log report after applying the update (assuming you are on testing channel) then please close this issue as:
a duplicate of #1769

**Comment by dragon2611** [comment]
I think that particular server is still getting stable updates, not sure how as I would have through that had expired by now.  

I'll change it to the testing channel and update/reboot, hopefully tonight if I get a chance, I don't currently have remote access on that box.

**Comment by phillxnet** [comment]
@dragon2611 Might get you up and running as normal again and you can always change back to stable updates once you have this fix. Though don't risk testing channel updates unless you really have to. But given the current poorly nature of your install it may be worth the risk: your call obviously.

**Comment by dragon2611** [comment]
@phillxnet unless it's messing around with the underlaying BTRFS stuff then i'm ok with testing updates, important stuff is backed up/replicated.

It was dead for ~3 Months after the CPU/Motherboard died anyway, I've only just recently picked it up from the co-lo it was in and replaced the board (It was a VM so Rockstor won't have seen any hardware changes other than CPU going from Intel to AMD)

**Comment by dragon2611** [comment]
@phillxnet update seems to have fixed the issue as far as I can tell 👍

**Comment by phillxnet** [comment]
@dragon2611 Cool, and thanks for the feedback. Glad it's sorted for your.
