### ISSUE TITLE
Unable to create Samba export

### ISSUE THREAD

**Issue by aherbach88** [rockstor/rockstor-core#1813]
When trying to create a share in 3.9.1-10 I get an error of "Unknown internal error doing a POST to /api/samba" in the WebUI, while tailing the rockstor log, I get the following error (my share is called systems):

[12/Sep/2017 14:33:53] ERROR [storageadmin.middleware:33] invalid literal for int() with base 10: 'systems'
Traceback (most recent call last):
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/views.py", line 452, in dispatch
    response = self.handle_exception(exc)
  File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/views.py", line 449, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/opt/rockstor/src/rockstor/storageadmin/views/samba.py", line 135, in post
    request.data['shares']]
  File "/opt/rockstor/src/rockstor/storageadmin/views/share.py", line 72, in _validate_share
    share = Share.objects.get(id=sid)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/db/models/query.py", line 325, in get
    clone = self.filter(*args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/db/models/query.py", line 679, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/db/models/query.py", line 697, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/db/models/sql/query.py", line 1310, in add_q
    clause, require_inner = self._add_q(where_part, self.used_aliases)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/db/models/sql/query.py", line 1338, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/db/models/sql/query.py", line 1209, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/db/models/sql/query.py", line 1102, in build_lookup
    return final_lookup(lhs, rhs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/db/models/lookups.py", line 105, in __init__
    self.rhs = self.get_prep_lookup()
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/db/models/lookups.py", line 143, in get_prep_lookup
    return self.lhs.output_field.get_prep_lookup(self.lookup_name, self.rhs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/db/models/fields/__init__.py", line 727, in get_prep_lookup
    return self.get_prep_value(value)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/db/models/fields/__init__.py", line 985, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'systems'

**Comment by phillxnet** [comment]
@aherbach88 Thanks for reporting this, pretty sure it's down to a recent change in the testing channel updates of share api (3.9.1-9) and we are collecting the loose ends currently.

I have reproduced this and am currently having a quick look at developing a fix.

**Comment by phillxnet** [comment]
The UI experience re this issue is the following:

![smb-export-after-share-api-change](https://user-images.githubusercontent.com/2521585/30441812-65e25ab8-9972-11e7-9805-9e5c65da4181.png)

directly after attempting to establish an smb export. And appears to be down to a failure to validate the share due to using the old name based rather than db id based api: hence the "invalid literal fro int()" ie front end suspected as still passing name when id is needed.

**Comment by aherbach88** [comment]
I updated to 3.9.1-11 and am still getting errors.  The log now shows:
[15/Sep/2017 10:45:17] ERROR [storageadmin.middleware:32] Exception occured while processing a request. Path: /api/users method: GET
[15/Sep/2017 10:45:17] ERROR [storageadmin.middleware:33] u"Got KeyError when attempting to get a value for field `groupname` on serializer `SUserSerializer`.\nThe serializer field might be named incorrectly and not match any attribute or key on the `User` instance.\nOriginal exception text was: 'getgrgid(): gid not found: 105'."
Traceback (most recent call last):
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/views.py", line 452, in dispatch
    response = self.handle_exception(exc)
  File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/views.py", line 449, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/generics.py", line 241, in get
    return self.list(request, *args, **kwargs)
  File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/mixins.py", line 44, in list
    return self.get_paginated_response(serializer.data)
  File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/serializers.py", line 618, in data
    ret = super(ListSerializer, self).data
  File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/serializers.py", line 213, in data
    self._data = self.to_representation(self.instance)
  File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/serializers.py", line 568, in to_representation
    self.child.to_representation(item) for item in iterable
  File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/serializers.py", line 426, in to_representation
    attribute = field.get_attribute(instance)
  File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/fields.py", line 316, in get_attribute
    raise type(exc)(msg)
KeyError: u"Got KeyError when attempting to get a value for field `groupname` on serializer `SUserSerializer`.\nThe serializer field might be named incorrectly and not match any attribute or key on the `User` instance.\nOriginal exception text was: 'getgrgid(): gid not found: 105'."

**Comment by phillxnet** [comment]
@aherbach88 Thanks for the feedback, however I did not experience this log entry post pr. You could try refreshing your brower and or rebooting your Rockstor instances as it may just be that you have some prior version code in play still as the error looks quite different. I.e it now relates to users / groups not shares and there has been no user / group api change. Could you clarify the circumstances under which you experience you newly reported error message in this issue, ie this issue relates to samba export / share creation. I did, prior to 'fix' development, re-produce your issue as originally expressed and there after was able to successfully create smb shares / exports.

**Comment by aherbach88** [comment]
@phillxnet The error when accessing the add a new samba export or edit an existing one.  It will sit trying to load the for a few seconds then displays "Unknown internal error doing a GET to /api/users?page=1&format=json&page_size=5000&count= ".

Much like the previous error, that error will persist on the web gui until you refresh the page.  I have restarted the server a couple of times, refreshed the broswer and even tried a different one.

My setup right now is pretty basic, I have AD, NIS, NTP, and SNMP enabled (I have tested disabling AD with no difference in the error), a single RAID6 pool I've created, a single share I've created, and a single NFS export.  Is there any other information I can give to help recreate this?  I'm just going to Storage > Samba > Add Samba Export.

**Comment by phillxnet** [comment]
@aherbach88 OK, thanks. So it looks like your particular instance of this issue was further complicated by the AD stuff as I've demonstrated a fix by way of the associated pr for the initial report and error log.  However that contained no initial AD config and I'm assuming this additional initial element to your existing causes is what's still outstanding as a 'trigger' in your case.. Unfortunately we need a reproducer and I don't have one here.  The AD element is all I can think of re the cause as from memory I don't remember any requirement otherwise to access the user api which is what your GET error is indicating.

So that we don't loose track of this can you please open a new issue with the new log entry and the new /api/users UI message. Please link back to this now closed issue for context and hopefully in time others can chip in with their experience of this and if a reproduce can be found then we can look into and validate a fix as the pull request for this issue as originally reported, and now released, obviously doesn't cover what you have there but it did cover the reproducer I had here. Hence the request to open a new issue so we can focus on your outstanding symptoms. Also others who are similarly affected can hopefully provide the steps to reproduce what you have. As I say it looks to be user / group related now and your mention of the AD stuff tallies with that so hopefully that corner can be addressed via the new issue.

Thanks and given most of the info is already here your can probably cut and paste, along with links and include the initial AD element in the title as I think that is the crinkle here. Don't think I'm going to be able to look at this for a bit myself but the new issue should be able to help with focus on the existing symptoms and if others also have those then we should be able to get to the bottom of it. As is I am just not seeing any:

    "Exception occured while processing a request. Path: /api/users method: GET"

happening here (looks like we have a typo in the exception message though).

Thanks for helping to split this out and hopefully we can get this sorted soon. My reproducer of your original issue was on a clean build from the source as released at that time and so would have affected all install.

@MFlyer  Hopefully we can continue this discussion in the new spin-off issue but does anything in the now user / group related stuff ring a bell with you re AD and samba as that is now my suspicion on @aherbach88 current symptoms (post 3.9.1-11 obvious fix re samba share creation pr).
