### ISSUE TITLE
Samba with AD connector errors out when creating/editing an export

### ISSUE THREAD

**Issue by aherbach88** [rockstor/rockstor-core#1817]
On 3.9.1-11 I am getting the following error

[15/Sep/2017 10:45:17] ERROR [storageadmin.middleware:32] Exception occured while processing a request. Path: /api/users method: GET
[15/Sep/2017 10:45:17] ERROR [storageadmin.middleware:33] u"Got KeyError when attempting to get a value for field groupname on serializer SUserSerializer.\nThe serializer field might be named incorrectly and not match any attribute or key on the User instance.\nOriginal exception text was: 'getgrgid(): gid not found: 105'."
Traceback (most recent call last):
File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/views/decorators/csrf.py", line 58, in wrapped_view
return view_func(*args, **kwargs)
File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/views/generic/base.py", line 71, in view
return self.dispatch(request, *args, **kwargs)
File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/views.py", line 452, in dispatch
response = self.handle_exception(exc)
File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/views.py", line 449, in dispatch
response = handler(request, *args, **kwargs)
File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/generics.py", line 241, in get
return self.list(request, *args, **kwargs)
File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/mixins.py", line 44, in list
return self.get_paginated_response(serializer.data)
File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/serializers.py", line 618, in data
ret = super(ListSerializer, self).data
File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/serializers.py", line 213, in data
self._data = self.to_representation(self.instance)
File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/serializers.py", line 568, in to_representation
self.child.to_representation(item) for item in iterable
File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/serializers.py", line 426, in to_representation
attribute = field.get_attribute(instance)
File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/fields.py", line 316, in get_attribute
raise type(exc)(msg)
KeyError: u"Got KeyError when attempting to get a value for field groupname on serializer SUserSerializer.\nThe serializer field might be named incorrectly and not match any attribute or key on the User instance.\nOriginal exception text was: 'getgrgid(): gid not found: 105'."

This is a continuation of issues from [1913](https://github.com/rockstor/rockstor-core/issues/1813)

As noted there I have AD, NIS, NTP, SNMP enabled (in addition to the defaults).
Originally @phillxnet thought this might be related to the AD implementation, but it appears that it's actually NIS causing this.  Once NIS is disabled, I no longer receive the errors.

**Comment by phillxnet** [comment]
@aherbach88 Thanks for opening this 'off shoot' issue. We have just had another report akin to this one which you might find interesting/useful. Please see:
https://forum.rockstor.com/t/samba-service-broken-after-update-11/3780
as it may be the same issue you have just experienced. Please report back here or there as you see fit as it would appear a fix was found, if not an actual 'pinned down' cause.

Thanks.

**Comment by aherbach88** [comment]
So, I was able to reproduce this on a clean install.  It is definitely the NIS service, however this probably has to do more with my internal setup for NIS than rockstor as I'm running a heavily customized version of NIS+ on Solaris 9 that I have el4/5/6/7 clients connect to.

**Comment by aherbach88** [comment]
Ignore my previous comment on this, the actual error is from winbind.

Currently it looks like this:
KeyError: u"Got KeyError when attempting to get a value for field `groupname` on serializer `SUserSerializer`.\nThe serializer field might be named incorrectly and not match any attribute or key on the `User` instance.\nOriginal exception text was: 'getgrgid(): gid not found: 105'."

The 105 corresponds to my primary Group ID as I have it set in the Unix Extensions for AD.  It doesn't seem to matter what group is set there, it will always error out.

**Comment by aherbach88** [comment]
A couple of updates I found,

When I set the following settings for Winbind this issue no longer seems to occur (no errors appear in the long either).

    winbind use default domain = true
    winbind offline logon = false
    winbind enum users = no
    winbind enum groups = no
