### ISSUE TITLE
Can't install Rockons

### ISSUE THREAD

**Issue by MBadberg** [rockstor/rockstor-core#1831]
ztask.log
2017-09-23 15:46:30,144 - ztaskd - ERROR - Error setting up function. Details:
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
#############################################
supervisor.ztask stderr.log
ERROR:storageadmin.views.rockon_helpers:'NoneType' object has no attribute 'name'
Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/storageadmin/views/rockon_helpers.py", line 121, in install
    generic_install)(rockon)
  File "/opt/rockstor/src/rockstor/storageadmin/views/rockon_helpers.py", line 207, in generic_install
    cmd.extend(vol_ops(c))
  File "/opt/rockstor/src/rockstor/storageadmin/views/rockon_helpers.py", line 179, in vol_ops
    share_mnt = ('%s%s' % (settings.MNT_PT, v.share.name))
AttributeError: 'NoneType' object has no attribute 'name'
INFO:ztaskd:Called storageadmin.views.rockon_helpers.install successfully
WARNING:py.warnings:/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Task.created received a naive datetime (2017-09-23 14:07:46.179843) while time zone support is active.
  RuntimeWarning)

INFO:ztaskd:Calling storageadmin.views.rockon_helpers.install
ERROR:storageadmin.views.rockon_helpers:'NoneType' object has no attribute 'name'
Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/storageadmin/views/rockon_helpers.py", line 121, in install
    generic_install)(rockon)
  File "/opt/rockstor/src/rockstor/storageadmin/views/rockon_helpers.py", line 207, in generic_install
    cmd.extend(vol_ops(c))
  File "/opt/rockstor/src/rockstor/storageadmin/views/rockon_helpers.py", line 179, in vol_ops
    share_mnt = ('%s%s' % (settings.MNT_PT, v.share.name))
AttributeError: 'NoneType' object has no attribute 'name'
INFO:ztaskd:Called storageadmin.views.rockon_helpers.install successfully

**Comment by Hooverdan96** [comment]
@FroggyFlox we can probably close this issue, as this was six years ago and many a changes have been implemented for the Rockon framework.
