### ISSUE TITLE
Schedules broken after update to 3.9.2-0

### ISSUE THREAD

**Issue by ScarabMonkey** [rockstor/rockstor-core#1851]
Since updating to 3.9.2-0 all of our existing scheduled snapshots are failing.
It seems to be that the field name has changed from 'share' to 'share_name' and the existing data hasn't been migrated:

> Traceback (most recent call last):
>  File "/opt/rockstor/bin/st-snapshot", line 45, in <module>
>    sys.exit(scripts.scheduled_tasks.snapshot.main())
>  File "/opt/rockstor/src/rockstor/scripts/scheduled_tasks/snapshot.py", line 94, in main
>    validate_snap_meta(meta)
>  File "/opt/rockstor/src/rockstor/scripts/scheduled_tasks/snapshot.py", line 38, in validate_snap_meta
>    raise Exception('share_name missing from meta. {}'.format(meta))
> Exception: share_name missing from meta. {u'writable': False, u'visible': True, u'prefix': u'snap', u'share': u'ATPSynthase', u'max_count': u'24'}

In our setup we have many Shares and had to manually create 2 snapshot schedules for each of these (in fact I got bored after making 10) - the schedule clone feature would be really great to ameliorate this!

**Comment by ScarabMonkey** [comment]
On closer inspection, this also appears to affect Scrub schedules - notice that it says 'undefined'

> ATP_snap_hourly | snapshot (undefined) | Every 1st minute past every hour | from 07:00 to 19:02 -   on every day |   | a day ago |  
> -- | -- | -- | -- | -- | -- | --
> ATPSynthase_snap_hourly | snapshot (ATPSynthase) | Every hour, on the hour | from 07:00 to 19:01 -   on every day |   | 30 minutes ago |  
> GroupsScrubMonthly | scrub (undefined) | 03:42 on the 8th of every month | Run always |   | error |  

(the 1st entry is an original snapshot schedule - the 2nd is the replacement that I manually re-created yesterday  - the 3rd is a scrub of the same pool)
Traceback from Scrub job follows:

> Traceback (most recent call last):
>  File "/usr/lib64/python2.7/logging/handlers.py", line 76, in emit
>    if self.shouldRollover(record):
>  File "/usr/lib64/python2.7/logging/handlers.py", line 154, in shouldRollover
>    msg = "%s\n" % self.format(record)
>  File "/usr/lib64/python2.7/logging/__init__.py", line 724, in format
>    return fmt.format(record)
>  File "/usr/lib64/python2.7/logging/__init__.py", line 464, in format
>    record.message = record.getMessage()
>  File "/usr/lib64/python2.7/logging/__init__.py", line 324, in getMessage
>    msg = str(self.msg)
> TypeError: __str__ returned non-string (type list)
> Logged from file pool_scrub.py, line 82
> Traceback (most recent call last):
>  File "/usr/lib64/python2.7/logging/handlers.py", line 76, in emit
>    if self.shouldRollover(record):
>  File "/usr/lib64/python2.7/logging/handlers.py", line 154, in shouldRollover
>    msg = "%s\n" % self.format(record)
>  File "/usr/lib64/python2.7/logging/__init__.py", line 724, in format
>    return fmt.format(record)
>  File "/usr/lib64/python2.7/logging/__init__.py", line 464, in format
>    record.message = record.getMessage()
>  File "/usr/lib64/python2.7/logging/__init__.py", line 324, in getMessage
>    msg = str(self.msg)
> TypeError: __str__ returned non-string (type list)
> Logged from file pool_scrub.py, line 43

**Comment by ScarabMonkey** [comment]
For clarity: I'm using the 'stable' channel and this update was installed automatically, unattended, without any warning.

**Comment by phillxnet** [comment]
@ScarabMonkey I don't believe this is due to a db migration failure but more to our newer code requiring an additional parameter (share_name) within the definition of the scheduled task. Hence me putting in the exception message to identify this occurrence: 'meta' is our info on the scheduled task and it doesn't contain the now required share_name. This was due to our moving share to reference the id not the name.

Apologies for this side effect but we should be just about done with these rather far reaching, but necessary changes now. I am about to also reply in your associated forum post:
https://forum.rockstor.com/t/issue-schedules-broken-after-update-to-3-9-2-0/3999

@ScarabMonkey and @schakrava 
This issue is as a result of the share api change during the 3.9.2 dev cycle and was opened as issue #1809 
ie: "snapshot scheduled task regression re 3.9.1-9 API change #1809"
So I suggest this is a duplicate of that issue.

The fix was released in pr #1812 

"fix snapshot scheduled task regression re share api change #1809 #1812"

With the caveat expressed in issue #1809 as follows:

_"N.B. as with the pool api scheduled scrub task fix, it will be necessary for users to delete and re-create all their existing scheduled snapshot tasks (post this pr) in order that their prior function (pre share api change) be restored."_

I believe this advise was due to be included in the 3.9.2 stable release announcement that has been delayed by unforeseen circumstances.

@ScarabMonkey can you confirm that when you re-create a scheduled snapshot task that it then executes as expected? As above scheduled scrub tasks will also require recreating.

**Comment by ScarabMonkey** [comment]
Thanks @phillxnet
Though I'm unsure as to why the migration script can't do this automatically?

I can confirm that a newly created schedule is functioning correctly.

**Comment by phillxnet** [comment]
@ScarabMonkey Thanks for the confirmation of pr #1812.

Would you care to close this issue as a duplicate of issue #1809 ?

As for why this was not dealt with auto-magically I'm afraid this was down to attempting to keep the code as clean and maintainable as possible. An early decision in the project had simply come back to haunt us but post 3.9.2 it has now been put to rest. The pain point being the necessary re-creation of scheduled scrub and snapshot tasks. Then we are free of it (hopefully) and can move on without the baggage of additional migration code. Apologies again as I was the author of both fixes and knew this to be an artefact and failed to sufficiently publicise it until the following forum post:
https://forum.rockstor.com/t/cron-root-rockstor-opt-rockstor-bin-st-snapshot-1-what-does-this-mean/3823/2
which sighted issue #1809's text detailing this side effect:

Once this requirement is disseminated to the stable subscribers via the (currently delayed) mailshot we should be sorted.

Thanks again for the additional confirmation.
