### ISSUE TITLE
Updating 3.8 to 3.9.1-16 failed on django migration

### ISSUE THREAD

**Issue by domaslasauskas** [rockstor/rockstor-core#1859]
I've enabled automatic updates for the first time and used Testing Updates channel. I don't remember specific version before update but this is what I've got from yum history:

```
    Updated     rockstor-3.8-13.x86_64                                   @anaconda/3
    Update               3.9.1-16.x86_64                                 @Rockstor-Testing
    Updated     rockstor-release-3-8.10.el7.x86_64                       @anaconda/3
    Update                       3-8.16.el7.x86_64                       @rockstor
```

I've tried downgrading rockstor:

```
yum downgrade rockstor
systemctl restart rockstor-pre rockstor rockstor-bootstrap
```

However, the issue still persisted:

```
[root@rockstor ~]# systemctl status rockstor-pre.service -l
● rockstor-pre.service - Tasks required prior to starting Rockstor
   Loaded: loaded (/etc/systemd/system/rockstor-pre.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Tue 2017-11-28 23:43:17 GMT; 19min ago
 Main PID: 3410 (code=exited, status=1/FAILURE)

Nov 28 23:43:17 rockstor initrock[3410]: File "/opt/rockstor/src/rockstor/scripts/initrock.py", line 423, in main
Nov 28 23:43:17 rockstor initrock[3410]: run_command(migration_cmd + ['storageadmin'])
Nov 28 23:43:17 rockstor initrock[3410]: File "/opt/rockstor/src/rockstor/system/osi.py", line 121, in run_command
Nov 28 23:43:17 rockstor initrock[3410]: raise CommandException(cmd, out, err, rc)
Nov 28 23:43:17 rockstor initrock[3410]: system.exceptions.CommandException: Error running a command. cmd = /opt/rockstor/bin/django migrate --noinput storageadmin. rc = 1. stdout = ['Operations to perform:', '  Apply all migrations: storageadmin', 'Running migrations:', '  No migrations to apply.', '']. stderr = ['Traceback (most recent call last):', '  File "/opt/rockstor/bin/django", line 44, in <module>', "    sys.exit(djangorecipe.manage.main('rockstor.settings'))", '  File "/opt/rockstor/eggs/djangorecipe-1.9-py2.7.egg/djangorecipe/manage.py", line 9, in main', '    management.execute_from_command_line(sys.argv)', '  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/core/management/__init__.py", line 354, in execute_from_command_line', '    utility.execute()', '  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/core/management/__init__.py", line 346, in execute', '    self.fetch_command(subcommand).run_from_argv(self.argv)', '  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/core/management/base.py", line 394, in run_from_argv', '    self.execute(*args, **cmd_options)', '  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/core/management/base.py", line 445, in execute', '    output = self.handle(*args, **options)', '  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/core/management/commands/migrate.py", line 226, in handle', '    emit_post_migrate_signal(created_models, self.verbosity, self.interactive, connection.alias)', '  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/core/management/sql.py", line 280, in emit_post_migrate_signal', '    using=db)', '  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/dispatch/dispatcher.py", line 189, in send', '    response = receiver(signal=self, sender=sender, **named)', '  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/contrib/auth/management/__init__.py", line 82, in create_permissions', '    ctype = ContentType.objects.db_manager(using).get_for_model(klass)', '  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/contrib/contenttypes/models.py
Nov 28 23:43:17 rockstor initrock[3410]: ", line 80, in get_for_model', '    "Error creating new content types. Please make sure contenttypes "', 'RuntimeError: Error creating new content types. Please make sure contenttypes is migrated before trying to migrate apps individually.', '']
Nov 28 23:43:17 rockstor systemd[1]: rockstor-pre.service: main process exited, code=exited, status=1/FAILURE
Nov 28 23:43:17 rockstor systemd[1]: Failed to start Tasks required prior to starting Rockstor.
Nov 28 23:43:17 rockstor systemd[1]: Unit rockstor-pre.service entered failed state.
Nov 28 23:43:17 rockstor systemd[1]: rockstor-pre.service failed.
```

**Comment by phillxnet** [comment]
@domaslasauskas This is a known limitation as way back at 3.8.15 we made major changes in the db migration mechanism that requires a 'stop off' at 3.8.15. Please see the following forum post as it looks like from your yum log entry you attempted to go from 3.8-13 (not sure of that one) or from 3.8.10: both of which are pre-3.8.14.

"Upgrading to 3.8.16 from 3.8-14 or before? Read this"
https://forum.rockstor.com/t/upgrading-to-3-8-16-from-3-8-14-or-before-read-this/2512

So not a bug as such but a known limitation. Let us know how that post works our for you. If you still have problems then I would advise you open a forum thread as this is then more of a support issue.

Hope that helps.

**Comment by domaslasauskas** [comment]
While I still think that it should be considered a bug when upgrade from one version to another fails in such a way, at this point I don't have any constructive suggestions on how it could be fixed.

I could not solve my issue because I got the same `No package rockstor-3.8.15 available` issue as **wgs** from the forum when trying to update to 3.8.15. And then by upgrading to other 3.8.16 testing versions and then downgrading again couple times I managed to get into another pickle getting migration issues yet on another package which I will investigate more over the weekend.

If you feel that broken update is not a bug, please feel free to close this issue. I'll try setting up rockstor dev VM and experiment more with updates and will report back here if I find a more permanent fix for this.

**Comment by Hooverdan96** [comment]
@phillxnet, since this is a CentOS relevant issue I think this can be closed, since we've moved to OpenSUSE.
