### ISSUE TITLE
shares unmounted after reboot - 3.9.2-3

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-core#1867]
Thanks to forum members upapi_rockstor, Horatio, and Hooverdan for initially reporting this issue. As per the 3.9.2-3 update it can be the case that some or all shares can fail to mount. This looks to be related to the Bootstrap process as System - Services indicates that OFF for Bootstrap and:
```
systemctl status rockstor-bootstrap
```
similarly indicates a failure due to MAX attempts(15) reached.

the 3.9.2-3 update appears to do no more than:
"move to docker-ce / dockerd. Fixes #1860" #1865

Based on a local reproduction of this issue:
On reboot mounts are still failed due to the following quota issue on the rock-ons-root:

```
[08/Dec/2017 15:58:23] ERROR [storageadmin.middleware:32] Exception occured while processing a request. Path: /api/commands/refresh-share-st
ate method: POST
[08/Dec/2017 15:58:23] ERROR [storageadmin.middleware:33] Error running a command. cmd = /sbin/btrfs qgroup show /mnt2/rock-pool/rock-ons-ro
ot. rc = 1. stdout = ['']. stderr = ["ERROR: can't list qgroups: quotas not enabled", '']
Traceback (most recent call last):
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/views.py", line 452, in dispatch
    response = self.handle_exception(exc)
  File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/views.py", line 449, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/opt/rockstor/src/rockstor/storageadmin/views/command.py", line 318, in post
    import_shares(p, request)
  File "/opt/rockstor/src/rockstor/storageadmin/views/share_helpers.py", line 94, in import_shares
    volume_usage(pool, share.qgroup, share.pqgroup)
  File "/opt/rockstor/src/rockstor/fs/btrfs.py", line 835, in volume_usage
    out, err, rc = run_command(cmd, log=True)
  File "/opt/rockstor/src/rockstor/system/osi.py", line 121, in run_command
    raise CommandException(cmd, out, err, rc)
CommandException: Error running a command. cmd = /sbin/btrfs qgroup show /mnt2/rock-pool/rock-ons-root. rc = 1. stdout = ['']. stderr = ["ERROR: can't list qgroups: quotas not enabled", '']
[08/Dec/2017 15:58:24] ERROR [system.osi:119] non-zero code(1) returned by command: ['/sbin/btrfs', 'qgroup', 'show', '/mnt2/rock-pool/rock-ons-root/btrfs/subvolumes/f352dfd367879d5f612bde14ec3da50250bb13b417a47312e94440156f8dc984']. output: [''] error: ["ERROR: can't list qgroups: quotas not enabled", '']
```

Quota issues were also indicated as related by forum user upapi_rockstor and confirmed by Hooverdan in the second of the following forum threads:

Please update the following forum threads with this issues resolution.
https://forum.rockstor.com/t/after-update-to-3-9-2-3-yum-updates-plex-shares-are-not-working/4141
https://forum.rockstor.com/t/rockstor-3-9-2-3-shares-unmounted-after-reboot/4144

**Comment by phillxnet** [comment]
I am currently looking into this issue.

**Comment by phillxnet** [comment]
trigger points:
```
File "/opt/rockstor/src/rockstor/storageadmin/views/share_helpers.py", line 94, in import_shares
    volume_usage(pool, share.qgroup, share.pqgroup)
  File "/opt/rockstor/src/rockstor/fs/btrfs.py", line 835, in volume_usage
    out, err, rc = run_command(cmd, log=True)
  File "/opt/rockstor/src/rockstor/system/osi.py", line 121, in run_command
    raise CommandException(cmd, out, err, rc)
```
and 
```
File "/opt/rockstor/src/rockstor/storageadmin/views/share_helpers.py", line 168, in import_snapshots
    rusage, eusage = volume_usage(share.pool, snaps_d[s][0])
  File "/opt/rockstor/src/rockstor/fs/btrfs.py", line 835, in volume_usage
    out, err, rc = run_command(cmd, log=True)
  File "/opt/rockstor/src/rockstor/system/osi.py", line 121, in run_command
    raise CommandException(cmd, out, err, rc)
```
both call:

/opt/rockstor/src/rockstor/fs/btrfs.py line 835

which fails with given command exception (quotas not enabled) breaking mounts.

**Comment by phillxnet** [comment]
Perusing the angle that we should robustly deal with quotas not enabled.

**Comment by phillxnet** [comment]
Linking as a completed sub goal towards #1592 
"[New feature] Add option to disable BTRFS quota/qgroups"
