### ISSUE TITLE
Rock-on broken after update, missing subvolume

### ISSUE THREAD

**Issue by ciliehub** [rockstor/rockstor-core#1888]
Problem: Rock-on is broken after Rockstor update and can't reinstall it.

History: I installed and configured the Duplicati2-canary plugin and it performed well until Rockstor update 3.9.2.-12. The Rock-on disappeared from the 'Installed' list. After trying to reinstall nothing seems to be installed, but the Rock-on displays a message:

> Failed to install in the previous attempt. Here's how you can proceed.
Check logs in /opt/rockstor/var/log for clues.
Install again.
If the problem persists, post on the Forum or email support@rockstor.com

So, here's my rockstor log output:

```shell
[04/Feb/2018 10:37:52] ERROR [system.osi:119] non-zero code(1) returned by command: ['/sbin/btrfs', 'qgroup', 'show', '/mnt2/rockstor_rockstor/home']. output: [''] error: ["ERROR: can't list qgroups: quotas not enabled", '']

[04/Feb/2018 10:37:52] ERROR [system.osi:119] non-zero code(1) returned by command: ['/sbin/btrfs', 'qgroup', 'show', '/mnt2/rockstor_rockstor/root']. output: [''] error: ["ERROR: can't list qgroups: quotas not enabled", '']

[04/Feb/2018 10:37:52] ERROR [system.osi:119] non-zero code(1) returned by command: ['/sbin/btrfs', 'qgroup', 'show', '/mnt2/rockstor_rockstor/rockonspace']. output: [''] error: ["ERROR: can't list qgroups: quotas not enabled", '']

[04/Feb/2018 10:44:21] ERROR [storageadmin.views.rockon_helpers:124] Error running a command. cmd = /usr/bin/docker run -d --restart=unless-stopped --name duplicati2-canary -v /mnt2/duplicati-config:/root/.config/Duplicati/ -v /etc/localtime:/etc/localtime:ro -p 8200:8200/tcp -e MONO_EXTERNAL_ENCODINGS=UTF-8 -e DUPLICATI_PASS=secret intersoftlab/duplicati. rc = 127. stdout = ['']. stderr = ['/usr/bin/docker: Error response from daemon: stat /mnt2/home/btrfs/subvolumes/d731d6bbc945a47bf7dbadb2bdf0ec0f861022ce1e13ef5b6baf43195869c494: no such file or directory.', "See '/usr/bin/docker run --help'.", '']
Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/storageadmin/views/rockon_helpers.py", line 121, in install
    generic_install)(rockon)
  File "/opt/rockstor/src/rockstor/storageadmin/views/rockon_helpers.py", line 221, in generic_install
    run_command(cmd)
  File "/opt/rockstor/src/rockstor/system/osi.py", line 121, in run_command
    raise CommandException(cmd, out, err, rc)
CommandException: Error running a command. cmd = /usr/bin/docker run -d --restart=unless-stopped --name duplicati2-canary -v /mnt2/duplicati-config:/root/.config/Duplicati/ -v /etc/localtime:/etc/localtime:ro -p 8200:8200/tcp -e MONO_EXTERNAL_ENCODINGS=UTF-8 -e DUPLICATI_PASS=secret intersoftlab/duplicati. rc = 127. stdout = ['']. stderr = ['/usr/bin/docker: Error response from daemon: stat /mnt2/home/btrfs/subvolumes/d731d6bbc945a47bf7dbadb2bdf0ec0f861022ce1e13ef5b6baf43195869c494: no such file or directory.', "See '/usr/bin/docker run --help'.", '']
```

It looks to me that the rock-on itself is not the problem, but 'something' with btrfs subvolumes. But what? I haven't done anything with that. Or at all, my NAS is just an intended Rockstor installation with a backup plugin. I chose Rockstor because of the Rock-on/docker/duplicati combination.

Anyway: any help to solve this will be appreciated!

**Comment by phillxnet** [comment]
@ciliehub Thanks for the report. This looks very much like a quota issue ie:

error: ["ERROR: can't list qgroups: quotas not enabled", '']

which I suspect as you did is the " 'something' with btrfs subvolumes."

And as it was associated with an update I suspect it was down to a rather gnarly and whole unexpected side effect of moving to  docker-ce (pr #1865) as the new docker-ce had the very strange side effect of disabling quotas. This initially lead to shares / subvols not being mounted as Rockstor previously completely depended on quotas and would fail to mount shares if quotas were disabled. This was fairly quickly addressed by way of:
"shares unmounted after reboot - 3.9.2-3 #1867" pr #1868 
"rock-ons-root host pool quota disabled by docker-ce #1872" pr #1873
and
"improve quotas not enabled behaviour #1869" pr #1874
with this last one also adding UI indicators of quota enabled/disabled status.

However all of these are prior to 3.9.2-12.

It may be that we are still suffering from an issue that only shows up if the rock-ons-root:
http://rockstor.com/docs/docker-based-rock-ons/overview.html#rockons-root
is on the system pool as your log indicates.

Could you first try a reboot to see if things settle as we have had numerous Rockon/docker issues directly after update, and in this case the update was more significant due to the move from docker to docker-ce. They have often taken the form of docker refusing to start after an update until a reboot is performed. Not ideal but it's what we have found. Also it will give the above mentioned changes a chance to kick in if they haven't already.

Let us know what the state of things is after a reboot re quotas (UI indicates this now) and mount status (also indicated in UI now). And the docker enabled state of course.

Just trying to establish if we can pin down a remaining bug in this area that your config is surfacing.

On a side note it looks like your youtrack rockon pull request has now been merged; nice.

**Comment by ciliehub** [comment]
Hello Phil, thank you so much for the long answer!

I will read it complete right after writing this. But what I meant with 'something with btrfs subvolumes' is the last message that tries to run the docker command:

CommandException: Error running a command. cmd = /usr/bin/docker run -d --restart=unless-stopped --name duplicati2-canary -v /mnt2/duplicati-config:/root/.config/Duplicati/ -v /etc/localtime:/etc/localtime:ro -p 8200:8200/tcp -e MONO_EXTERNAL_ENCODINGS=UTF-8 -e DUPLICATI_PASS=secret intersoftlab/duplicati. rc = 127. stdout = ['']. stderr = ['/usr/bin/docker: **Error response from daemon: stat /mnt2/home/btrfs/subvolumes/d731d6bbc945a47bf7dbadb2bdf0ec0f861022ce1e13ef5b6baf43195869c494: no such file or directory.**', "See '/usr/bin/docker run --help'.", '']

I will now read your complete answer!

**Comment by ciliehub** [comment]
A reboot adds this to the log:

```shell
[04/Feb/2018 15:23:51] ERROR [system.osi:119] non-zero code(1) returned by command: ['/sbin/btrfs', 'qgroup', 'show', '/mnt2/rockstor_rockstor/home']. output: [''] error: ["ERROR: can't list qgroups: quotas not enabled", '']
[04/Feb/2018 15:23:52] ERROR [system.osi:119] non-zero code(1) returned by command: ['/sbin/btrfs', 'qgroup', 'show', '/mnt2/rockstor_rockstor/root']. output: [''] error: ["ERROR: can't list qgroups: quotas not enabled", '']
[04/Feb/2018 15:23:52] ERROR [system.osi:119] non-zero code(1) returned by command: ['/sbin/btrfs', 'qgroup', 'show', '/mnt2/rockstor_rockstor/rockonspace']. output: [''] error: ["ERROR: can't list qgroups: quotas not enabled", '']
```
... so the quota issue does not seem to be resolved by the reboot. I understand that the Rock-on problem maybe resolved by pointing the the rockon root (rockonspace in my case) to the data pool?

If so, what do we do with the other errors concerning _home_ & _root_?

Again, your help is much appreciated!

**Comment by ciliehub** [comment]
Great, 1. _moving_ the rockonspace to the data pool and 2. pointing the rockon service to the new share resolves the issue. I have successfully installed Duplicati2 again.

But still i'm very curious about the last question: 
what do we do with the other errors concerning home & root? Ignore or take other steps?

**Comment by phillxnet** [comment]
@ciliehub Thanks for the feedback / testing and glad you got up and running again, although only via the  rock-ons-root recreate on non system disk work around.

As per the errors, they are as intended: Rockstor still considers 'quota disabled' as an error state for a pool, the referenced issues simply made it less critical in that the pool's shares (btrfs subvols) are still mounted but we nevertheless log this error state still.

Try now manually enabling quotas on your system pool via:
```
btrfs quota enable /mnt2/rockstor_rockstor
```
"rockstor_rockstor" is the system drives (btrfs pool/vol) name where "root" and "home" are it's subvols.

We are currently 'lazy' with enabling quotas and with quota rescan as we until very recently assumed they were always on.

**Comment by ciliehub** [comment]
OK, all seems to be fine, my backups are (re)syncing. Thank you so much for the quick solution & insights. Rockstor rocks!
