### ISSUE TITLE
Latest initscripts conflicts with rockstor-release-3-8.16.el7.x86_64

### ISSUE THREAD

**Issue by zipsonic** [rockstor/rockstor-core#1921]
Received this email, over and over last night

/etc/cron.hourly/0yum-hourly.cron:

Traceback (most recent call last):
  File "/usr/sbin/yum-cron", line 729, in <module>
    main()
  File "/usr/sbin/yum-cron", line 726, in main
    base.updatesCheck()
  File "/usr/sbin/yum-cron", line 618, in updatesCheck
    self.populateUpdateMetadata()
  File "/usr/sbin/yum-cron", line 422, in populateUpdateMetadata
    self.pkgSack # honor skip_if_unavailable
  File "/usr/lib/python2.7/site-packages/yum/__init__.py", line 1074, in <lambda>
    pkgSack = property(fget=lambda self: self._getSacks(),
  File "/usr/lib/python2.7/site-packages/yum/__init__.py", line 779, in _getSacks
    if not self.repos.getPackageSack():
  File "/usr/lib/python2.7/site-packages/yum/packageSack.py", line 373, in __len__
    ret += len(sack)
  File "/usr/lib/python2.7/site-packages/yum/sqlitesack.py", line 519, in __len__
    pkg_num += self._sql_MD_pkg_num('primary', repo)
  File "/usr/lib/python2.7/site-packages/yum/sqlitesack.py", line 487, in _sql_MD_pkg_num
    return self._sql_MD('primary', repo, sql).fetchone()[0]
  File "/usr/lib/python2.7/site-packages/yum/sqlitesack.py", line 55, in newFunc
    raise Errors.RepoError, str(e)
yum.Errors.RepoError: file is encrypted or is not a database

yum update yields:

--> Processing Conflict: initscripts-9.49.41-1.el7.x86_64 conflicts redhat-release < 7.5-0.11
--> Finished Dependency Resolution
Error: Package: nut-2.7.2-3.el7.x86_64 (@anaconda/3)
           Requires: libfreeipmi.so.13()(64bit)
           Removing: freeipmi-1.2.9-8.el7.x86_64 (@anaconda/3)
               libfreeipmi.so.13()(64bit)
           Updated By: freeipmi-1.5.7-2.el7.x86_64 (base)
              ~libfreeipmi.so.17()(64bit)
Error: initscripts conflicts with rockstor-release-3-8.16.el7.x86_64
Error: Package: nut-2.7.2-3.el7.x86_64 (@anaconda/3)
           Requires: libipmimonitoring.so.5()(64bit)
           Removing: freeipmi-1.2.9-8.el7.x86_64 (@anaconda/3)
               libipmimonitoring.so.5()(64bit)
           Updated By: freeipmi-1.5.7-2.el7.x86_64 (base)
              ~libipmimonitoring.so.6()(64bit)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

Running Latest Stable

**Comment by FroggyFlox** [comment]
I have the same issue (although I didn't have the opportunity to test a `yum update` yet).
see the following forum post:
https://forum.rockstor.com/t/cron-hourly-error-system-update-page-on-webui-gives-houston-weve-a-problem/4770/2?u=flox

**Comment by zipsonic** [comment]
Fixed with rockstor-release 3-9.23
