### ISSUE TITLE
Cant remove share due to stale NFS mount options

### ISSUE THREAD

**Issue by t3kka** [rockstor/rockstor-core#1960]
I am attempting to remove a share via the UI but it is giving me the following error:

```
Share (Usenet) cannot be deleted as it is exported via NFS. Delete NFS exports and try again.

  Traceback (most recent call last):
  File "/opt/rockstor/eggs/gunicorn-19.7.1-py2.7.egg/gunicorn/workers/sync.py", line 68, in run_for_one
    self.accept(listener)
  File "/opt/rockstor/eggs/gunicorn-19.7.1-py2.7.egg/gunicorn/workers/sync.py", line 27, in accept
    client, addr = listener.accept()
  File "/usr/lib64/python2.7/socket.py", line 202, in accept
    sock, addr = self._sock.accept()
error: [Errno 11] Resource temporarily unavailable

```

Reviewing NFS config via Storage > NFS > Advanced Edit I see that the snapshot folders are still mounted in the automatically added entries.  Note there is no NFS export created for the share when viewing the current NFS exports in the UI.  I did 'modify' the previously configured NFS export to use a different share but then ultimately deleted it after I received this error.

Now it just seems to be stuck in limbo and I cannot remove the share until it is removed from the NFS service but I cannot modify the NFS exports in the UI because that share isn't actually being exported anymore (at least not in the UI).

Is it possible to modify the NFS settings in the CLI somehow? I tried modifying the /etc/exports and restart the NFS service but to no avail.  Sort of stuck here now.

**Comment by t3kka** [comment]
After playing around, going directly into the Share1 details page and then the Snapshots tab, I was able to successfully delete the snapshots left in the subvolume which in turn removed them from the NFS mount config.  It may have been an issue with the order of operations I performed the original NFS mount change/modification or perhaps something else....I really need to understand more about the snapshotting process/expectations. Will leave this open for now to further understand from a dev hopefully why this was the case.

**Comment by t3kka** [comment]
@phillxnet yeah my bad..new to this issue stuff but I'll try to recreate it over the next few days and post back
