### ISSUE TITLE
Rockon Storageadmin view issue

### ISSUE THREAD

**Issue by magicalyak** [rockstor/rockstor-core#1963]
Rockon issue (new rockon created)
Looks like a task is stuck in the storageadmin table?

```
            Traceback (most recent call last):
  File "/opt/rockstor/eggs/gunicorn-19.7.1-py2.7.egg/gunicorn/workers/sync.py", line 68, in run_for_one
    self.accept(listener)
  File "/opt/rockstor/eggs/gunicorn-19.7.1-py2.7.egg/gunicorn/workers/sync.py", line 27, in accept
    client, addr = listener.accept()
  File "/usr/lib64/python2.7/socket.py", line 202, in accept
    sock, addr = self._sock.accept()
error: [Errno 11] Resource temporarily unavailable

```
    
![image](https://user-images.githubusercontent.com/6165889/45504866-0ba2ef80-b759-11e8-8f00-0ad1fe4cdddd.png)

```
[root@rocky log]# tailf /opt/rockstor/var/log/rockstor.log
[13/Sep/2018 13:02:06] ERROR [storageadmin.util:44] Exception: Found a failed Task (62fa15c8-427d-4137-a4b9-8910c92f7fe0) in the future of a pending Task (dd372af2-dbdf-45e1-b8da-b79028a96455).
Traceback (most recent call last):
  File "/opt/rockstor/eggs/gunicorn-19.7.1-py2.7.egg/gunicorn/workers/sync.py", line 68, in run_for_one
    self.accept(listener)
  File "/opt/rockstor/eggs/gunicorn-19.7.1-py2.7.egg/gunicorn/workers/sync.py", line 27, in accept
    client, addr = listener.accept()
  File "/usr/lib64/python2.7/socket.py", line 202, in accept
    sock, addr = self._sock.accept()
error: [Errno 11] Resource temporarily unavailable
[13/Sep/2018 13:04:02] ERROR [system.osi:119] non-zero code(1) returned by command: ['/sbin/btrfs', 'qgroup', 'show', '/mnt2/rockstor_rockstor/root00']. output: [''] error: ["ERROR: can't list qgroups: quotas not enabled", '']
[13/Sep/2018 13:04:14] ERROR [system.osi:119] non-zero code(1) returned by command: ['/sbin/btrfs', 'qgroup', 'show', '/mnt2/rockstor_rockstor/root00']. output: [''] error: ["ERROR: can't list qgroups: quotas not enabled", '']
[13/Sep/2018 13:04:18] ERROR [storageadmin.util:44] Exception: Found a failed Task (62fa15c8-427d-4137-a4b9-8910c92f7fe0) in the future of a pending Task (dd372af2-dbdf-45e1-b8da-b79028a96455).
Traceback (most recent call last):
  File "/opt/rockstor/eggs/gunicorn-19.7.1-py2.7.egg/gunicorn/workers/sync.py", line 68, in run_for_one
    self.accept(listener)
  File "/opt/rockstor/eggs/gunicorn-19.7.1-py2.7.egg/gunicorn/workers/sync.py", line 27, in accept
    client, addr = listener.accept()
  File "/usr/lib64/python2.7/socket.py", line 202, in accept
    sock, addr = self._sock.accept()
error: [Errno 11] Resource temporarily unavailable
[13/Sep/2018 13:04:21] ERROR [storageadmin.util:44] Exception: Found a failed Task (62fa15c8-427d-4137-a4b9-8910c92f7fe0) in the future of a pending Task (dd372af2-dbdf-45e1-b8da-b79028a96455).
Traceback (most recent call last):
  File "/opt/rockstor/eggs/gunicorn-19.7.1-py2.7.egg/gunicorn/workers/sync.py", line 68, in run_for_one
    self.accept(listener)
  File "/opt/rockstor/eggs/gunicorn-19.7.1-py2.7.egg/gunicorn/workers/sync.py", line 27, in accept
    client, addr = listener.accept()
  File "/usr/lib64/python2.7/socket.py", line 202, in accept
    sock, addr = self._sock.accept()
error: [Errno 11] Resource temporarily unavailable
[13/Sep/2018 13:04:28] ERROR [system.osi:119] non-zero code(1) returned by command: ['/sbin/btrfs', 'qgroup', 'show', '/mnt2/rockstor_rockstor/root00']. output: [''] error: ["ERROR: can't list qgroups: quotas not enabled", '']
[13/Sep/2018 13:04:58] ERROR [system.osi:119] non-zero code(1) returned by command: ['/sbin/btrfs', 'qgroup', 'show', '/mnt2/rockstor_rockstor/root00']. output: [''] error: ["ERROR: can't list qgroups: quotas not enabled", '']
[13/Sep/2018 13:05:14] ERROR [storageadmin.util:44] Exception: Found a failed Task (62fa15c8-427d-4137-a4b9-8910c92f7fe0) in the future of a pending Task (dd372af2-dbdf-45e1-b8da-b79028a96455).
Traceback (most recent call last):
  File "/opt/rockstor/eggs/gunicorn-19.7.1-py2.7.egg/gunicorn/workers/sync.py", line 68, in run_for_one
    self.accept(listener)
  File "/opt/rockstor/eggs/gunicorn-19.7.1-py2.7.egg/gunicorn/workers/sync.py", line 27, in accept
    client, addr = listener.accept()
  File "/usr/lib64/python2.7/socket.py", line 202, in accept
    sock, addr = self._sock.accept()
error: [Errno 11] Resource temporarily unavailable
[13/Sep/2018 13:05:17] ERROR [storageadmin.util:44] Exception: Found a failed Task (62fa15c8-427d-4137-a4b9-8910c92f7fe0) in the future of a pending Task (dd372af2-dbdf-45e1-b8da-b79028a96455).
Traceback (most recent call last):
  File "/opt/rockstor/eggs/gunicorn-19.7.1-py2.7.egg/gunicorn/workers/sync.py", line 68, in run_for_one
    self.accept(listener)
  File "/opt/rockstor/eggs/gunicorn-19.7.1-py2.7.egg/gunicorn/workers/sync.py", line 27, in accept
    client, addr = listener.accept()
  File "/usr/lib64/python2.7/socket.py", line 202, in accept
    sock, addr = self._sock.accept()
error: [Errno 11] Resource temporarily unavailable

```

**Comment by magicalyak** [comment]
I ended up just removing the tasks in the pgsql to get this to clear.

**Comment by FroggyFlox** [comment]
Hi @magicalyak ,
Could this be taken care of by `opt/rockstor/bin/delete-rockon`?

https://forum.rockstor.com/t/force-rockon-cleanup-in-postgres/3825/2?u=flox

**Comment by magicalyak** [comment]
That is exactly what I should have used, I just did it the manual way!  Yes that would have fixed it for sure.

**Comment by FroggyFlox** [comment]
Closing as this issue appears to have been resolved then.
