### ISSUE TITLE
remove/resize pool for detached single dev pool fails

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-core#2077]
Thanks to forum member Zonk for highlighting this issue. When a single disk pool suffers disk failure the suggested, via bubble, "Pool remove/resize" procedure to remove the associated pool / disk it fails with:

```
Traceback (most recent call last):
File “/opt/rockstor/eggs/gunicorn-19.7.1-py2.7.egg/gunicorn/workers/sync.py”, line 68, in run_for_one
self.accept(listener)
File “/opt/rockstor/eggs/gunicorn-19.7.1-py2.7.egg/gunicorn/workers/sync.py”, line 27, in accept
client, addr = listener.accept()
File “/usr/lib64/python2.7/socket.py”, line 202, in accept
sock, addr = self._sock.accept()
error: [Errno 11] Resource temporarily unavailable
```

Please update the following forum thread with this issue resolution:
https://forum.rockstor.com/t/cannot-delete-remove-a-failed-disk/6453

**Comment by phillxnet** [comment]
This report pertains to 3.9.2-48. A follow up report is expected once we get forum member Zonk upgraded to 3.9.2-50 which contains some significant updates to the disk/poll management code.

**Comment by phillxnet** [comment]
I have confirmed this behaviour in 3.9.2-51 with the accompanying user error message prior to the Traceback noted in this issues original report:

> Houston, we've had a problem.
> Pool member / raid edits require an active mount. Please see the "Maintenance required" section. 

So with the current reproducer of a single disk pool loosing it's only disk member and following the Web-UI guide we have a corner case that it's not possible to mount this pool. We could in this case identify if the detached disk was the only member and skip the otherwise required mount option. We already, in the disk section, advise only to remove the disk if it is not to be re-attached and presumably it is obvious that removing the only member of a pool will render the pool 'gone'.

Note that in this instance, of a single device pool where this devices is also detached, we also fail to allow the Pool details page - "Delete" button option for similar reasons:

> Houston, we've had a problem.
> Failed to mount Pool(rock-pool) due to an unknown reason. Command used ['/usr/bin/mount', u'/dev/disk/by-label/rock-pool', u'/mnt2/rock-pool'] 

```
[27/Jan/2020 13:09:32] INFO [fs.btrfs:504] Mount by label (/dev/disk/by-label/rock-pool) failed.                                                                
[27/Jan/2020 13:09:32] ERROR [storageadmin.util:44] Exception: Failed to mount Pool(rock-pool) due to an unknown reason. Command used ['/usr/bin/mount', u'/dev/disk/by-label/rock-pool', u'/mnt2/rock-pool']                                                                                                                                      
Traceback (most recent call last):                                                                                                                              
  File "/opt/rockstor/src/rockstor/rest_framework_custom/generic_view.py", line 41, in _handle_exception                                                        
    yield                                                                                                                                                       
  File "/opt/rockstor/src/rockstor/storageadmin/views/pool.py", line 655, in delete                                                                             
    force=force)                                                                                                                                                
  File "/opt/rockstor/src/rockstor/fs/btrfs.py", line 874, in remove_share                                                                                      
    root_pool_mnt = mount_root(pool)                                                                                                                            
  File "/opt/rockstor/src/rockstor/fs/btrfs.py", line 525, in mount_root                                                                                        
    'Command used %s' % (pool.name, mnt_cmd))                                                                                                                   
Exception: Failed to mount Pool(rock-pool) due to an unknown reason. Command used ['/usr/bin/mount', u'/dev/disk/by-label/rock-pool', u'/mnt2/rock-pool']
```

**Comment by phillxnet** [comment]
I am currently working on this issue, likely also working on the suspected as closely related:

"failure to remove detached disks via pool resize" #2099

**Comment by phillxnet** [comment]
By putting in a special case for last disk in pool being detached and avoiding the normal mount requirement, which is obviously nonsense in this case, and then special casing around our btrfs remove command, as this is a db issue only given no disks are attached that ever belonged to the pool. We can allow for removal but with a raged edge caveat:

### Test case: single disk pool with shares/snaps.
1: live detach disk, virtio in this case.
- Pool Degraded Alert in header.
- disk renamed to "detached-<random>"
-- Disk notices "Drive is a detached member of a Rockstor managed pool"
-- Exclamation: "Use Linked Page Pool resize/reraid 'Remove disks' option if no re-attachment is planned."
![warnings-on-last-disk-as-detached](https://user-images.githubusercontent.com/2521585/84577530-fedf7f80-adb4-11ea-9c9a-478eaeeffcec.png)

- Pool detail page shows single dev as detached and "Missing or removal in progress"  and usual "Maintenance required" section notifying us of the requirement that missing disk remoal requires a degraded,rw but to try degraded,ro and refresh backups first. Not quite appropriate but could be refined later and we have been told we can remove the disk so we proceed.

2: proceeding as per exclamation on the detached disk, as per issue and attempt to remove disk via Pool resize/reraid "Remove disks" option.
- We select the only disk which is indicated as detached-<random>
- Returned to Pool detail page and there are no disks listed.
- Refresh page and we have "Houston, we've had a problem Pool (3) does not exist."
![pool-does-note-exist-after-detached-member-removal](https://user-images.githubusercontent.com/2521585/84577680-78c43880-adb6-11ea-9df7-4128357f970b.png)
(RAGGED EDGE)

3: Visiting the pools overview and page refresh to remove warning and we are essentially sorted. Pool is gone and detached disk is now, no longer associated with a pool and can be removed via the 'bin' icon.
![disk-bin-but-pool-degraded-persistent](https://user-images.githubusercontent.com/2521585/84577756-0d2e9b00-adb7-11ea-8dc4-ebf0a33ad7bc.png)
(ragged edge) in that our pool degraded warning is still active, but this is no longer a rockstor managed pool. But the message now reads Pools found degraded (1): unimported. So that's about right really. And we do have a lingering btrfs memory of this pool still as we live unplugged this disk.
- detached disk can now be removed via bin icon. So was first removed form the pool, our usual method, then removed from the system via bin.

4: Reboot to reset our btrfs sub-system re live unplugged pool only member and we are as expected. No warnings.

It may be that for the time being this is a functional, and cosmetically wanting fix. As post proposed changes we can at least remove the last member of a pool when that last member is detached. And maintain our communication that a re-attachment is possible: the purpose of not just wiping all pool info whenever there are at least detached disks associated with it. And hence allowing for temporarily attached single disk Pool functionality.#

Posting by way of issue progress update.
