### ISSUE TITLE
failure to build on Tumbleweed for master tag 3.9.2-52

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-core#2113]
When preparing the final rpm releases for 3.9.2-52 the native build on a fully updated Tumbleweed failed. As a result no testing channel (currently openSUSE open) rpm for this distro was released. But openSUSE Leap15.1, our current main dev target, was not affected by this issue and so an rpm was released for this distro simultaneously with our current but now deprecated CentOS Stable channel. The observed build error was as follows:
```
Getting distribution for 'six==1.10.0'.
no previously-included directories found matching 'documentation/_build'
zip_safe flag not set; analyzing archive contents...
six: module references __path__
While:
  Installing django.
  Getting distribution for 'six==1.10.0'.
An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/buildbot/worker/Build-on-TW/rockstor-prod/eggs/zc.buildout-2.13.2-py2.7.egg/zc/buildout/buildout.py", line 2174, in main
    getattr(buildout, command)(args)
  File "/home/buildbot/worker/Build-on-TW/rockstor-prod/eggs/zc.buildout-2.13.2-py2.7.egg/zc/buildout/buildout.py", line 817, in install
    installed_files = self[part]._call(recipe.install)
  File "/home/buildbot/worker/Build-on-TW/rockstor-prod/eggs/zc.buildout-2.13.2-py2.7.egg/zc/buildout/buildout.py", line 1603, in _call
    return f()
  File "/home/buildbot/worker/Build-on-TW/rockstor-prod/eggs/djangorecipe-1.9-py2.7.egg/djangorecipe/recipe.py", line 67, in install
    requirements, ws = self.egg.working_set(['djangorecipe'])
  File "/home/buildbot/worker/Build-on-TW/rockstor-prod/eggs/zc.recipe.egg-2.0.7-py2.7.egg/zc/recipe/egg/egg.py", line 87, in working_set
    allow_unknown_extras=bool_option(buildout_section, 'allow-unknown-extras')
  File "/home/buildbot/worker/Build-on-TW/rockstor-prod/eggs/zc.recipe.egg-2.0.7-py2.7.egg/zc/recipe/egg/egg.py", line 168, in _working_set
    allow_unknown_extras=allow_unknown_extras)
  File "/home/buildbot/worker/Build-on-TW/rockstor-prod/eggs/zc.buildout-2.13.2-py2.7.egg/zc/buildout/easy_install.py", line 957, in install
    return installer.install(specs, working_set)
  File "/home/buildbot/worker/Build-on-TW/rockstor-prod/eggs/zc.buildout-2.13.2-py2.7.egg/zc/buildout/easy_install.py", line 730, in install
    for dist in self._get_dist(req, ws):
  File "/home/buildbot/worker/Build-on-TW/rockstor-prod/eggs/zc.buildout-2.13.2-py2.7.egg/zc/buildout/easy_install.py", line 574, in _get_dist
    dists = [_move_to_eggs_dir_and_compile(dist, self._dest)]
  File "/home/buildbot/worker/Build-on-TW/rockstor-prod/eggs/zc.buildout-2.13.2-py2.7.egg/zc/buildout/easy_install.py", line 1776, in _move_to_eggs_dir_and_compile
    assert newdist is not None  # newloc above is missing our dist?!
AssertionError
program finished with exit code 1
elapsedTime=31.730806
```

**Comment by phillxnet** [comment]
I am currently working on a pull request for this issue and in final testing phase. Looks to be the 'sort of indicated' old six library's interaction with Tumbleweeds particular Python 2.7 variant.
