### ISSUE TITLE
[NGboot to snapshot robustness

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-core#2166]

**Comment by phillxnet** [comment]
Initial point of failure here looks to be within initrock upon creating our /etc/issue.rockstor file:
```
-- Startup of the manager took 27925 microseconds.
May 09 16:09:27 leap15-2 sshd[1136]: pam_unix(sshd:session): session opened for user root by (uid=0)
May 09 16:09:27 leap15-2 initrock[720]: Traceback (most recent call last):
May 09 16:09:27 leap15-2 initrock[720]:   File "/opt/rockstor-dev/bin/initrock", line 38, in <module>
May 09 16:09:27 leap15-2 initrock[720]:     sys.exit(scripts.initrock.main())
May 09 16:09:27 leap15-2 initrock[720]:   File "/opt/rockstor-dev/src/rockstor/scripts/initrock.py", line 537, in main
May 09 16:09:27 leap15-2 initrock[720]:     shutil.copyfile("/etc/issue", "/etc/issue.rockstor")
May 09 16:09:27 leap15-2 initrock[720]:   File "/usr/lib64/python2.7/shutil.py", line 97, in copyfile
May 09 16:09:27 leap15-2 initrock[720]:     with open(dst, 'wb') as fdst:
May 09 16:09:27 leap15-2 initrock[720]: IOError: [Errno 30] Read-only file system: '/etc/issue.rockstor'
May 09 16:09:27 leap15-2 systemd[1]: rockstor-pre.service: Main process exited, code=exited, status=1/FAILURE
May 09 16:09:27 leap15-2 systemd[1]: Failed to start Tasks required prior to starting Rockstor.
-- Subject: Unit rockstor-pre.service has failed
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit rockstor-pre.service has failed.
-- 
-- The result is failed.
May 09 16:09:27 leap15-2 systemd[1]: Dependency failed for RockStor startup script.
-- Subject: Unit rockstor.service has failed
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit rockstor.service has failed.
-- 
-- The result is dependency.
May 09 16:09:27 leap15-2 systemd[1]: Dependency failed for Rockstor bootstrapping tasks.
-- Subject: Unit rockstor-bootstrap.service has failed
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit rockstor-bootstrap.service has failed.
-- 
-- The result is dependency.
May 09 16:09:27 leap15-2 systemd[1]: rockstor-bootstrap.service: Job rockstor-bootstrap.service/start failed with result 'dependency'.
May 09 16:09:27 leap15-2 systemd[1]: rockstor.service: Job rockstor.service/start failed with result 'dependency'.
May 09 16:09:27 leap15-2 systemd[1]: rockstor-pre.service: Unit entered failed state.
May 09 16:09:27 leap15-2 systemd[1]: rockstor-pre.service: Failed with result 'exit-code'.
May 09 16:09:27 leap15-2 systemd[1]: Reached target Multi-User System.
-- Subject: Unit multi-user.target has finished start-up
```
It is proposed that we surround such write requirement with try except and log if possible (var is a separate subvol).

**Comment by phillxnet** [comment]
An example of the expected output upon executing a snapper root rollback after having booted in to a prior zypper initiated read only root snapshot is as follows:
```
leap15-2:~ # snapper rollback
Creating read-only snapshot of default subvolume. (Snapshot 100.)
Creating read-write snapshot of current subvolume. (Snapshot 101.)
Setting default subvolume to snapshot 101.
leap15-2:~ # reboot
```
The problematic Rockstor instance, in this case containing code changes associated with issue:

"[NG] ROOT pool user share not displayed on page refresh" #2156

to improve system ROOT pool/share management was then able to start as normal during the subsequent rw root session.

**Comment by idnovic** [comment]
`When booting to a read only snapshot of root in our NG (Next Generation) 'Built on openSUSE' variant it would be preferable if we were able to start our various processes enough to inform the user of a successful boot.`

I think these two tools could be useful to check for a working base system. 

[Health-Checker](https://github.com/kubic-project/health-checker)
[Greenboot](https://github.com/fedora-iot/greenboot)

**Comment by phillxnet** [comment]
@idnovic Thanks for the pointers.
My intention in that wording was for the rockstor processes themselves to be able to start.

I.e.
rockstor-pre
rockstor-bootstrap
rockstor

So our Web-UI functioned enough for folks to be informed via that. I.e. we already indicate if a pool is read-on for instance. As opposed to just having just a command line. Ideally we would also offer advise on, or even better integrate the roll back mechanism. But my initial intention for this issue is for our existing services to not fall on their face and be of no use what-so-ever. And as I indicated in your original MicroOS issue, it would be the start of our journey to being able to function on a read only root which is what is encountered when booting to a root snapshot.

As to adding services that are not part of our immediate upstream; that is rather too much for our current development resources. But if there are official upstream supported packages (OBS) for these usefully looking facilities, that would be a definite start. When we started out many years ago we rolled our own btfs and a number of other custom packages. This ended up failing as we simply didn't have the resources. We are now down to a single package with some required changes pre-install to our base distro. Hence we need to not make the same mistake again and stick as closely as possible to our upstream. The second Greenboot suggestion only mentions fedora, who in the comming btrfs incarnation do not have boot to snapshot and are not one of our currently supported distros. And from our recent move from CentOS to openSUSE we have found a number of tripping points that we don't want to repeat by depending on software that does not concern itself with openSUSE targest (systemd names and config vary from distro to distro). I know systemd is semi-universal so it may be that Greenboot is appropriate but again we do wish to stick to upstream as best as we can. I'll try and take a proper look at these services to see if they could in deed help with this issues aim. But again the main aim with this issue is 

> ... help folks establish if they have at least achieved a successful boot from a Web-UI perspective prior to enabling that snapshot for the next boot via the:
> 
> ```
> snapper rollback
> ```

And your suggested packages, if available for Leap 15.2, may well be key to that. @FroggyFlox if you get time chip in here that may help with another perspective. It would certainly be good if we didn't fail absolutely from the Web-UI when doing this super valuable boot to snapshot event. I'm thinking if we see a read-only root we could simply indicate the required command, or offer to run it if need be. But ideally we also need to identify that we are in a boot-to-snapshot scenario and I don't think either package helps to indicate this. But I've not looked properly just yet :).

Thanks for taking the time to contribute to this issue by the way. Much appreciated. It's not received any attention since I created it and I think it's an important hole in our current 'Built on opeSUSE' endeavour. Although it is not a blocker for our Rockstor 4 release.
