### ISSUE TITLE
No disks Shown. Not a valid BTRFS Filesystem

### ISSUE THREAD

**Issue by der-geraet** [rockstor/rockstor-core#2185]
Today i started a very small project to create a NAS. For the os I decided to take Rockstor because it is easy to handle and the GUI makes everything easy. Well, i was wrong. After the installation guide (https://www.youtube.com/watch?v=nHwHy2otnd0&t=304s) it didn't work out as planned. First thing is that the os got back to its old system so the update wasn't worth it, and second the part i need help for is that all three of my 20gb HDDs in VMWare don't show up. As an error message i get:
            Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/rest_framework_custom/generic_view.py", line 41, in _handle_exception
    yield
  File "/opt/rockstor/src/rockstor/storageadmin/views/disk.py", line 377, in post
    return self._update_disk_state()
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/opt/rockstor/src/rockstor/storageadmin/views/disk.py", line 322, in _update_disk_state
    p.uuid = btrfs_uuid(dob.name)
  File "/opt/rockstor/src/rockstor/fs/btrfs.py", line 1055, in btrfs_uuid
    [BTRFS, 'filesystem', 'show', '/dev/disk/by-id/%s' % disk])
  File "/opt/rockstor/src/rockstor/system/osi.py", line 115, in run_command
    raise CommandException(cmd, out, err, rc)
CommandException: Error running a command. cmd = /sbin/btrfs filesystem show /dev/disk/by-id/sda3. rc = 1. stdout = ['']. stderr = ['ERROR: not a valid btrfs filesystem: /dev/disk/by-id/sda3', '']

I don't know what to do to get this to a btrfs filesystem so i need the help of the community. I thank you very much for your answers.

**Comment by phillxnet** [comment]
@der-geraet This is a know issue caused by the system drive in this case not having a serial number.

> i need help for is that all three of my 20gb HDDs in VMWare don't show up.

Check out our Quick start: http://rockstor.com/docs/quickstart.html Minimum system requirements section here: http://rockstor.com/docs/quickstart.html#minimum-system-requirements

There is a note on a required config for VMware use there.

Also I would advise that you ask such support type question on our forum:
https://forum.rockstor.com/
as that would be a better place to refine the exact nature of an bugs so we can bring them to a finer point ready to make focused GitHub issues. This particular report, and it's cause/fix, has many similar entries on the forum also.

Hope that helps. Also note that we have many guides of our own referenced in the docs referenced above.
