### ISSUE TITLE
initrock via rockstor-pre fails on non-existent /etc/issue

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-core#2335]
Under some circumstances a system can end up with no /etc/issue. Initrock, run by rockstor-pre.service can then fail trivially via:
```
Dec 29 11:32:08 installer initrock[671]: 2021-12-29 11:32:08,190: Done
Dec 29 11:32:08 installer initrock[671]: 2021-12-29 11:32:08,190: stopping firewalld...
Dec 29 11:32:08 installer systemd[1]: Reloading.
Dec 29 11:32:08 installer initrock[671]: 2021-12-29 11:32:08,445: firewalld stopped and disabled
Dec 29 11:32:08 installer initrock[671]: Traceback (most recent call last):
Dec 29 11:32:08 installer initrock[671]:   File "/opt/rockstor/bin/initrock", line 41, in <module>
Dec 29 11:32:08 installer initrock[671]:     sys.exit(scripts.initrock.main())
Dec 29 11:32:08 installer initrock[671]:   File "/opt/rockstor/src/rockstor/scripts/initrock.py", line 510, in main
Dec 29 11:32:08 installer initrock[671]:     shutil.copyfile("/etc/issue", "/etc/issue.rockstor")
Dec 29 11:32:08 installer initrock[671]:   File "/usr/lib64/python2.7/shutil.py", line 96, in copyfile
Dec 29 11:32:08 installer initrock[671]:     with open(src, 'rb') as fsrc:
Dec 29 11:32:08 installer initrock[671]: IOError: [Errno 2] No such file or directory: '/etc/issue'
Dec 29 11:32:08 installer systemd[1]: rockstor-pre.service: Main process exited, code=exited, status=1/FAILURE
░░ Subject: Unit process exited
```
Which in-turn fails rockstor.service & consequently rockstor-bootstrap.service vai a dependency chain.

The default upstream contents of /etc/issue is, in our new upstream of openSUSE, determined initially by:
```
rleap15-3:~ # cat /usr/lib/issue.d/10-openSUSE.conf 
Welcome to \S - Kernel \r (\l).
```

**Comment by phillxnet** [comment]
```
rleap15-3:~ # rpm -qf /usr/lib/issue.d/10-openSUSE.conf 
openSUSE-release-15.3-lp1532.157.1.x86_64
```
And the associated systemd service:
```
zypper info issue-generator
...
Information for package issue-generator:
----------------------------------------
Repository     : Leap_15_3
Name           : issue-generator
Version        : 1.7-1.17
Arch           : noarch
Vendor         : SUSE LLC <https://www.suse.com/>
Installed Size : 25.9 KiB
Installed      : No
Status         : not installed
Source package : issue-generator-1.7-1.17.src
Summary        : Generates an issue files from different snippets
Description    : 
    issue-generator is a tool to create an issue file dynamically.

```

**Comment by phillxnet** [comment]
Our treatment of /etc/issues history:
https://github.com/rockstor/rockstor-core/pull/940 (initrock)
with quick follow-up regression fix:
https://github.com/rockstor/rockstor-core/pull/962 (initrock)
and later:
https://github.com/rockstor/rockstor-core/pull/1702 (initrock)

**Comment by phillxnet** [comment]
It is proposed that we postpone any major changes to our existing outdated treatment of /etc/issue and for the time being fix our simple failure to back-up a file that does not exist, for whatever reason.

Later, maybe in our next testing channel run-up to our subsequent stable release, post 4.1.0-0, we can move over to using the issue-generator systemd service and simply drop our desired content into new within proposed content directories managed by this service.

But for now we have  basic failure to address to ensure we are more robust to whatever has caused this anomalous missing /etc/issue file situation.

**Comment by phillxnet** [comment]
From the following it looks like we have some dead code here also:
```
grep -R "update_issue" *
src/rockstor/system/osi.py:def update_issue(ipaddr):
src/rockstor/scripts/initrock.py:def init_update_issue(logger):
src/rockstor/scripts/initrock.py:    init_update_issue(logging)
```
So system/osi.py: update_issue() is no longer used.

**Comment by phillxnet** [comment]
I am working on a pull request for this issue.
