### ISSUE TITLE
[Rockons] - mapping same share multiple times causes Rockon Install failure

### ISSUE THREAD

**Issue by Hooverdan96** [rockstor/rockstor-core#2399]
There are instances (aside from testing) where it could be desirable to utilize the same share for different mappings in a Rockon installation (e.g. data/usage is separated via sub-directories already). This works fine when installing the underlying container using docker directly, however in the context of a Rockon installation, this will cause errors and the installation will fail:

For example:
<img width="563" alt="image" src="https://user-images.githubusercontent.com/35113775/192166013-8b23b83d-f3c7-430d-a0cd-7a332c4b24c9.png">

fails, and one can find in the logs the following messages:

`[25/Sep/2022 14:15:53] DEBUG [system.osi:205] Running command: /usr/bin/docker pull linuxserver/couchpotato:latest
[25/Sep/2022 14:16:03] DEBUG [storageadmin.views.rockon_helpers:206] Exception while installing the Rockon (23).
[25/Sep/2022 14:16:03] ERROR [storageadmin.views.rockon_helpers:207] 'NoneType' object has no attribute 'name'
Traceback (most recent call last):
  File "/opt/rockstor-dev/src/rockstor/storageadmin/views/rockon_helpers.py", line 204, in install
    globals().get("{}_install".format(rockon.name.lower()), generic_install)(rockon)
  File "/opt/rockstor-dev/src/rockstor/storageadmin/views/rockon_helpers.py", line 374, in generic_install
    cmd.extend(vol_ops(c))
  File "/opt/rockstor-dev/src/rockstor/storageadmin/views/rockon_helpers.py", line 295, in vol_ops
    share_mnt = "{}{}".format(settings.MNT_PT, v.share.name)
AttributeError: 'NoneType' object has no attribute 'name'
[25/Sep/2022 14:16:03] DEBUG [storageadmin.views.rockon_helpers:210] Set rock-on 23 state to install_failed
[25/Sep/2022 14:16:03] INFO [storageadmin.tasks:63] Task [install] completed OK`

I would expect that it would allow the installation, if shares are "shared" for the container.

**Comment by FroggyFlox** [comment]
@Hooverdan96, following your recent efforts in triaging our issues, it was found that this is now addressed by #2481.
As you mentioned, though, the overall behavior should be improved and this is tracked in #2258. I'm thus closing this issue to keep things more focused but let me know if I'm misunderstanding the scope of this issue and I'll re-open :).
