### ISSUE TITLE
(t) Django db migration fail - 4.1.0-0 to proposed 4.5.0-0

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-core#2402]
While preparing a proposed 4.5.0-0 testing channel rpm we have a Web-UI update failure concerning a database migration failure:
```
Oct 23 17:18:22 rleap15-3 [RPM][20123]: Transaction ID 6355694e started
Oct 23 17:18:22 rleap15-3 [RPM][20123]: erase rockstor-4.1.0-0.x86_64: success
Oct 23 17:18:26 rleap15-3 systemd[1]: Reloading.
Oct 23 17:18:26 rleap15-3 systemd[1]: Configuration file /etc/systemd/system/smb.service is marked world-inaccessible. This has no effect as configuration data is accessible via APIs without restrictions. Proceeding anyway.
Oct 23 17:18:26 rleap15-3 systemd[1]: Reloading.
Oct 23 17:18:27 rleap15-3 systemd[1]: Configuration file /etc/systemd/system/smb.service is marked world-inaccessible. This has no effect as configuration data is accessible via APIs without restrictions. Proceeding anyway.
Oct 23 17:18:27 rleap15-3 systemd[1]: Condition check resulted in Rockstor IPv6 Check being skipped.
Oct 23 17:18:27 rleap15-3 [RPM][20123]: install rockstor-4.5.0-2400.x86_64: success
Oct 23 17:18:27 rleap15-3 [RPM][20123]: erase rockstor-4.1.0-0.x86_64: success
Oct 23 17:18:27 rleap15-3 [RPM][20123]: install rockstor-4.5.0-2400.x86_64: success
Oct 23 17:18:27 rleap15-3 [RPM][20123]: Transaction ID 6355694e finished: 0
Oct 23 17:18:30 rleap15-3 systemd[1]: Starting Tasks required prior to starting Rockstor...
Oct 23 17:18:30 rleap15-3 initrock[21286]: /opt/rockstor/eggs/psycopg2-2.7.4-py2.7-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
Oct 23 17:18:30 rleap15-3 initrock[21286]:   """)
Oct 23 17:18:30 rleap15-3 initrock[21286]: 2022-10-23 11:18:30,686: Checking for flash and Running flash optimizations if appropriate.
Oct 23 17:18:31 rleap15-3 initrock[21286]: 2022-10-23 11:18:31,242: Updating the timezone from the system
Oct 23 17:18:31 rleap15-3 initrock[21286]: 2022-10-23 11:18:31,242: system timezone = Europe/London
Oct 23 17:18:31 rleap15-3 initrock[21286]: 2022-10-23 11:18:31,244: Changed timezone from America/Chicago to Europe/London
Oct 23 17:18:31 rleap15-3 initrock[21286]: 2022-10-23 11:18:31,246: Updating sshd_config
Oct 23 17:18:31 rleap15-3 initrock[21286]: 2022-10-23 11:18:31,247: SSHD_CONFIG Customization
Oct 23 17:18:31 rleap15-3 initrock[21286]: 2022-10-23 11:18:31,248: sshd_config already has the updates. Leaving it unchanged.
Oct 23 17:18:31 rleap15-3 initrock[21286]: 2022-10-23 11:18:31,248: Running app database migrations...
Oct 23 17:18:31 rleap15-3 initrock[21286]: 2022-10-23 11:18:31,268: non-zero code(1) returned by command: ['/opt/rockstor/bin/django', 'migrate', '--noinput', '--fake-initial', '--database=default', 'contenttypes']. output: [''] error: ['Traceback (most recent call last):', '  File "/opt/rockstor/bin/django", line 41, in <module>', '    import djangorecipe.manage', 'ImportError: No module named djangorecipe.manage', '']
Oct 23 17:18:31 rleap15-3 initrock[21286]: Traceback (most recent call last):
Oct 23 17:18:31 rleap15-3 initrock[21286]:   File "/opt/rockstor/bin/initrock", line 40, in <module>
Oct 23 17:18:31 rleap15-3 initrock[21286]:     sys.exit(scripts.initrock.main())
Oct 23 17:18:31 rleap15-3 initrock[21286]:   File "/opt/rockstor/src/rockstor/scripts/initrock.py", line 477, in main
Oct 23 17:18:31 rleap15-3 initrock[21286]:     fake_initial_migration_cmd + ["--database=default", "contenttypes"], log=True
Oct 23 17:18:31 rleap15-3 initrock[21286]:   File "/opt/rockstor/src/rockstor/system/osi.py", line 225, in run_command
Oct 23 17:18:31 rleap15-3 initrock[21286]:     raise CommandException(cmd, out, err, rc)
Oct 23 17:18:31 rleap15-3 initrock[21286]: system.exceptions.CommandException: Error running a command. cmd = /opt/rockstor/bin/django migrate --noinput --fake-initial --database=default contenttypes. rc = 1. stdout = ['']. stderr = ['Traceback (most recent call last):', '  File "/opt/rockstor/bin/django", line 41, in <module>', '    import djangorecipe.manage', 'ImportError: No module named djangorecipe.manage', '']
Oct 23 17:18:31 rleap15-3 systemd[1]: rockstor-pre.service: Main process exited, code=exited, status=1/FAILURE
Oct 23 17:18:31 rleap15-3 systemd[1]: rockstor-pre.service: Failed with result 'exit-code'.
Oct 23 17:18:31 rleap15-3 systemd[1]: Failed to start Tasks required prior to starting Rockstor.
Oct 23 17:18:31 rleap15-3 systemd[1]: Dependency failed for RockStor startup script.
Oct 23 17:18:31 rleap15-3 systemd[1]: rockstor.service: Job rockstor.service/start failed with result 'dependency'.
```
On initial inspection this looks to be related to our recent major Django update changes and specifically an import request.

**Comment by phillxnet** [comment]
In our recent Django update we renamed our prior "django-hack" file and replace it with "django-hack.py", the above error would seem to relate to the prior version/name of this file. I.e. no "import djangorecipe.manage" in our newer verwsion.

We may have a missing scripted change alteration concerning this file and end up not replacing it with our newer edition.

**Comment by phillxnet** [comment]
We have the following that should install our 'django hack' as the filename "django" from within our initrock script that is evidently called and logging from the above log.
```
grep -R 'django-hack'
...
src/rockstor/scripts/initrock.py:            "{}/conf/django-hack.py".format(BASE_DIR), "{}/django".format(BASE_BIN)
```
and the source file in this case looks to be the newer version, confirmed via:
```
cat /opt/rockstor/conf/django-hack.py
```

**Comment by phillxnet** [comment]
It now looks like we are using the old version of this file as we only assert its existence in initrock on un-configured installs, i.e. on fresh installs of an rpm, or when a source install is freshly build. Hence, as this was an update from a prior configured install we did not update this otherwise not touched for years file:

## In master branch
https://github.com/rockstor/rockstor-core/blob/81a0d5f5e0a6dfe5a922199828f66eeab0253e65/src/rockstor/scripts/initrock.py#L377-L381

## In testing branch
https://github.com/rockstor/rockstor-core/blob/c53fa9f6544b15cfc2b3eeef3e59fce3b65c8ca0/src/rockstor/scripts/initrock.py#L377-L381

**Comment by phillxnet** [comment]
To prove our updated django-hack file, when instantiated, resolves this migration issue we have the following:
```
cp /opt/rockstor/conf/django-hack.py /opt/rockstor/bin/django
reboot
```
resulting in a error free boot and rockstor service start, i.e. the prior failing migration now works as intended.

I will being working on an initrock modification to address this Django launch file update short fall.

**Comment by phillxnet** [comment]
We have a caveat here concerning the rpm package "%post" script:
from 
```
rpm -qp --scripts rockstor-4.5.0-0.x86_64.rpm
```
we have:
```
postinstall scriptlet (using /bin/sh):

#Actions to be taken during an rpm upgrade ($1 == 1 would be install)
if [ "$1" = "2" ]; then
    cp /opt/rockstor/conf/django-hack /opt/rockstor/bin/django
    for f in `find /opt/rockstor/var/log -type f`;
    do echo "Package upgrade" >> $f; done
fi
```
I.e. old reference related to the stable branch only.

It is also the case that our rpm contains two copies of this file as ones it is responsible for installing; both in it's source ./conf and target ./bin directories (named correctly for testing branch as django-hack.py & django respectively):
```
rpm -qli rockstor | grep 'bin/django\|conf/django'
/opt/rockstor/bin/django
/opt/rockstor/bin/django-admin
/opt/rockstor/bin/django-admin.py
/opt/rockstor/conf/django-hack.py
/opt/rockstor/eggs/Django-1.11.29-py2.7.egg/django/bin/django-admin.py
/opt/rockstor/eggs/Django-1.11.29-py2.7.egg/django/bin/django-admin.pyc
```
