### ISSUE TITLE
(t) resolve multiple leaf nodes in db migration graph

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-core#2404]
The following db migration conflict is a consequence of our now dual branch development and an attempt to maintain branch portability of, for example, the database migration associated with a more recent scrub model change (see: pr: #2398), I proposed that we resolve the following:
```
Oct 25 18:37:22 rleap15-3 initrock[31036]: Traceback (most recent call last):
Oct 25 18:37:22 rleap15-3 initrock[31036]:   File "/opt/rockstor/bin/initrock", line 40, in <module>
Oct 25 18:37:22 rleap15-3 initrock[31036]:     sys.exit(scripts.initrock.main())
Oct 25 18:37:22 rleap15-3 initrock[31036]:   File "/opt/rockstor/src/rockstor/scripts/initrock.py", line 517, in main
Oct 25 18:37:22 rleap15-3 initrock[31036]:     fake_initial_migration_cmd + ["--database=default", "contenttypes"], log=True
Oct 25 18:37:22 rleap15-3 initrock[31036]:   File "/opt/rockstor/src/rockstor/system/osi.py", line 225, in run_command
Oct 25 18:37:22 rleap15-3 initrock[31036]:     raise CommandException(cmd, out, err, rc)
Oct 25 18:37:22 rleap15-3 initrock[31036]: system.exceptions.CommandException: Error running a command. cmd = /opt/rockstor/bin/django migrate --noinput --fake-initial --database=default contenttypes. rc = 1. stdout = ['']. stderr = ['/opt/rockstor/eggs/psycopg2-2.7.4-py2.7-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.', '  """)', 'CommandError: Conflicting migrations detected; multiple leaf nodes in the migration graph: (0015_auto_20220918_1524, 0016_auto_20221020_1605 in storageadmin).', "To fix them run 'python manage.py makemigrations --merge'", '']
Oct 25 18:37:22 rleap15-3 systemd[1]: rockstor-pre.service: Main process exited, code=exited, status=1/FAILURE
Oct 25 18:37:22 rleap15-3 systemd[1]: rockstor-pre.service: Failed with result 'exit-code'.
Oct 25 18:37:22 rleap15-3 systemd[1]: Failed to start Tasks required prior to starting Rockstor.
Oct 25 18:37:22 rleap15-3 systemd[1]: Dependency failed for RockStor startup script.
Oct 25 18:37:22 rleap15-3 systemd[1]: rockstor.service: Job rockstor.service/start failed with result 'dependency'.
```
By manually transferring the prior partial Django update migration file in the testing branch:
0015_auto_20210513_1830.py associated with the above mentioned earlier pr:
"Update Django within current Python 2 constrains" #2254
with it's later follow-up migration file:
0016_auto_20221020_1605.py associated with (t) db migrations for GitHub pr #2365 and issue #2384
commit: https://github.com/rockstor/rockstor-core/commit/4f5881b4b333ac9538231009c481be2bb596d370
a discreet subset of pr #2400
Both of which are primarily concerned with the recent Django update. This way we combine the disparate parts of that efforts db modifications, thus far, and return our db migrations file to a single chronological thread where the testing channel, in it's more modern form, picks up after what is expected to be the last db update in the master channel (assuming we back-port the scrub db fix to master in time - as is planned).

I am preparing a pull request with this proposal which looks to resolve the above migration issue.

N.B. no package has yet been released with any of the more recent Django update work, so only developer source builds should be affected by the proposed db migration file set changes.

**Comment by phillxnet** [comment]
Closing as:
Fixed by #2405
