### ISSUE TITLE
(t) aarch64 4.5.4 rpm builds have insufficient dependencies

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-core#2469]
We have an initial build failure on aarch64 for GitHub testing tag 4.5.4-0 surfacing as an incomplete .venv creation:
```
du -sh /opt/rockstor/.venv/
20M     /opt/rockstor/.venv/
```

With the following contents of **/opt/rockstor/poetry-install.txt**
```
...
creating build/temp.linux-aarch64-2.7/src/greenlet
    gcc -pthread -fno-strict-aliasing -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -DNDEBUG -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -DOPENSSL_LOAD_CONF -fwrapv -fPIC -I/opt/rockstor/.venv/include/python2.7 -c src/greenlet/greenlet.cpp -o build/temp.linux-aarch64-2.7/src/greenlet/greenlet.o
    gcc: error trying to exec 'cc1plus': execvp: No such file or directory
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
    ERROR: Failed building wheel for greenlet
    Running setup.py clean for greenlet
...
```
Strongly suggesting a differing dependency regarding gcc between our x86_64 and aarch64 rpms.

The following rockstor-pre.service failure is the initial result:
```
localhost:/opt/rockstor # systemctl status rockstor-pre.service 
× rockstor-pre.service - Tasks required prior to starting Rockstor
     Loaded: loaded (/usr/lib/systemd/system/rockstor-pre.service; disabled; vendor preset: disabled)
     Active: failed (Result: exit-code) since Tue 2023-01-17 13:57:26 WET; 17min ago
    Process: 2450 ExecStart=/root/.local/bin/poetry run initrock (code=exited, status=1/FAILURE)
   Main PID: 2450 (code=exited, status=1/FAILURE)

Jan 17 13:57:20 localhost.localdomain systemd[1]: Starting Tasks required prior to starting Rockstor...
Jan 17 13:57:26 localhost.localdomain poetry[2450]: Traceback (most recent call last):
Jan 17 13:57:26 localhost.localdomain poetry[2450]:   File "<string>", line 1, in <module>
Jan 17 13:57:26 localhost.localdomain poetry[2450]:   File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
Jan 17 13:57:26 localhost.localdomain poetry[2450]:     __import__(name)
Jan 17 13:57:26 localhost.localdomain poetry[2450]: ImportError: No module named scripts.initrock
Jan 17 13:57:26 localhost.localdomain systemd[1]: rockstor-pre.service: Main process exited, code=exited, status=1/FAILURE
Jan 17 13:57:26 localhost.localdomain systemd[1]: rockstor-pre.service: Failed with result 'exit-code'.
Jan 17 13:57:26 localhost.localdomain systemd[1]: Failed to start Tasks required prior to starting Rockstor.
```

**Comment by phillxnet** [comment]
Work-around prior to next release:
```
zypper in --no-recommends gcc-c++

The following 2 NEW packages are going to be installed:
  gcc7-c++ gcc-c++

2 new packages to install.
Overall download size: 7.4 MiB. Already cached: 0 B. After the operation, additional 18.1 MiB will be used.
Continue? [y/n/v/...? shows all options] (y): y
```
Followed by an in-situ rebuilt:
```
cd /opt/rockstor/
./build.sh
```
The latter, after quite a while, should then end in the regular advise for a rebuild:
```
...
448 static files copied to '/opt/rockstor/static', 508 post-processed.

ROCKSTOR BUILD SCRIPT COMPLETED

If installing from source, from scratch, for development:
1. Run 'cd /opt/rockstor'.
2. Run 'systemctl start postgresql'.
3. Run 'export DJANGO_SETTINGS_MODULE=settings'.
4. Run 'poetry run initrock' as root (equivalent to rockstor-pre.service).
5. Run 'systemctl enable --now rockstor-bootstrap'.
```

However for regular rpm installs of this early 4.5.4-0 testing rpm on aarch64 (issue does not affect x86_64)  a simple reboot or 'systemctl enable --now rockstor-bootstrap' should return normal function.

**Comment by phillxnet** [comment]
This failure was not seen on the rpm build and test system as they had additional dependencies likely missed in our recent 15.4 profile changes in our installer config here:
https://github.com/rockstor/rockstor-installer/pull/125

```
rleap15-4aarch64:~ # zypper info gcc-c++
...
Information for package gcc-c++:
--------------------------------
Repository     : Main Repository
Name           : gcc-c++
Version        : 7-3.9.1
Arch           : aarch64
Vendor         : SUSE LLC <https://www.suse.com/>
Installed Size : 0 B
Installed      : Yes
Status         : up-to-date
...
```

**Comment by phillxnet** [comment]
Closing as fixed by adding the missing  "gcc-c++" to the rpm spec file, rebuilding for the arm64 repos and republishing over the top of the prior problematic rpms in the testing channel. A rebuild of our installer using the newly added Leap15.4.ARM64EFI profile, which resources the just refreshed 4.5.4-0 testing rpm, then booted with a working rockstor install, just post JeOS first boot setup on both qcow2 and raw image formats.
