### ISSUE TITLE
(t) Rockstor 4.5.7 on TW build - sshd_config location changed - for future consideration

### ISSUE THREAD

**Issue by Hooverdan96** [rockstor/rockstor-core#2501]
**Don't want to move focus from Leap 15.4 since that's the priority, just want to leave this behind for future considerations.**

@phillxnet , @FroggyFlox  if there's a better place to have these "notes" (or adding something else to the title), let me know.

After installing a Rockstor 4.5.7 build on OpenSUSE Tumbleweed iso and trying to turn on SFTP service, error message is thrown, indicating missing config file:

`            Traceback (most recent call last):`

`  File "/opt/rockstor/src/rockstor/smart_manager/views/sftp_service.py", line 55, in post
    toggle_sftp_service(switch=False)
  File "/opt/rockstor/src/rockstor/system/ssh.py", line 83, in toggle_sftp_service
    with open(SSHD_CONFIG) as sfo, open(npath, "w") as tfo:
IOError: [Errno 2] No such file or directory: '/etc/ssh/sshd_config'`

It seems that with Tumbleweed, the sshd configuration has moved here, and of course Rockstor can't find it then.
`/usr/etc/ssh`
<img width="700" alt="image" src="https://user-images.githubusercontent.com/35113775/221033051-351889e8-0374-4b04-add8-39ae1ee9c336.png">

I assume, the path for this set here in line 30:
https://github.com/rockstor/rockstor-core/blob/0249f5283203461d71093447611c762901f6f378/src/rockstor/system/ssh.py#L30-L34

**Comment by FroggyFlox** [comment]
Thanks a lot for taking the time to nicely detail this here, @Hooverdan96 !

This is indeed part of the UsrMerge that happened in tumbleweed a little while back as you documented.

When we address this one, I think we should take the opportunity to also switch to using override files as that would simplify things a lot, I think. Path should be `/etc/ssh/sshd_config.d/*.conf`.
I would love to know whether this would also be supported in Leap but I would be surprised, though.

**Comment by phillxnet** [comment]
@Hooverdan96 Nice find and report by the way. And thanks for kicking this one off.

@FroggyFlox 

> ... the opportunity to also switch to using override files ...

Agreed. I'm assuming this is akin to what we have just done with our nginx config - on the systemd side?

**Comment by FroggyFlox** [comment]
Yes.
If I'm correct, we can have one file per setting to override, so one for the `PermirRootLogin`, for instance, and then another one for the SFTP settings we apply.

**Comment by phillxnet** [comment]
@Hooverdan96 @FroggyFlox re:

> I would love to know whether this would also be supported in Leap but I would be surprised, though.

Maybe our 'transition' to the new override approach could be enacted in a Leap 15.4 (and Leap 15.5 - Beta now out by the way) via the addition, if not found already in the base file (/etc/ssh/sshd_config) of:

Include /etc/ssh/sshd_config.d/*.conf

I.e. if we find the 'old' file of: /etc/ssh/sshd_config then we search it for the above include: if not found we add it. From there on we push all our stuff into /etc/ssh/sshd_config.d/*.conf. We then have forward compatibility and can maintain our existing Leap compatibility.

Plus, to ease our burden of transition we now use, as per our nginx override recently, a single override file with our configs in. Multiple might be nice, but initially if we stick with a single one our existing code will essentially know no difference. We already try to 'stand apart' by doing edits only between our comments: but that has worn itself out now anyway as I believe we already edit what we find outside of those with the last major changes where we had to change the sftp subsystem of something. And that involved an edit of what was already there. So some work to do but we could take baby steps to get there. And a simple file exists check, then the addition of the Include entry if not found.

Need to look to Leap 15.5 to see what they have done really.

**Comment by Hooverdan96** [comment]
In the 15.5 alpha version this is still under `/etc/`:
<img width="339" alt="image" src="https://user-images.githubusercontent.com/35113775/221228152-d475de1b-c7f3-47ef-9fa8-7ffe7af00724.png">

I am in the progress of updating to the beta version now. BTW, found a cool tidbit for that: install the package `openSUSE-repos-Leap` and then perform `zypper dup` and the new repos are built and used for the upgrade.

**Comment by phillxnet** [comment]
@Hooverdan96 @FroggyFlox 
Side line but:

> BTW, found a cool tidbit for that: install the package `openSUSE-repos-Leap` and then perform `zypper dup` and the new repos are built and used for the upgrade.

Maybe this could be used in our 15.3 to 15.4 Howto doc: to be modelled on our existing:
https://rockstor.com/docs/howtos/15-2_to_15-3.html
But we have less complexities repo wise now, linking to new doc issue where this could be discussed:
https://github.com/rockstor/rockstor-doc/issues/417

@Hooverdan96 be sure to check if they have now included the **Include** mentioned earlier.

**Comment by Hooverdan96** [comment]
Just checked, the include is not in the file. When looking at the header it still states (like in 15.4):
`$OpenBSD: sshd_config,v 1.103 2018/04/09 20:41:22 tj Exp`
compared to the TW version that has the include:
`$OpenBSD: sshd_config,v 1.104 2021/07/02 05:11:21 dtucker Exp $`

**Comment by Hooverdan96** [comment]
just to give another update. I tried this on the Leap version. I updated the global config file that's still located in `/etc/ssh` with these lines (I know the `/usr/etc/ssh ...` was not necessary, but I did it anyway):
```
# To modify the system-wide sshd configuration, create a "*.conf" file under
# "/etc/ssh/sshd_config.d/" which will be automatically included below.
# Don't edit this configuration file itself if possible to avoid update
# problems.
Include /etc/ssh/sshd_config.d/*.conf

# The strategy used for options in the default sshd_config shipped with
# OpenSSH is to specify options with their default value where
# possible, but leave them commented.  Uncommented options override the
# default value.
Include /usr/etc/ssh/sshd_config.d/*.conf
```
and then took out the Rockstor entries at the bottom and placed them in a `.conf` file in the `/etc/ssh/sshd_config.d/`
I did not create a separate file for the Root permission (as you suggested above) but put that and the `AllowedUsers` into the same file for now. I also commented out the root permission parameter in the global file. Upon restart, ssh access continued to work same as before. So, looks like, if in Leap modify global file with the `include` statement and write Rockstor settings into separate config files. In TW just write the Rockstor settings into the separate config files.

**Comment by phillxnet** [comment]
@Hooverdan96 Thanks for more exploration on this front.

I've also noticed that although there is no ssh root login (by default) on the Tumbleweed x86_64 kvm xen images we bootstrap from (JeOS or now called Minimal_VM or something) if one uses the equivalent aarch64 image (that are still called JeOS). There is root login already enabled via the following file:

> /etc/ssh/sshd_config.d/PermitRootLogin.conf

Which contains:

```
    # Allow root login on ssh
    PermitRootLogin yes
```

So we are likely going to want to honour that. I.e. split that bit of our config out. And if this file doesn't exist we create it, with our required root ssh login (for development primarily). That way folks can change the file (if we end up persisting this in released installers) and we will not then change this setting back again.

This file could be added to our installer as another way to approach at least this bit of the config - assuming we have broken that out. That way folks could build installers with this disabled/enabled and our start-up config won't change that file if it sees it there.

Bit by Bit.

**Comment by Hooverdan96** [comment]
just for further information gathering. Looks like the path to the sshd_config is defined in three places:

https://github.com/rockstor/rockstor-core/blob/f41d786022dac232cd9f36c785c53f78919c28ad/src/rockstor/scripts/initrock.py#L168-L174

https://github.com/rockstor/rockstor-core/blob/eeb0084a2ea6f6bdb1cdbe35428aa5021ddadc72/src/rockstor/system/ssh.py#L28-L34

https://github.com/rockstor/rockstor-core/blob/eeb0084a2ea6f6bdb1cdbe35428aa5021ddadc72/src/rockstor/system/services.py#L27-L32

that would have to be considered during an "outsourcing" of the configuration file to pieces in the `sshd_config.d` (TW or not).

**Comment by FroggyFlox** [comment]
Thanks for the rundown here, @Hooverdan96.

I personally am not a fan of having the same thing defined at multiple places; we're asking for trouble here, maybe.

What would you think of progressively move our constants defined like that to a more central location so that we don't have the potential of constants being inconsistent throughout the code base? Maybe we could have a single `constants.py` (or multiple ones organized by "domain") to which we would refer elsewhere.
This and/or refactoring `services.py` so that we have all the code that needs to alter our ssh config in `ssh.py`.

**Comment by phillxnet** [comment]
This issue has a related testing element that currently block rpm building due to non existence ssh config file currently assumed in both tested and testing code. As such I'd like to raise it's priority as this takes time on the back-end where I have to manually accommodate before each release by instantiating the said file - but this then breaks ssh access after the tests have run due to the very limited config contained within - and it overriding (on TW) the other default config that is now held under /usr/etc:

> with Tumbleweed, the sshd configuration has moved here, and of course Rockstor can't find it then.
> `/usr/etc/ssh`

So this issue is now a partial blocker for our continued releases on TW and given the difficulties of Python 2 on 15.5 it may be that we have to use TW as our preferred OS during our Python 2 to 3 transition.

So I'll take a look at our first-draft on resolving this issue as it's pretty much alone in singling out TW currently as a dev/repair only base for us. Plus @Hooverdan96 is using it so there's that :) .

**Comment by phillxnet** [comment]
From @Hooverdan96's link: http://dominique.leuenberger.net/blog/2021/06/opensuse-tumbleweed-review-of-the-week-2021-23/
"Best to put config snippets in /etc/ssh/sshd_config.d/*.conf files to inherit distro config changes"

**Comment by phillxnet** [comment]
It may be the simplest transition we can do here is to conditionally (on say distro.id) do either what we have been doing, or, in the case of TW, move to using say an

> /etc/ssh/sshd_config.d/rockstor.conf

all-in-one override file - although I'd like to break out at least a:

> /etc/ssh/sshd_config.d/PermitRootLogin.conf

as per the above commit here: https://github.com/rockstor/rockstor-core/issues/2501#issuecomment-1466746507

Which then allows folks to just delete this file if that is not their want.

**Comment by phillxnet** [comment]
@FroggyFlox 
> we can have one file per setting to override, so one for the `PermitRootLogin`, for instance, and then another one for the SFTP settings we apply.

Yes, this would be nice. I'll have a look as I go - initially I was thinking of just one for all our settings but this is not in keeping with the newer approach.

**Comment by FroggyFlox** [comment]
Thank you so much for taking care of that one.
If I recall correctly, we also write to that file for each SFTP exports, don't we?

**Comment by phillxnet** [comment]
@FroggyFlox Just creeping up on this one now actually. Bit by bit.
In time what we do now, against this issue, will become the only way so trying to tread carefully but within time to have our next release with this in place!

**Comment by phillxnet** [comment]
> all-in-one override file - although I'd like to break out at least a:
> 
> > /etc/ssh/sshd_config.d/PermitRootLogin.conf

It appears that our use of AllowUsers will override this drop-in override file so I'm leaning towards instead having a flag file to enable (if there) or disable our inclusion of the 'root' user when we construct our AllowUsers entry.
See dedicated commit in current Draft PR:
https://github.com/phillxnet/rockstor-core/commit/f3cf8ef838778583721f93a3d27fd7cb4e5332c9

**Comment by phillxnet** [comment]
@FroggyFlox and @Hooverdan96 

> Maybe we could have a single `constants.py` (or multiple ones organized by "domain") to which we would refer elsewhere.

So it turns out we had to do exactly that due to a circular dependency I ran into. May have been fixable via:

> refactoring `services.py` so that we have all the code that needs to alter our ssh config in `ssh.py`.

But that is likely another mission creep on this front. Plus it turns out we have a massive amount of duplication re constants (as far as Python 'doesn't' actually have these) within our system domain so starting there.

See commit: https://github.com/phillxnet/rockstor-core/commit/67c8e06c031997ab3899e39d9e454b89b9a9cc31

It will be good to have this type of simple abstraction in place anyway before we move to maintaining both testing and master branches. So we should probably follow-up my current/pending pr against this issue with a global change of this sort as it's fairly simple work that will pay off later.

@FroggyFlox Thanks for the prompt. I really didn't expect to run into a circular situation like this but there it was, and hopefully there it goes along with future ones if we do this in a clean enough fashion. I would like to keep constants within their domain or intra file if that is the only place they are used.

Still fathoming the main issue but getting there.

**Comment by phillxnet** [comment]
Initial initrock run in TW (Pending commit) - indicated file not already existing: 
```
2023-05-10 11:02:43,165: Updating sshd config
2023-05-10 11:02:43,165: SSHD via (/etc/ssh/sshd_config.d/rockstor-sftp.conf) Customization
2023-05-10 11:02:43,165: SSHD updated via (/etc/ssh/sshd_config.d/rockstor-sftp.conf)
```
with the freshly created file contents, if conf/PermitRootLogin file exists, of:
```
cat /etc/ssh/sshd_config.d/rockstor-sftp.conf 
###BEGIN: Rockstor SFTP CONFIG. DO NOT EDIT BELOW THIS LINE###
Subsystem       sftp    internal-sftp
AllowUsers root
```
A consequent re-run of initrock:

> buildvm:/opt/rockstor # poetry run initrock

results in:

```
2023-05-10 11:13:13,806: Updating sshd config
2023-05-10 11:13:13,806: SSHD via (/etc/ssh/sshd_config.d/rockstor-sftp.conf) Customization
2023-05-10 11:13:13,807: SSHD via (/etc/ssh/sshd_config.d/rockstor-sftp.conf) already has the updates. Leaving unchanged.
```
with contents of file, and it's timestamp, unchanged.

**Comment by phillxnet** [comment]
So we do still have the existing issue of note being able to only override !!

> /usr/etc/ssh/sshd_config line 118: Subsystem 'sftp' already defined.

**Comment by phillxnet** [comment]
I've finally teased out the inter-dependecy that had crept in between services and ssh: see the following commit:
https://github.com/phillxnet/rockstor-core/commit/9769b9589560d9f2682f0e8d6eff022c806f031a

I think we are on the home run on this tidy up now.

**Comment by phillxnet** [comment]
To replace package default config we can do:
```
zypper install -f openssh-server
```

**Comment by Hooverdan96** [comment]
looks like great progress. I somehow did not imagine that this seemingly "simple" topic is leading to all of this refactoring and rearranging of where stuff should be located :). But I guess, it makes sense to when opening up this can of worms to do it "right".
Thanks for putting so much thought into this!

**Comment by phillxnet** [comment]
@Hooverdan96 Hello there, and thank for all the prep you did here. You and @FroggyFlox's comments have helped to set the stage.
Re:
> that this seemingly "simple" topic is leading to all of this refactoring and rearranging of where stuff should be located :).

What you said, plus: I'll likely just making a meal of it. But the cleaner it is on this pass the easier it will be to maintain. Plus I ran into a import loop back there so thought it time to do a little house keeping. Nearly there now however. Would be good to get a glance or two at this once I've submitted the pr.

I've not managed to split our config out completely into separate files but I think it's going to be a good start.

**Comment by phillxnet** [comment]
Post latest commits to working branch we have:

## Tumbleweed:

### Initial initrock run
2023-05-13 18:53:13,282: Initialising SSHD config
2023-05-13 18:53:13,283: SSHD (/usr/etc/ssh/sshd_config) sftp-server disabled
2023-05-13 18:53:13,283: SSHD - Creating new configuration file (/etc/ssh/sshd_config.d/rockstor-sftp.conf).
2023-05-13 18:53:13,284: SSHD (/etc/ssh/sshd_config.d/rockstor-sftp.conf) initialised
2023-05-13 18:53:13,284: SSHD config altered, restarting service

## Subsequent initrock run
2023-05-13 18:54:13,511: Initialising SSHD config
2023-05-13 18:54:13,511: SSHD (/usr/etc/ssh/sshd_config) sftp-server already disabled
2023-05-13 18:54:13,512: SSHD (/etc/ssh/sshd_config.d/rockstor-sftp.conf) already initialised

Now to tackle the sshd tests touching files on the real system!! And blocking rpm building by way of those tests also failing on Tumbleweed.

Getting there now. Apologies for the delay in getting this one ready by the way folks. It's just a pretty sensitive area and give we have our big testing branch merge into master just around the corner I wanted to have things clean on this front as there will be more to do here and likely fairly soon. Plus when one relies on the subsystem (sftp) that is being messed about by development code to do that same development there are some drawbacks :).

Haven't yet tackled the PermitRootLogin directive, or file, addition yet. But we have changed upstream defaults to consider there also. Also have to confirm that AllowUsers does in fact override the "PermitRootLogin yes".

**Comment by phillxnet** [comment]
So after an initial initrock run we do have:
```
Ran 253 tests in 30.757s

OK
```
But then our new files exist now !! Will look to the initial test run on my next session with this issue.

**Comment by phillxnet** [comment]
I am currently cleaning up the testing of sftp to address the last element of this issue: as indicted in the original issue text.
It seems we have yet to migrate the existing test to using fixtures!

**Comment by phillxnet** [comment]
Repeating our previously detailed reproducer for test failure in commit:  https://github.com/rockstor/rockstor-core/issues/2501#issuecomment-1546722749 we have (on a Tumbleweed instance):
```
rm /etc/ssh/sshd_config.d/rockstor-sftp.conf
```
and then a test run:
```
cd /opt/rockstor/src/rockstor
export DJANGO_SETTINGS_MODULE=settings
poetry run django-admin test -p test_sftp.py -v 2
```
resulting in :
```
...
  Applying storageadmin.0016_auto_20221020_1605... OK
System check identified no issues (0 silenced).
test_delete_requests_1 (rockstor.storageadmin.tests.test_sftp.SFTPTests) ... ok
test_delete_requests_2 (rockstor.storageadmin.tests.test_sftp.SFTPTests) ... ok
test_get (rockstor.storageadmin.tests.test_sftp.SFTPTests) ... ok
test_post_requests_1 (rockstor.storageadmin.tests.test_sftp.SFTPTests) ... ok
test_post_requests_2 (rockstor.storageadmin.tests.test_sftp.SFTPTests) ... ok

----------------------------------------------------------------------
Ran 5 tests in 0.137s

OK
Destroying test database for alias 'default' ('test_storageadmin')...
Destroying test database for alias 'smart_manager' ('test_smartdb')...
```
And we have no file system artifact due to test run!
```
ls /etc/ssh/sshd_config.d
PermitRootLogin.conf
```
Where the PermitRootLogin.conf was pre-existing in this instance. Noteworthy is that we have not created file due to our test run, and a successful test run without the expected configuration file already existing - by way our our last commit re missing mocks. We have also restored some previously remarked out basic sftp API tests run as part of our prior reduced set.

**Comment by phillxnet** [comment]
And we have a full test run pass:
```
poetry run django-admin test -v 2

Ran 253 tests in 33.565s

OK
```

**Comment by phillxnet** [comment]
@FroggyFlox & @Hooverdan96 I think we are basically there on this on. We do need more/some low-level tests on the sshd side of things but that should be for issue I think. I will next prep the associated work and re-submit as a non draft pr so we can take a final look. The write-through to test instance failure (requiring an existing config file) was down to insufficient mocking it turns out. I'll do some final testing but I think we are in a better place on this code now and I just need to check we haven't broken any of our existing non TW config arrangements. But I think we are likely OK on that front as there is little functional change by this half-way approach of just creating a new file wise to OS type approach.
