### ISSUE TITLE
EOL 15.3 issue re postgres user

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-core#2516]
Our current EOL 15.3 installers, display the following failure at the end of the install process:
![installer-fail-eol15 3](https://user-images.githubusercontent.com/2521585/224318366-972e96ef-18b4-4f03-bc64-7e6e4ca10e22.png)

The following:
```
localhost:~ # systemctl status rockstor-pre.service --no-pager --full
● rockstor-pre.service - Tasks required prior to starting Rockstor
     Loaded: loaded (/usr/lib/systemd/system/rockstor-pre.service; disabled; vendor preset: disabled)
     Active: failed (Result: exit-code) since Fri 2023-03-10 12:31:42 WET; 10min ago
    Process: 2056 ExecStart=/root/.local/bin/poetry run initrock (code=exited, status=1/FAILURE)
   Main PID: 2056 (code=exited, status=1/FAILURE)

Mar 10 12:31:42 localhost.localdomain poetry[2056]: Traceback (most recent call last):
Mar 10 12:31:42 localhost.localdomain poetry[2056]:   File "<string>", line 1, in <module>
Mar 10 12:31:42 localhost.localdomain poetry[2056]:   File "/opt/rockstor/src/rockstor/scripts/initrock.py", line 503, in main
Mar 10 12:31:42 localhost.localdomain poetry[2056]:     run_command(["su", "-", "postgres", "-c", command])
Mar 10 12:31:42 localhost.localdomain poetry[2056]:   File "/opt/rockstor/src/rockstor/system/osi.py", line 227, in run_command
Mar 10 12:31:42 localhost.localdomain poetry[2056]:     raise CommandException(cmd, out, err, rc)
Mar 10 12:31:42 localhost.localdomain poetry[2056]: system.exceptions.CommandException: Error running a command. cmd = su - postgres -c cp -f /opt/rockstor/conf/pg_hba.conf /var/lib/pgsql/data/. rc = 1. stdout = ['This account is currently not available.', '']. stderr = ['']
Mar 10 12:31:42 localhost.localdomain systemd[1]: rockstor-pre.service: Main process exited, code=exited, status=1/FAILURE
Mar 10 12:31:42 localhost.localdomain systemd[1]: rockstor-pre.service: Failed with result 'exit-code'.
Mar 10 12:31:42 localhost.localdomain systemd[1]: Failed to start Tasks required prior to starting Rockstor.
```
Indicates an issue with the 'postgres' user!

[EDIT] Executing the equivalent command in the console results in:
```
localhost:~ # su - postgres -c "cp -f /opt/rockstor/conf/pg_hba.conf /var/lib/pgsql/data/."
This account is currently not available.
```

**Comment by phillxnet** [comment]
An equally modern build of the installer using a 15.4 profile does not exhibit this behaviour.

**Comment by phillxnet** [comment]
## Leap 15.3 based installer:

```
cat /etc/passwd | grep postgres
postgres:x:478:478:PostgreSQL Server:/var/lib/pgsql:/sbin/nologin
```

## Leap 15.4 based installer:

```
cat /etc/passwd | grep postgres
postgres:x:490:479:PostgreSQL Server:/var/lib/pgsql:/bin/bash
```

**Comment by FroggyFlox** [comment]
Wow... that's an unexpected difference. Is that a postgresql version difference?

**Comment by phillxnet** [comment]
## Work-around:
N.B. it is not advised to use this EOL installer - Prefer earlier listed variants on our downloads page:


```
usermod --shell /bin/bash postgres
systemctl start rockstor-bootstrap.service
```

**Comment by phillxnet** [comment]
Closing as we no longer provide 15.3 installers, and while we did this issues detailed work-around was indicated on our downloads page as per the referenced rockstor-website downloads page update:

- Issue: https://github.com/rockstor/rockstor-website/issues/66
- PR: https://github.com/rockstor/rockstor-website/pull/67

Plus we have also now removed 15.3 based installer;, as from:

- https://github.com/rockstor/rockstor-website/pull/95
