### ISSUE TITLE
[Active Directory] Failure to set an AD user as Samba admin_user until Rockstor service restart

### ISSUE THREAD

**Issue by FroggyFlox** [rockstor/rockstor-core#2526]
Thanks to forum user **ocelot11** for reporting this issue: [https://forum.rockstor.com/t/active-directory-issues/8728/4](https://forum.rockstor.com/t/active-directory-issues/8728/4?u=flox)

# Description
As described in that forum post, when clicking on Submit during the creation of a Samba export using an AD user as the *admin_user*, Rockstor throws the following Exception:
```
Traceback (most recent call last):
File “/opt/rockstor/src/rockstor/rest_framework_custom/generic_view.py”, line 41, in _handle_exception
yield
File “/opt/rockstor/src/rockstor/storageadmin/views/samba.py”, line 239, in put
self._set_admin_users(admin_users, smbo)
File “/opt/rockstor/src/rockstor/storageadmin/views/samba.py”, line 141, in _set_admin_users
auo.smb_shares.add(smb_share)
UnboundLocalError: local variable ‘auo’ referenced before assignment
```
As detailed by @Hooverdan96 in that forum thread, the section throwing that exception is the following:
https://github.com/rockstor/rockstor-core/blob/e490c32c3308d0d18b468b902750aa9663784a5f/src/rockstor/storageadmin/views/samba.py#L118-L141

# Reproducer
1. Setup, configure, and turn ON the Active Directory service.
2. Go to Storage > Samba, and click on "Add Samba export".
3. Use an AD user as admin_user.
4. Click submit, and the error above is returned.

**Note** that if the Rockstor service is restarted or the machine rebooted, everything works as intended without error.
To reproduce this error again after a Rockstor service restart, one has to turn OFF the AD service, manually remove the AD user from the storageadmin.user table, manually remove the group from the storageadmin.group table, and then restart the Rockstor service. Without this "cleanup/reset" steps, the AD user remains "in cache" and thus no error will be returned upon creation of the Samba export as detailed in the reproducer steps above.

# Explanation
The `_set_admin_users()` method aims at adding the User <-> smb_share relationship in the database. Its logic can be summarized as follows:
1. Try to get the `storageadmin.user` object corresponding to the user set as admin_user in the Samba export form.
2. If no entry is found in `storageadmin.user`, fetch that info from system users using the `pwd` library.
3. Create corresponding `storageadmin.user` entry, save it, and then add the User <-> smb_share relationship.

In our case, the user is an AD user and thus does not have an entry in the `storageadmin.user` table. We thus try step 2 above. This one fails for a similar reason as investigated and solved in #2240. This is also why a Rockstor service restart works (as it did in #2240).

# Resolution
We may follow the same approach to fix this as we did to fix #2240: use InfoPipe as a failover mechanism if `pwd` cannot retrieve the required information. This will need further investigation to verify it is the best option, though.

**Comment by FroggyFlox** [comment]
I now have a working fix.
Currently, the following logic is followed:
1. check `User` for an existing entry
2. if 1 fails, check system users using `pwd` and create a `User` entry

The proposed fix is to add a second fallback mechanism using InfoPipe:
1. check `User` for an existing entry
2. if 1 fails, check system users for an existing user with that username using `pwd` and create a `User` entry
3. if 2 fails, check InfoPipe for an existing user with that username and create a `User` entry

There is an alternative approach, however. We indeed already have a method to parse all users as seen by `getent passwd`. This is what we use to list all users in the "Users" page. This list thus includes both local and domain users. We could thus use that already existing method and extract the `User` object needed by `_set_admin_users()` from that list. This method is `storageadmin.views.ug_helpers.combined_users()`:
https://github.com/rockstor/rockstor-core/blob/e490c32c3308d0d18b468b902750aa9663784a5f/src/rockstor/storageadmin/views/ug_helpers.py#L27

I think this second approach would have the benefit of being a lot more simple than the current approach as well as the first fix described above. I still need to verify whether using InfoPipe would have an advantage over using `getent passwd` (used by `combined_users()`). I wonder if InfoPipe would work to retrieve user info even if `enumerate = false`... I'm going to try that.

**Comment by FroggyFlox** [comment]
I tested as follows:
1. Reset/cleanup AD settings and cache on client (Rockstor machine)
2. Configure the AD service with **Enumeration disabled**
3. Turn ON the AD service
4. in Python console:
```python
>>> import pwd
>>> pwd.getpwnam("guest@samdom.example.com")
Traceback (most recent call last):
  File "<input>", line 1, in <module>
KeyError: 'getpwnam(): name not found: guest@samdom.example.com'
>>> pwd.getpwnam("guest@samdom.example.com")
Traceback (most recent call last):
  File "<input>", line 1, in <module>
KeyError: 'getpwnam(): name not found: guest@samdom.example.com'
# Above: the pwd module cannot see AD users, consistent with all prior observations.

# Below: try using combined_users(): based on getent passwd output: should not see AD users
>>> from storageadmin.views.ug_helpers import combined_users
>>> sysusers = combined_users()
# Above: inspecting sysusers reveals it includes only local system users, NO AD user is listed

# Below: try using InfoPipe
>>> username = "administrator@samdom.example.com"
>>> import dbus
>>> bus = dbus.SystemBus()
>>> users_obj = bus.get_object(
>>>     "org.freedesktop.sssd.infopipe", "/org/freedesktop/sssd/infopipe/Users"
>>> )
>>> users_iface = dbus.Interface(users_obj, "org.freedesktop.sssd.infopipe.Users")
>>> my_obj = bus.get_object("org.freedesktop.sssd.infopipe", users_iface.FindByName(username))
>>> my_iface_properties = dbus.Interface(my_obj, "org.freedesktop.DBus.Properties")
>>> user_id = my_iface_properties.Get(
>>>     "org.freedesktop.sssd.infopipe.Users.User", "uidNumber"
>>> )
>>> user_id
dbus.UInt32(755200500L, variant_level=1)
# Above: InfoPipe was able to retrieve the uid number from the AD user!

# Below: verify that pwd still cannot see AD users
>>> pwd.getpwnam("guest@samdom.example.com")
Traceback (most recent call last):
  File "<input>", line 1, in <module>
KeyError: 'getpwnam(): name not found: guest@samdom.example.com'
>>> pwd.getpwnam("administrator@samdom.example.com")
Traceback (most recent call last):
  File "<input>", line 1, in <module>
KeyError: 'getpwnam(): name not found: administrator@samdom.example.com'
```

It does seem like InfoPipe can see AD users even with enumeration disabled.

As a result, I now favor a hybrid approach to resolve this issue:
1. simplify our current `_set_admin_users()` to use `combined_users()`
2. Add a fallback mechanism using InfoPipe to try to retrieve user info in case enumeration is disabled for the AD service

@phillxnet, what do you think? I'm not well versed in `pwd` so I do not know what advantage it would have over our current parsing of `getent passwd` done in `combined_users()`. I have to admit that all our users/groups logic is rather confusing and it took me a while to have a better understanding of how we're doing it in various places. I may thus miss the obvious reason(s) for such inconsistencies (sometimes using `getent passwd`, other times using `pwd`); I do see that using `pwd` is very convenient and easy to parse, though, but we already have a seemingly good parsing of `getent passwd` thanks to Suman, I believe, so we might as well take advantage of it.

**Comment by phillxnet** [comment]
@FroggyFlox Re: 

> * simplify our current `_set_admin_users()` to use `combined_users()`

Simplify is good.

> I'm not well versed in `pwd` 

No, me neither and re:

> I may thus miss the obvious reason(s) for such inconsistencies ...

Inevitably our/all code can get this way, I suspect it has just been pulled in various directions without a concerted refactoring effort.

Re:

> I do see that using `pwd` is very convenient and easy to parse, though, but we already have a seemingly good parsing of `getent passwd` thanks to Suman, I believe, so we might as well take advantage of it.

Agreed.

I think, all that has happened, is a preference for a Python wrapper one time, and our also common place parsing of 'raw' linux commands another time. I think the linux parsing approach removes a layer and more easily allows folks to test at the command line in the event of an error. It's basically what works that counts and the simpler we can keep things the better also. We don't want to become another complex layer in proceedings ourselves, if we can help it. At least no more (or little more) complex that we have to be.

Not much help I know, but an implementation in code will likely also be informative. We do want to take advantage of other projects doing abstraction, but not at the cost of complexity/additional-dependency, or more future technical dept. But on the other hand parsing command output is fragile, but less so with well established/stable outputs. Or where a json output is available for example.

We likely need a refactoring of this entire area from the sounds of it. And what you are proposing may be the start of this, we can likely pop in a few tidy-ups (maybe via some specific issues detailing the specific aim) as we begin our new testing channel soon. So all does not need to be done no-directly.

**Comment by Hooverdan96** [comment]
Not sure whether that is really relevant here, but I found this (albeit a bit older) question, and it's also about LDAP:

https://serverfault.com/questions/673522/getent-passwd-dosent-show-users-of-ldap-server

Checking our current `sssd` config, the entry referenced in that post `enumerate` is set to `false` on Rockstor. The recommendation was that it needs to be set to `true` for `getent pwd` to work, but that's for LDAP and not explicitly called out for AD ...

But I can see now that there is some interaction for the enumerate parameter:
LDAP:
https://github.com/rockstor/rockstor-core/blob/eeb0084a2ea6f6bdb1cdbe35428aa5021ddadc72/src/rockstor/system/directory_services.py#L136-L156
AD:
https://github.com/rockstor/rockstor-core/blob/eeb0084a2ea6f6bdb1cdbe35428aa5021ddadc72/src/rockstor/system/directory_services.py#L94-L118

**Comment by FroggyFlox** [comment]
> Simplify is good.

Sounds good, I'll go that route, then:
1. simplify our current `_set_admin_users()` to use `combined_users()`
2. add a fallback mechanism using InfoPipe to try to retrieve user info in case enumeration is disabled for the AD service




> Not sure whether that is really relevant here(...)

Oh it definitely is. We use SSSD for both LDAP and AD as they do overlap. The need to enable enumeration is common for both, and we keep it disabled by default as this is SSSD's default (due to the fact that it can be using a lot of resource the first time for domains with a lot of users to fetch). You can see our related section of the docs for more details and link to SSSD's explanation on the matter: https://rockstor.com/docs/interface/system/services.html#active-directory-ad

It's thus the expected behavior here NOT to see anything with `combined_users()` when enumeration is disabled, but I wanted to double-check as I keep seeing some weirdness most likely related to caching. The bottom line here, I think, is that we do need some fallbacks mechanisms as we need to be able to cover multiple cases (enumeration on/off, and data cached or not, variety in AD/LDAP server setups and availability, etc...) if we want to offer our users a robust experience. That is also part of why I like having InfoPipe as a fallback here as that is a way designed to interface directly with SSSD and thus the upstream AD server so most likely to be the source of truth in our case. It also offers the option to get a lot more attributes about the users that one can set on an AD server; we don't yet surface these, but we might in the future if we have an SSSD base to communicate with the AD server.

**Comment by FroggyFlox** [comment]
I just observed a new bug:
1. Freshly configure and turn ON the AD service
2. Go straight to Storage > Samba
3. Create a new Samba export using an AD user as admin_user. This will result in that AD user having an entry in the `User` table
4. Go straight to the System > Users page: fails with:
```
[16/Apr/2023 16:42:01] ERROR [storageadmin.util:45] Exception: 'getgrgid(): gid not found: 755200513'
Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/rest_framework_custom/generic_view.py", line 41, in _handle_exception
    yield
  File "/opt/rockstor/src/rockstor/storageadmin/views/user.py", line 134, in get_queryset
    return combined_users()
  File "/opt/rockstor/src/rockstor/storageadmin/views/ug_helpers.py", line 37, in combined_users
    gname = get_groups(uo.gid).keys()[0]
  File "/opt/rockstor/src/rockstor/system/users.py", line 113, in get_groups
    entry = grp.getgrgid(g)
KeyError: 'getgrgid(): gid not found: 755200513'
```

This is yet another instance of `grp` not being able to see domain users on a "freshly" joined domain. Note that if one visits the System > Users page between steps 1 and 2 above. This indicates we somehow "refresh" something somewhere... I admit that I'm unsure of what that is at this point. It seems that a call to `combined_users()` makes `grp` and `pwd` suddenly aware of domain users somehow (this behavior is also consistently observed in my first fix described above for `_set_admin_users()`).
I have added a way to get that info using InfoPipe in case `grp` fails to fetch it.

**Comment by phillxnet** [comment]
@FroggyFlox Thanks for chasing this issue's/issues' long tail, and providing a robust fix.
My apologies for taking so long to merge and publish. This will be available in our soon to be released 4.5.9-0 (RC6) rpm.

Closing as:
Fixed by #2532
