### ISSUE TITLE
SSL Certificate update doesn't reload nginx

### ISSUE THREAD

**Issue by 6ixfalls** [rockstor/rockstor-core#2566]
## Brief description of the problem
I’m unable to update the SSL certificate for Rockstor through the web-ui (/home#update-certificate). After specifying a certificate name, certificate and private key, I get the error below. However, the certificate is indeed updated and you just need to manually restart nginx with systemctl restart nginx.

## Detailed step by step instructions to reproduce the problem
SSL Certificate tab under System, Update SSL Certificate and add the relevant configs.

## Error Traceback provided on the Web-UI
```
Traceback (most recent call last): File "/opt/rockstor/src/rockstor/rest_framework_custom/generic_view.py", line 41, in _handle_exception yield File "/opt/rockstor/src/rockstor/storageadmin/views/tls_certificate.py", line 92, in post superctl("nginx", "restart") File "/opt/rockstor/src/rockstor/system/services.py", line 142, in superctl out, err, rc = run_command([SUPERCTL_BIN, switch, service]) File "/opt/rockstor/src/rockstor/system/osi.py", line 227, in run_command logger.debug("Running command: {}".format(" ".join(cmd))) CommandException: Error running a command. cmd = /opt/rockstor/.venv/bin/supervisorctl restart nginx. rc = 1. stdout = ['nginx: ERROR (no such process)', 'nginx: ERROR (no such process)', '']. stderr = ['']
```

References [this forum post](https://forum.rockstor.com/t/error-running-a-command-cmd-opt-rockstor-venv-bin-supervisorctl-restart-nginx-rc-1-stdout-nginx-error-no-such-process-nginx-error-no-such-process-stderr/8833).

**Comment by FroggyFlox** [comment]
Thanks a lot for creating that issue, @6ixfalls!

For reference, we should change...
https://github.com/rockstor/rockstor-core/blob/1d4b9d5acd7236fc74d5c86f2cbfbb2c98326490/src/rockstor/storageadmin/views/tls_certificate.py#L92

... to use `system.services.systemctl()`.

Of note, `TLSCertificateView.post()` class would need some refactoring to separate the multiple `run_command()` calls we have in there; currently it seems not possible to cover this with unit tests, for instance. That'll be for its own dedicated issue, though.

**Comment by FroggyFlox** [comment]
@phillxnet, @Hooverdan96 , thanks a lot for the additional input here!
Would you be ok with including the fix to that one to the current `master` branch? It should be a relatively isolated change (:crossed_fingers:) and a follow-up to the move to Poetry so that would make sense. I know it would be a direct merge to master, though...
Let me know...

**Comment by phillxnet** [comment]
@FroggyFlox Re:

> Would you be ok with including the fix to that one to the current `master` branch?

Agreed, I'll get on this now ready for our planned final 4.6.1-0 Stable release. Given we have incurred a delay re the Shopify API fiasco.
