### ISSUE TITLE
Py3.6 Errors in (rockstor.fs.tests.test_btrfs.BTRFSTests)

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-core#2571]
Post #2567 in testing branch we have the following test failures in rockstor.fs.tests.test_btrfs.BTRFSTests

```
cd /opt/rockstor/src/rockstor/fs
export DJANGO_SETTINGS_MODULE=settings
poetry run django-admin test -p test_btrfs.py -v 2
```
Results in:
```
======================================================================
ERROR: test_balance_status_internal_unknown_mnt (rockstor.fs.tests.test_btrfs.BTRFSTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/fs/tests/test_btrfs.py", line 789, in test_balance_status_internal_unknown_mnt
    result = balance_status_internal(pool)
  File "/opt/rockstor/src/rockstor/fs/btrfs.py", line 2238, in balance_status_internal
    if unallocated >= 0:
TypeError: '>=' not supported between instances of 'NoneType' and 'int'

======================================================================
ERROR: test_balance_status_internal_unknown_parsing (rockstor.fs.tests.test_btrfs.BTRFSTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/fs/tests/test_btrfs.py", line 754, in test_balance_status_internal_unknown_parsing
    result = balance_status_internal(pool)
  File "/opt/rockstor/src/rockstor/fs/btrfs.py", line 2238, in balance_status_internal
    if unallocated >= 0:
TypeError: '>=' not supported between instances of 'NoneType' and 'int'

======================================================================
ERROR: test_get_pool_raid_levels_identification (rockstor.fs.tests.test_btrfs.BTRFSTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/fs/tests/test_btrfs.py", line 297, in test_get_pool_raid_levels_identification
    None, raid_levels_tested, btrfs_fi_di, return_dict
TypeError: 'NoneType' object is not callable
```
They are suspected as also having a knock-on effect with some Pool related tests but this will be more apparent once these 3 tests, or tested code has been fixed re our Py3.6 move.

**Comment by phillxnet** [comment]
Closing as:
Fixed by #2573
