### ISSUE TITLE
[Config backups] GET error if file not found

### ISSUE THREAD

**Issue by FroggyFlox** [rockstor/rockstor-core#2593]
I noticed this issue while working on #2569, but it is unrelated to that work.
This issue is indeed already existing in our `master` branch.

The Config Backups UI can throw a GET error if the file for a config backup entry in the database cannot be found:
```
Unknown internal error doing a GET to /api/config-backup?page=1&format=json&page_size=32000&count= 
```

The logs actually tell us what is happening:
```
[10/Jun/2023 09:23:34] ERROR [storageadmin.views.config_backup:612] [Errno 2] No such file or directory: '/opt/rockstor/static/config-backups/backup-2023-06-10-092243.json.gz'
Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/storageadmin/views/config_backup.py", line 609, in get_queryset
    with gzip.open(fp, "rb") as f:
  File "/usr/lib64/python3.6/gzip.py", line 53, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/usr/lib64/python3.6/gzip.py", line 163, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/opt/rockstor/static/config-backups/backup-2023-06-10-092243.json.gz'
[10/Jun/2023 09:23:34] INFO [storageadmin.views.config_backup:615] The file backup-2023-06-10-092243.json.gz is not gzipped, so compress it now.
[10/Jun/2023 09:23:34] DEBUG [system.osi:225] Running command: /usr/bin/gzip /opt/rockstor/static/config-backups/backup-2023-06-10-092243.json.gz
[10/Jun/2023 09:23:34] DEBUG [system.osi:225] Running command: /usr/bin/zypper --non-interactive -q list-updates
[10/Jun/2023 09:23:34] ERROR [system.osi:249] non-zero code(1) returned by command: ['/usr/bin/gzip', '/opt/rockstor/static/config-backups/backup-2023-06-10-092243.json.gz']. output: [''] error: ['gzip: /opt/rockstor/static/config-backups/backup-2023-06-10-092243.json.gz: No such file or directory', '']
[10/Jun/2023 09:23:34] ERROR [storageadmin.middleware:33] Exception occurred while processing a request. Path: /api/config-backup method: GET
[10/Jun/2023 09:23:34] ERROR [storageadmin.middleware:34] ConfigBackup object can't be deleted because its id attribute is set to None.
Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/storageadmin/views/config_backup.py", line 609, in get_queryset
    with gzip.open(fp, "rb") as f:
  File "/usr/lib64/python3.6/gzip.py", line 53, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/usr/lib64/python3.6/gzip.py", line 163, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/opt/rockstor/static/config-backups/backup-2023-06-10-092243.json.gz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/storageadmin/views/config_backup.py", line 620, in get_queryset
    o, err, rc = run_command(["/usr/bin/gzip", fp], log=True)
  File "/opt/rockstor/src/rockstor/system/osi.py", line 251, in run_command
    raise CommandException(cmd, out, err, rc)
system.exceptions.CommandException: Error running a command. cmd = /usr/bin/gzip /opt/rockstor/static/config-backups/backup-2023-06-10-092243.json.gz. rc = 1. stdout = ['']. stderr = ['gzip: /opt/rockstor/static/config-backups/backup-2023-06-10-092243.json.gz: No such file or directory', '']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/rockstor/.venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/rockstor/.venv/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/rockstor/.venv/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/rockstor/.venv/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/opt/rockstor/.venv/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/rockstor/.venv/lib/python3.6/site-packages/rest_framework/views.py", line 466, in raise_uncaught_exception
    raise exc
  File "/opt/rockstor/.venv/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/rockstor/.venv/lib/python3.6/site-packages/rest_framework/generics.py", line 241, in get
    return self.list(request, *args, **kwargs)
  File "/opt/rockstor/.venv/lib/python3.6/site-packages/rest_framework/mixins.py", line 40, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "/opt/rockstor/src/rockstor/storageadmin/views/config_backup.py", line 638, in get_queryset
    cbo.delete()
  File "/opt/rockstor/.venv/lib/python3.6/site-packages/django/db/models/base.py", line 969, in delete
    (self._meta.object_name, self._meta.pk.attname)
AssertionError: ConfigBackup object can't be deleted because its id attribute is set to None.
```

As listed above, we start with a FileNotFound error, but then we can see that the processing logic continues nonetheless, leading to even more errors as we keep trying to process a file that does not exist.

This relates to a `TODO` added in #2592:
https://github.com/rockstor/rockstor-core/blob/a16d9483c0d5b834d764f96213c9449a2ecfe436/src/rockstor/storageadmin/views/config_backup.py#L605

**Comment by FroggyFlox** [comment]
**Workaround** for those seeing this error: simply refresh the page.
The model entry is indeed correctly removed because the file was not found on the disk, so Rockstor will not try to process that backup again upon page refresh.
