### ISSUE TITLE
Py3.8 TW collectstatic failure

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-core#2622]
While testing a Py3.8 pyproject.toml setting via:
"Update specifics of Python version in pyproject.toml #2620" #2621
&
https://github.com/rockstor/rockstor-rpmbuild/pull/22/files

We have what looks like a Huey compatibility re setup and newer Python:
```
rtumbleweed:/opt/rockstor # poetry run django-admin collectstatic --no-input --verbosity 2
BASE_DIR=/opt/rockstor
Traceback (most recent call last):
  File "/opt/rockstor/.venv/bin/django-admin", line 8, in <module>
    sys.exit(execute_from_command_line())
  File "/opt/rockstor/.venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/opt/rockstor/.venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "/opt/rockstor/.venv/lib/python3.8/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/opt/rockstor/.venv/lib/python3.8/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/rockstor/.venv/lib/python3.8/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/rockstor/src/rockstor/settings.py", line 421, in <module>
    HUEY = SqliteHuey(filename='{}/rockstor-tasks-huey.db'.format(BASE_DIR))
  File "/opt/rockstor/.venv/lib/python3.8/site-packages/huey/api.py", line 116, in __init__
    self.storage = self.create_storage()
  File "/opt/rockstor/.venv/lib/python3.8/site-packages/huey/api.py", line 135, in create_storage
    return self.get_storage(**self.storage_kwargs)
  File "/opt/rockstor/.venv/lib/python3.8/site-packages/huey/api.py", line 147, in get_storage
    return Storage(self.name, **kwargs)
  File "/opt/rockstor/.venv/lib/python3.8/site-packages/huey/storage.py", line 713, in __init__
    super(SqliteStorage, self).__init__(name)
  File "/opt/rockstor/.venv/lib/python3.8/site-packages/huey/storage.py", line 628, in __init__
    self.initialize_schema()
  File "/opt/rockstor/.venv/lib/python3.8/site-packages/huey/storage.py", line 664, in initialize_schema
    with self.db(commit=True, close=True) as curs:
  File "/usr/lib64/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/opt/rockstor/.venv/lib/python3.8/site-packages/huey/storage.py", line 647, in db
    conn = self.conn
  File "/opt/rockstor/.venv/lib/python3.8/site-packages/huey/storage.py", line 639, in conn
    self._state.set_connection(self._create_connection())
  File "/opt/rockstor/.venv/lib/python3.8/site-packages/huey/storage.py", line 716, in _create_connection
    conn = sqlite3.connect(self.filename, timeout=self._timeout,
AttributeError: 'NoneType' object has no attribute 'connect'
```
Our Huey 2.3.0 was updated to 2.4.5:
   • Updating huey (2.3.0 -> 2.4.5)
to see if we have a Huey Python issue but the failure remained.

It is currently supposed that we have the 'edge' of our current Django compatibility here, re Py3.7 as last Python for our current Django.

The following line in the above output:
> BASE_DIR=/opt/rockstor

was after the following line was modified (for Py3.6 syntax) in settings.py to double check our BASE_DIR:

> print("BASE_DIR={}".format(BASE_DIR))  # "/opt/rockstor" via 'django-admin runserver'

The same build (post the indicated proposed patches) succeeds on a Leap 15.4 Py3.6 based venv.

**Comment by phillxnet** [comment]
Thanks to @FroggyFlox for identifying our issue here.
It turns out we had a missing dependency of python38 (base) and we also require to specify our host Python version during a poetry install: Notes have been made regarding these find in build.sh.
Existing systems that already have poetry installed are not affected by this.

Closing as this issue is now understood and relates to our older Poetry and newer TW Python. Both are to be accomodated as more move through out next few GitHub milestones. And our TW target may have to await one or two more of those to be completed before we can again build installers for example.
