### ISSUE TITLE
Failure to automatically update/configure Samba workgroup during AD service activation

### ISSUE THREAD

**Issue by FroggyFlox** [rockstor/rockstor-core#2671]
In #2273, we added the automatic configuration of the Samba service workgroup during the activation of the Active Directory (AD) service (these need to match).

I'm not sure why/how but this procedure now fails (tested on Leap 15.5, testing branch only) with:
```
[11/Sep/2023 12:35:03] ERROR [storageadmin.util:45] Exception: Error running a command. cmd = /usr/bin/net ads workgroup -S samdom.example.com. rc = 255. stdout = ['']. stderr = ["Didn't find the cldap server!", '']
Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/rest_framework_custom/generic_view.py", line 41, in _handle_exception
    yield
  File "/opt/rockstor/src/rockstor/smart_manager/views/active_directory.py", line 163, in post
    config["workgroup"] = domain_workgroup(domain, method=method)
  File "/opt/rockstor/src/rockstor/system/directory_services.py", line 309, in domain_workgroup
    o, e, rc = run_command(cmd)
  File "/opt/rockstor/src/rockstor/system/osi.py", line 251, in run_command
    raise CommandException(cmd, out, err, rc)
system.exceptions.CommandException: Error running a command. cmd = /usr/bin/net ads workgroup -S samdom.example.com. rc = 255. stdout = ['']. stderr = ["Didn't find the cldap server!", '']
```

This happens when `smb.conf` does not contain any information pertaining to the AD server/realm. We can thus bypass that by explicitly telling `net` the realm:
```
buildvm155:/opt/rockstor # net ads workgroup --realm=SAMDOM.EXAMPLE.COM
Workgroup: SAMDOM
```

It seems we should thus switch from using the `-S` flag to the `--realm=<REALM>` flag.

**Comment by FroggyFlox** [comment]
For the record: https://manpages.opensuse.org/Tumbleweed/samba-client/net.8.en.html

Current (problematic) option used:
> -S|--server server
> Name of target server. You should specify either this option or a target workgroup or a target IP address.

Proposed fix:
> -r|--realm=REALM
> Set the realm for the domain.
> 
> Note that specifying this parameter here will override the realm parameter in the /etc/samba/smb.conf file.

**Comment by phillxnet** [comment]
Closing as:
Fixed by #2672
