### ISSUE TITLE
[Services] Websocket failure to update service status

### ISSUE THREAD

**Issue by FroggyFlox** [rockstor/rockstor-core#2681]
In the "System" > "Services" page, we have websocket that fetches the status of each service and sends it to our front-end to update the toggle buttons. This unfortunately is currently failing, resulting in a toggled button remaining "misaligned" (see screenshot below) until a manual page refresh:
![image](https://github.com/rockstor/rockstor-core/assets/30297881/4a47eb40-5c45-4abe-99b3-e11abcb06e98)

By using Firefox's dev tools, we can see that the websocket is correctly created and removed upon visiting/leaving the "Services" page, but it does not seem to send/return any data on the services' statuses, hence the failure to refresh the toggle button state.

It turns out this failure results from an Exception thrown when checking the status of the "replication" service. This exception is normal (when the replication service is OFF), but we shouldn't fail the checking of service status as a result.

**Comment by FroggyFlox** [comment]
As a confirmation, setting `throw=False` to the underlying `run_command()` checking the status of the replication service, we no-longer see this exception being thrown, and the `"get_services"` websocket returns a correct response full of data at the expected interval. The toggle button is also updated and re-aligned at that time.

**Comment by FroggyFlox** [comment]
For details, the exception we see in the logs when visiting the Services page is:
```
[30/Sep/2023 11:19:11] ERROR [smart_manager.views.base_service:73] Exception while querying status of service(replication): Error running a command. cmd = /opt/rockstor/.venv/bin/supervisorctl status replication. rc = 3. stdout = ['replication                      STOPPED   Not started', '']. stderr = ['']
[30/Sep/2023 11:19:11] ERROR [smart_manager.views.base_service:74] Error running a command. cmd = /opt/rockstor/.venv/bin/supervisorctl status replication. rc = 3. stdout = ['replication                      STOPPED   Not started', '']. stderr = ['']
Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/smart_manager/views/base_service.py", line 64, in _get_status
    o, e, rc = service_status(service.name, config)
  File "/opt/rockstor/src/rockstor/system/services.py", line 192, in service_status
    return superctl(service_name, "status")
  File "/opt/rockstor/src/rockstor/system/services.py", line 142, in superctl
    out, err, rc = run_command([SUPERCTL_BIN, switch, service])
  File "/opt/rockstor/src/rockstor/system/osi.py", line 251, in run_command
    raise CommandException(cmd, out, err, rc)
system.exceptions.CommandException: Error running a command. cmd = /opt/rockstor/.venv/bin/supervisorctl status replication. rc = 3. stdout = ['replication                      STOPPED   Not started', '']. stderr = ['']
```

As we can see, the command itself does not fail, but returns a proper output with a `rc` of 3. Based on our `run_command()` logic, we raise a `CommandException` given `rc != 0 `:
https://github.com/rockstor/rockstor-core/blob/a2d75941ca998099b7930099c5ecc8adf000325a/src/rockstor/system/osi.py#L243-L251

Here, we should thus set `throw=False`.
