### ISSUE TITLE
(t) Error when trying to delete NFS export via WebUI

### ISSUE THREAD

**Issue by Hooverdan96** [rockstor/rockstor-core#2742]
@FroggyFlox, @phillxnet 

I tried to delete a NFS export that I had previously created using the last stable (4.5.8). In the meantime I activated the test channel and went to 5.0.5 (not sure whether that matters).

when attempting to delete the NFS export, it created an error message:

```
            Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/storageadmin/views/nfs_exports.py", line 147, in refresh_wrapper
    refresh_nfs_exports(exports)
  File "/opt/rockstor/src/rockstor/system/osi.py", line 780, in refresh_nfs_exports
    return run_command([EXPORTFS, "-ra"])
  File "/opt/rockstor/src/rockstor/system/osi.py", line 263, in run_command
    raise CommandException(cmd, out, err, rc)
system.exceptions.CommandException: Error running a command. cmd = /usr/sbin/exportfs -ra. rc = 1. stdout = ['']. stderr = ['exportfs: /etc/exports.d/rockstor.exports [1]: Neither \'subtree_check\' or \'no_subtree_check\' specified for export "*:/export/AAA/bbb".', "  Assuming default behaviour ('no_subtree_check').", '  NOTE: this default has changed since nfs-utils version 1.0.x', '', 'exportfs: /etc/exports.d/rockstor.exports [2]: Neither \'subtree_check\' or \'no_subtree_check\' specified for export "*:/export/AAA/ccc".', "  Assuming default behaviour ('no_subtree_check').", '  NOTE: this default has changed since nfs-utils version 1.0.x', '', 'exportfs: /etc/exports.d/rockstor.exports [3]: Neither \'subtree_check\' or \'no_subtree_check\' specified for export "*:/export/AAA/ddd".', "  Assuming default behaviour ('no_subtree_check').", '  NOTE: this default has changed since nfs-utils version 1.0.x', '', 'exportfs: /etc/exports.d/rockstor.exports [4]: Neither \'subtree_check\' or \'no_subtree_check\' specified for export "*:/export/AAA/bbb/eee".', "  Assuming default behaviour ('no_subtree_check').", '  NOTE: this default has changed since nfs-utils version 1.0.x', '', 'exportfs: /etc/exports.d/rockstor.exports [5]: Neither \'subtree_check\' or \'no_subtree_check\' specified for export "*:/export/AAA/bbb/fff".', "  Assuming default behaviour ('no_subtree_check').", '  NOTE: this default has changed since nfs-utils version 1.0.x', '', 'exportfs: /etc/exports.d/rockstor.exports [6]: Neither \'subtree_check\' or \'no_subtree_check\' specified for export "*:/export/AAA/bbb/ggg".', "  Assuming default behaviour ('no_subtree_check').", '  NOTE: this default has changed since nfs-utils version 1.0.x', '', 'exportfs: /etc/exports.d/rockstor.exports [7]: Neither \'subtree_check\' or \'no_subtree_check\' specified for export "*:/export/AAA/bbb/ggg/evenlongerdirectorynameshere".', "  Assuming default behaviour ('no_subtree_check').", '  NOTE: this default has changed since nfs-utils version 1.0.x', '', 'exportfs: /etc/exports.d/rockstor.exports [8]: Neither \'subtree_check\' or \'no_subtree_check\' specified for export "*:/export/AAA/bbb/ggg//wemakelongdirectorynames".', "  Assuming default behaviour ('no_subtree_check').", '  NOTE: this default has changed since nfs-utils version 1.0.x', '', 'exportfs: /etc/exports.d/rockstor.exports [9]: Neither \'subtree_check\' or \'no_subtree_check\' specified for export "*:/export/AAA/bbb/ggg/wemakelongdirectorynames/anotherdirectoryoverhere".', "  Assuming default behaviour ('no_subtree_check').", '  NOTE: this default has changed since nfs-utils version 1.0.x', '', 'exportfs: /etc/exports.d/rockstor.exports [10]: Neither \'subtree_check\' or \'no_subtree_check\' specified for export "*:/export/AAA/bbb/ggg/wemakelongdirectorynames/anotherdirectoryoverhere/andanotherlongname".', "  Assuming default behaviour ('no_subtree_check').", '  NOTE: this default has changed since nfs-utils version 1.0.x', '', 'exportfs: Failed to stat /export/AAA/bbb/ggg/wemakelongdirectorynames/anotherdirectoryoverhere/andanotherlongname: No such file or directory', 'exportfs: Failed to stat /export/AAA/bbb/ggg/wemakelongdirectorynames/anotherdirectoryoverhere: No such file or directory', 'exportfs: Failed to stat /export/AAA/bbb/ggg//wemakelongdirectorynames: No such file or directory', 'exportfs: Failed to stat /export/AAA/bbb/ggg/evenlongerdirectorynameshere: No such file or directory', 'exportfs: Failed to stat /export/AAA/bbb/ggg: No such file or directory', 'exportfs: Failed to stat /export/AAA/bbb/fff: No such file or directory', 'exportfs: Failed to stat /export/AAA/bbb/eee: No such file or directory', 'exportfs: Failed to stat /export/AAA/ddd: No such file or directory', 'exportfs: Failed to stat /export/AAA/ccc: No such file or directory', 'exportfs: Failed to stat /export/AAA/bbb: No such file or directory', '']

```

The current nfs-utils version seems to be 2.1.1

**Comment by phillxnet** [comment]
@Hooverdan96 Thanks for creating this issue. Note that:

> created using the last stable (4.5.8)

From the downloads page: **Rockstor 4.5.8-0 = Stable Release Candidate (RC5)** but I don't remember any NFS issues sorted since then and the official 4.6.1 latest Stable.

Give we are heading now (in testing branch) for a 5.1.0-0 Stable it would be good to have a reproducer in the current testing channel.

**Comment by Hooverdan96** [comment]
yes, I ended up wiping everything ... I will try again. In the past I had only tested the creation of an NFS export, which worked fine, but then 6 months later I tried to delete it for the first time (since I usually don't use NFS) and then the above happened. So, not sure if that portion was tested much, and of course I don't remember everything I've used that test instance for.

**Comment by phillxnet** [comment]
@Hooverdan96 during development and testing of the recent NFS fixes / test coverage improvements I was not able to replicate this issue. So what we need really is a reproducer. I'm wondering if this is a TW only thing currently.

Linking to recent attention the NFS side of things has received:

- NFS tests in need of maintenance #2923 #2925
- Inactive NFS export validation #2924 #2926
- NFS exports restored as read-only #2912 #2927

As of now Leap 15.6 has the following info shown for the source package nfs-utils:

```
rleap15-6:~ # zypper info nfs-utils
Loading repository data...
Reading installed packages...


package 'nfs-utils' not found.

Information for srcpackage nfs-utils:
-------------------------------------
Repository            : Update repository with updates from SUSE Linux Enterprise 15
Name                  : nfs-utils
Version               : 2.6.4-150600.28.3.2
Arch                  : noarch
Vendor                : SUSE LLC <https://www.suse.com/>
Summary               : Support Utilities for Kernel nfsd
Description           : 
    This package contains the NFS utilities. You can tune the number of
    server threads via the sysconfig variable USE_KERNEL_NFSD_NUMBER. For
    quota over NFS support, install the quota package.
Builds binary package : 
    S | Name              | Version
    --+-------------------+--------------------
      | libnfsidmap0      | 0.26-150600.28.3.2
    i | libnfsidmap1      | 1.0-150600.28.3.2
    i | nfs-client        | 2.6.4-150600.28.3.2
      | nfs-doc           | 2.6.4-150600.28.3.2
    i | nfs-kernel-server | 2.6.4-150600.28.3.2
      | nfsidmap-devel    | 1.0-150600.28.3.2
      | nfsidmap0-devel   | 0.26-150600.28.3.2
```

**Comment by Hooverdan96** [comment]
I will try again to see whether I can reproduce it, if we're lucky, it's not occurring anymore, and then it can be closed and reopened when another reproducer is found.
