### ISSUE TITLE
[t] Assigning custom GID during User Group creation, results in syntax error

### ISSUE THREAD

**Issue by Hooverdan96** [rockstor/rockstor-core#2807]
when trying to create a new User Group using a custom GID (e.g., 1001), the system will throw a syntax error. Here is the traceback:
```
            Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/system/osi.py", line 236, in run_command
    p = subprocess.Popen(
        ^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.11/subprocess.py", line 1883, in _execute_child
    self.pid = _fork_exec(
               ^^^^^^^^^^^
TypeError: expected str, bytes or os.PathLike object, not int

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/rest_framework_custom/generic_view.py", line 41, in _handle_exception
    yield
  File "/opt/rockstor/src/rockstor/storageadmin/views/group.py", line 74, in post
    groupadd(groupname, gid)
  File "/opt/rockstor/src/rockstor/system/users.py", line 254, in groupadd
    return run_command(cmd)
           ^^^^^^^^^^^^^^^^
  File "/opt/rockstor/src/rockstor/system/osi.py", line 253, in run_command
    raise Exception("Exception while running command({}): {}".format(cmd, e))
Exception: Exception while running command(['/usr/sbin/groupadd', '-g', 1001, 'plex']): expected str, bytes or os.PathLike object, not int
```
 when leaving the field blank, i.e. allow AutoGenerate, this is not an issue. I assume, in that case the `-g` parameter is not passed and the OS assigns a new number.

Note, when creating a new user with a custom GID, this error does not occur.

**Comment by FroggyFlox** [comment]
Nice find!
That looks like a Python3 requirement that was missed in the transition so far.so I've added this issue to our next Stable milestone.

**Comment by Hooverdan96** [comment]
I suspect we might have some more candidates that take advantage of the run_command(cmd) or similar, where usually integers are passed instead of strings? ... Non-exhaustive list mind you:

like this:
https://github.com/rockstor/rockstor-core/blob/4d60a2c683140aaa10a8e5b201157163cc9a898b/src/rockstor/system/network.py#L344-L349

possibly this:
https://github.com/rockstor/rockstor-core/blob/4d60a2c683140aaa10a8e5b201157163cc9a898b/src/rockstor/scripts/qgroup_maxout_limit.py#L53-L57

https://github.com/rockstor/rockstor-core/blob/4d60a2c683140aaa10a8e5b201157163cc9a898b/src/rockstor/system/acl.py#L31-L34


only relevant, if a numeric domain is used (which I believe I have seen in the past):
https://github.com/rockstor/rockstor-core/blob/4d60a2c683140aaa10a8e5b201157163cc9a898b/src/rockstor/smart_manager/views/active_directory.py#L105-L110

and finally, we have this issue open, which likely has the same root cause:

https://github.com/rockstor/rockstor-core/issues/2805

**Comment by Hooverdan96** [comment]
Looking further into the `run_command` function, it seems that the mapping of all command parameters to strings has been commented out in Line 233:

https://github.com/rockstor/rockstor-core/blob/6c86e3858079ce8edc62c62684a7f2cf50fb6d79/src/rockstor/system/osi.py#L228-L245

based on this PR:

https://github.com/rockstor/rockstor-core/issues/2564

and this commit:

https://github.com/rockstor/rockstor-core/commit/316654cff7f495329fde449f8328530f207a6cd0


For this specific error message, when checking the comparable `useradd` I noticed that the ID is "stringified"

https://github.com/rockstor/rockstor-core/blob/6c86e3858079ce8edc62c62684a7f2cf50fb6d79/src/rockstor/system/users.py#L239-L246

whereas in the `groupadd` it is not:

https://github.com/rockstor/rockstor-core/blob/6c86e3858079ce8edc62c62684a7f2cf50fb6d79/src/rockstor/system/users.py#L250-L254

which would explain the above that the error occurs for a group addition, but not a user addition.

It could be fixed here (probably should for consistency purposes in the group/user management), but that would leave examples like the above, where, if a numeric AD name was passed, the `run_command` would still fail.

So, not sure, whether it's more secure to force the string conversion in the `run_command` function to ensure that only string values are passed into it, or enforce the "stringification" of any cmd parameter by the caller?

**Comment by phillxnet** [comment]
@Hooverdan96 Another simple reproducer for the original issue here is of course creating a custom group:

![Custom-group-creation-failure](https://github.com/rockstor/rockstor-core/assets/2521585/97ff4582-eaa5-4aeb-89ae-9c5c5cf2f3ae)

```
            Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/system/osi.py", line 236, in run_command
    p = subprocess.Popen(
        ^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.11/subprocess.py", line 1883, in _execute_child
    self.pid = _fork_exec(
               ^^^^^^^^^^^
TypeError: expected str, bytes or os.PathLike object, not int

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/rest_framework_custom/generic_view.py", line 41, in _handle_exception
    yield
  File "/opt/rockstor/src/rockstor/storageadmin/views/group.py", line 74, in post
    groupadd(groupname, gid)
  File "/opt/rockstor/src/rockstor/system/users.py", line 254, in groupadd
    return run_command(cmd)
           ^^^^^^^^^^^^^^^^
  File "/opt/rockstor/src/rockstor/system/osi.py", line 253, in run_command
    raise Exception("Exception while running command({}): {}".format(cmd, e))
Exception: Exception while running command(['/usr/sbin/groupadd', '-g', 1000, 'auth-config']): expected str, bytes or os.PathLike object, not int

```

I think we should be more TYPE orientated here, and rather than force map all elements passed to run_command we should pass correct types in the first place. I.e. fix in place; rather than work around incorrect types. Maybe a type hint of sorts in run_command and fix all other code to use only the new str type as command list elements.

**Comment by Hooverdan96** [comment]
sounds good to me. Pardon my ignorance, when you talk about hint, do you mean adding some comment in the code, indicating that the caller should have string only elements or are you referring to some other "hinting"?

**Comment by phillxnet** [comment]
@Hooverdan96 Re:

> when you talk about hint

My apologies, I was referencing what @FroggyFlox began within Rockstor's code, once we were a little more 'modern' on the Python version front: "type hinting", introduced in Py3.5:

https://realpython.com/lessons/type-hinting/

**Comment by Hooverdan96** [comment]
ah, ok, so you mean like this:

https://github.com/rockstor/rockstor-core/blob/4d60a2c683140aaa10a8e5b201157163cc9a898b/src/rockstor/system/osi.py#L209-L218

turning into something like this:

```
def run_command(
    cmd: str,
    shell: bool = False,
    stdout: PIPE = subprocess.PIPE,
    stderr: PIPE = subprocess.PIPE,
    stdin: PIPE = subprocess.PIPE,
    throw: bool = True,
    log: bool = False,
    input=None,
):
```

I know, probably a little overboard 😄 in the type hinting - I guess, the important one would be for the `cmd` parameter.

**Comment by phillxnet** [comment]
@Hooverdan96 yes, that was the type of thing I was thinking. But our `cmd` is a LIST type with all str() members expected: not sure how that is typed yet. Plus with `input` there is a 'type or None' definition in type hints. Maybe that would be the way to go on that front.

> I know, probably a little overboard

Not at all. Plus there is no typing on the return type! I like this extra stringency. Early Python was just too loose. Hence this more recent introduction. And besides helping with errors at run-time: i.e. wrong type being more informative, the IDE's are also informed by this and can help us by hinting that we are doing it wrong: via their being informed from the hints themselves. All good stuff. I should have taken this approach from the get-go when doing the initial Python 2 to 3 migration. But alas there was much to do and I had thought type hints were not yet available for some reason. Then saw @FroggyFlox popping them in and was much relieved to finally have them available.

All our newer code, and significant code changes, should be, at least trying to use these to their fullest extend now. Take a look at my recent replication fixes, they were super helpful there as we had some major str() / byte type issues going on there from our Py2.7 days.

**Comment by phillxnet** [comment]
> for q in qgroup_ids:

Likewise qgourp_ids is constructed from strings: but I'll pop in a type-hint anyway. Cheers.

**Comment by phillxnet** [comment]
> only relevant, if a numeric domain is used (which I believe I have seen in the past,

I wouldn't have though that would float !

**Comment by phillxnet** [comment]
Another potential inadvertent int left over from our Py2.7 to Py3.11 modifications.

Create a docker net 111: fine.
Delete the docker-net named "111"

```
[22/Mar/2024 15:33:25] ERROR [storageadmin.util:45] Exception: '>' not supported between instances of 'BridgeConnection' and 'int'
Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/rest_framework_custom/generic_view.py", line 41, in _handle_exception
    yield
  File "/opt/rockstor/src/rockstor/storageadmin/views/network.py", line 548, in delete
    if nco.bridgeconnection_set.first() > 0:  # If docker network
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '>' not supported between instances of 'BridgeConnection' and 'int'
```

**Comment by phillxnet** [comment]
@FroggyFlox Thanks for taking a look at this. Agreed something is a drift here, and it looked a little different from my current draft pr against this issue hence the spin-off issue I've just created. Also I'm now on the home run for my current draft PR so will likely present that shortly. You may want to rebase and work on it once it's merged as there are a few hopefully useful type hint additions etc. But again, it looks like it's something a little different to what I'm currently working on.

**Comment by phillxnet** [comment]
Closing as:
Fixed by #2815
