### ISSUE TITLE
ROOT pool import failure (Advanced Users Only)

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-core#2832]
Post the changes in-development against issue #2824 we have the following failure when importing a ROOT Pool: OS system Pool.

It would be nice to be able to retain this capability: however this option is now indicated/considered as "Advanced Users Only" in the tooltip associated with this particular pool import. This import fail was previously thought to be associated with non snapshot development hosts: however in the later stages of #2824 development we now see the following:

```
[16/Apr/2024 17:28:38] DEBUG [system.osi:265] Running command: /usr/sbin/btrfs quota enable /mnt2/ROOT
[16/Apr/2024 17:28:38] ERROR [storageadmin.util:45] Exception: Failed to import any pool on device db id (1). Error: (Error running a command. cmd = /usr/sbin/btrfs property get /mnt2/ROOT/.snapshots/1/snapshot ro. rc = 1. stdout = ['']. stderr = ['ERROR: failed to open /mnt2/ROOT/.snapshots/1/snapshot: No such file or directory', 'ERROR: failed to detect object type: No such file or directory', '']).
Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/storageadmin/views/disk.py", line 774, in _btrfs_disk_import
    import_shares(po, request)
  File "/opt/rockstor/src/rockstor/storageadmin/views/share_helpers.py", line 95, in import_shares
    shares_in_pool = shares_info(pool)
                     ^^^^^^^^^^^^^^^^^
  File "/opt/rockstor/src/rockstor/fs/btrfs.py", line 1010, in shares_info
    s_name, writable, is_clone = parse_snap_details(
                                 ^^^^^^^^^^^^^^^^^^^
  File "/opt/rockstor/src/rockstor/fs/btrfs.py", line 1055, in parse_snap_details
    writable = not get_property(full_snap_path, "ro")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/rockstor/src/rockstor/fs/btrfs.py", line 2346, in get_property
    o, e, rc = run_command(cmd)
               ^^^^^^^^^^^^^^^^
  File "/opt/rockstor/src/rockstor/system/osi.py", line 293, in run_command
    raise CommandException(cmd, out, err, rc)
system.exceptions.CommandException: Error running a command. cmd = /usr/sbin/btrfs property get /mnt2/ROOT/.snapshots/1/snapshot ro. rc = 1. stdout = ['']. stderr = ['ERROR: failed to open /mnt2/ROOT/.snapshots/1/snapshot: No such file or directory', 'ERROR: failed to detect object type: No such file or directory', '']
[16/Apr/2024 17:28:38] DEBUG [storageadmin.util:46] Current Rockstor version: 5.0.8-2830
```

On a Leap 15.5 system with the following ROOT pool mount; ~~established by our installer/fstab~~:
```
/dev/sda3 on /mnt2/ROOT type btrfs (rw,relatime,space_cache,subvolid=259,subvol=/@/.snapshots/1/snapshot)
```

---

It is proposed that this now advanced feature, that **does not present itself on existing in-place updates** as the pool is already imported, should be handled independently: avoiding further delays in our pending stable push.

[EDIT] note that the /mnt2/ROOT mount shown above is as a result of an in-progress (and in this case failed) import: we rotinely mount the entire pool (during import) to have certain Pool wide facilities. On reboot of the same system this mount no longer exists: and we have only the installer/initbab/fstab arrangement mount of "/":
```
/dev/sda3 on / type btrfs (rw,relatime,space_cache,subvolid=259,subvol=/@/.snapshots/1/snapshot)
```

[EDIT 2] We also look to have an unwanted mount here: in the still special case of the 'ROOT' Pool:

https://github.com/rockstor/rockstor-core/blob/6c6acb437a8f19108419390ea3df3563f8d2689a/src/rockstor/storageadmin/models/pool.py#L85-L93

**Comment by phillxnet** [comment]
During early stages of this failed import we have (via a dev debug log addition):

```
[16/Apr/2024 18:27:39] DEBUG [storageadmin.views.disk:727] _btrfs_disk_import using get_pool_info(ata-QEMU_HARDDISK_QM00001-part3) = {'disks': {'ata-QEMU_HARDDISK_QM00001-part3': Dev(temp_name='/dev/sda3', is_byid=True, devid='1', size=25128940.0, allocated=8454144.0)}, 'hasMissingDev': False, 'fullDevCount': 1, 'missingDevCount': 0, 'uuid': '4d866326-2a23-4f01-b81f-4f9e3a811203', 'label': 'ROOT'}
```

**Comment by phillxnet** [comment]
This issue may well now be resolved as part of the ongoing development referenced.
Once our Draft PR is re-submitted and we have a successful ROOT import on a boot-to-snapshot arrangement: ideally when in an installer arrangement, then this issue can be closed as an in-development detail, stepping stone, against #2824

**Comment by phillxnet** [comment]
Closing as an artifact of in-progress development associated with Draft PR:
Un special-case system drive btrfs-in-partition treatment #2824 #2830

Which has now been superseded by PR #2835 which no longer exhibits this issue.
