### ISSUE TITLE
duplicate disk name

### ISSUE THREAD

**Issue by schakrava** [rockstor/rockstor-core#581]
I also hit a bug again with switching device names. This time the error was
ERROR [storageadmin.util:39] exception: duplicate key value violates unique constraint "storageadmin_disk_name_key"
DETAIL:  Key (name)=(sdd) already exists.

User to send rockstor.log to help with debugging.

**Comment by schakrava** [comment]
[20/Jan/2015 22:53:17] ERROR [storageadmin.util:38] request path: /api/disks method: GET data: <QueryDict: {}>
[20/Jan/2015 22:53:17] ERROR [storageadmin.util:39] exception: duplicate key value violates unique constraint "storageadmin_disk_name_key"
DETAIL:  Key (name)=(sdd) already exists.
Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/rest_framework_custom/generic_view.py", line 89, in _handle_exception
    yield
  File "/opt/rockstor/src/rockstor/storageadmin/views/disk.py", line 49, in get_queryset
    self._scan()
  File "/opt/rockstor/eggs/Django-1.6.2-py2.7.egg/django/db/transaction.py", line 399, in inner
    return func(*args, **kwargs)
  File "/opt/rockstor/src/rockstor/storageadmin/views/disk.py", line 85, in _scan
    dob.save()
  File "/opt/rockstor/eggs/Django-1.6.2-py2.7.egg/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/opt/rockstor/eggs/Django-1.6.2-py2.7.egg/django/db/models/base.py", line 573, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/opt/rockstor/eggs/Django-1.6.2-py2.7.egg/django/db/models/base.py", line 635, in _save_table
    forced_update)
  File "/opt/rockstor/eggs/Django-1.6.2-py2.7.egg/django/db/models/base.py", line 679, in _do_update
    return filtered._update(values) > 0
  File "/opt/rockstor/eggs/Django-1.6.2-py2.7.egg/django/db/models/query.py", line 507, in _update
    return query.get_compiler(self.db).execute_sql(None)
  File "/opt/rockstor/eggs/Django-1.6.2-py2.7.egg/django/db/models/sql/compiler.py", line 976, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/opt/rockstor/eggs/Django-1.6.2-py2.7.egg/django/db/models/sql/compiler.py", line 782, in execute_sql
    cursor.execute(sql, params)
  File "/opt/rockstor/eggs/Django-1.6.2-py2.7.egg/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/opt/rockstor/eggs/Django-1.6.2-py2.7.egg/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/opt/rockstor/eggs/Django-1.6.2-py2.7.egg/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
IntegrityError: duplicate key value violates unique constraint "storageadmin_disk_name_key"
DETAIL:  Key (name)=(sdd) already exists.

**Comment by pecigonzalo** [comment]
Hitting a similar issue, 

```
[24/Aug/2015 20:02:10] ERROR [storageadmin.util:38] request path: /api/disks/scan method: POST data: <QueryDict: {}>
[24/Aug/2015 20:02:10] ERROR [storageadmin.util:39] exception: duplicate key value violates unique constraint "storageadmin_pool_name_key"
DETAIL:  Key (name)=(rockstor_rockstor) already exists.
Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/rest_framework_custom/generic_view.py", line 40, in _handle_exception
    yield
  File "/opt/rockstor/src/rockstor/storageadmin/views/disk.py", line 110, in post
    return self._scan()
  File "/opt/rockstor/eggs/Django-1.6.2-py2.7.egg/django/db/transaction.py", line 339, in inner
    return func(*args, **kwargs)
  File "/opt/rockstor/src/rockstor/storageadmin/views/disk.py", line 79, in _scan
    self._create_root_pool(dob)
  File "/opt/rockstor/src/rockstor/storageadmin/views/disk.py", line 98, in _create_root_pool
    p.save()
  File "/opt/rockstor/eggs/Django-1.6.2-py2.7.egg/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/opt/rockstor/eggs/Django-1.6.2-py2.7.egg/django/db/models/base.py", line 573, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/opt/rockstor/eggs/Django-1.6.2-py2.7.egg/django/db/models/base.py", line 654, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/opt/rockstor/eggs/Django-1.6.2-py2.7.egg/django/db/models/base.py", line 687, in _do_insert
    using=using, raw=raw)
  File "/opt/rockstor/eggs/Django-1.6.2-py2.7.egg/django/db/models/manager.py", line 232, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/opt/rockstor/eggs/Django-1.6.2-py2.7.egg/django/db/models/query.py", line 1511, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/opt/rockstor/eggs/Django-1.6.2-py2.7.egg/django/db/models/sql/compiler.py", line 899, in execute_sql
    cursor.execute(sql, params)
  File "/opt/rockstor/eggs/Django-1.6.2-py2.7.egg/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/opt/rockstor/eggs/Django-1.6.2-py2.7.egg/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/opt/rockstor/eggs/Django-1.6.2-py2.7.egg/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
IntegrityError: duplicate key value violates unique constraint "storageadmin_pool_name_key"
DETAIL:  Key (name)=(rockstor_rockstor) already exists.

[24/Aug/2015 20:02:10] ERROR [smart_manager.data_collector:353] Failed to update disk state.. exception: duplicate key value violates unique constraint "storageadmin_pool_name_key"
DETAIL:  Key (name)=(rockstor_rockstor) already exists.

[24/Aug/2015 20:02:10] ERROR [storageadmin.middleware:35] Exception occured while processing a request. Path: /api/commands/refresh-pool-state method: POST
[24/Aug/2015 20:02:10] ERROR [storageadmin.middleware:36] Error running a command. cmd = ['/sbin/btrfs', 'fi', 'df', '/mnt2/centos']. rc = 1. stdout = ['']. stderr = ["ERROR: can't access '/mnt2/centos'", '']
Traceback (most recent call last):
  File "/opt/rockstor/eggs/Django-1.6.2-py2.7.egg/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/rockstor/eggs/Django-1.6.2-py2.7.egg/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.6.2-py2.7.egg/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/views.py", line 452, in dispatch
    response = self.handle_exception(exc)
  File "/opt/rockstor/eggs/djangorestframework-3.1.1-py2.7.egg/rest_framework/views.py", line 449, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/rockstor/eggs/Django-1.6.2-py2.7.egg/django/db/transaction.py", line 339, in inner
    return func(*args, **kwargs)
  File "/opt/rockstor/src/rockstor/storageadmin/views/command.py", line 242, in post
    p.raid = pool_raid('%s%s' % (settings.MNT_PT, p.name))['data']
  File "/opt/rockstor/src/rockstor/fs/btrfs.py", line 82, in pool_raid
    o, e, rc = run_command([BTRFS, 'fi', 'df', mnt_pt])
  File "/opt/rockstor/src/rockstor/system/osi.py", line 85, in run_command
    raise CommandException(cmd, out, err, rc)
CommandException: Error running a command. cmd = ['/sbin/btrfs', 'fi', 'df', '/mnt2/centos']. rc = 1. stdout = ['']. stderr = ["ERROR: can't access '/mnt2/centos'", '']
[24/Aug/2015 20:02:10] ERROR [smart_manager.data_collector:353] Failed to update pool state.. exception: Internal Server Error
[24/Aug/2015 20:02:10] DEBUG [smart_manager.data_collector:351] Share state updated successfully
[24/Aug/2015 20:02:10] ERROR [storageadmin.util:38] request path: /api/disks/scan method: POST data: <QueryDict: {}>
[24/Aug/2015 20:02:10] ERROR [storageadmin.util:39] exception: duplicate key value violates unique constraint "storageadmin_pool_name_key"
DETAIL:  Key (name)=(rockstor_rockstor) already exists.
Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/rest_framework_custom/generic_view.py", line 40, in _handle_exception
    yield
  File "/opt/rockstor/src/rockstor/storageadmin/views/disk.py", line 110, in post
    return self._scan()
  File "/opt/rockstor/eggs/Django-1.6.2-py2.7.egg/django/db/transaction.py", line 339, in inner
    return func(*args, **kwargs)
  File "/opt/rockstor/src/rockstor/storageadmin/views/disk.py", line 79, in _scan
    self._create_root_pool(dob)
  File "/opt/rockstor/src/rockstor/storageadmin/views/disk.py", line 98, in _create_root_pool
    p.save()
  File "/opt/rockstor/eggs/Django-1.6.2-py2.7.egg/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/opt/rockstor/eggs/Django-1.6.2-py2.7.egg/django/db/models/base.py", line 573, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/opt/rockstor/eggs/Django-1.6.2-py2.7.egg/django/db/models/base.py", line 654, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/opt/rockstor/eggs/Django-1.6.2-py2.7.egg/django/db/models/base.py", line 687, in _do_insert
    using=using, raw=raw)
  File "/opt/rockstor/eggs/Django-1.6.2-py2.7.egg/django/db/models/manager.py", line 232, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/opt/rockstor/eggs/Django-1.6.2-py2.7.egg/django/db/models/query.py", line 1511, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/opt/rockstor/eggs/Django-1.6.2-py2.7.egg/django/db/models/sql/compiler.py", line 899, in execute_sql
    cursor.execute(sql, params)
  File "/opt/rockstor/eggs/Django-1.6.2-py2.7.egg/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/opt/rockstor/eggs/Django-1.6.2-py2.7.egg/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/opt/rockstor/eggs/Django-1.6.2-py2.7.egg/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
IntegrityError: duplicate key value violates unique constraint "storageadmin_pool_name_key"
DETAIL:  Key (name)=(rockstor_rockstor) already exists.

[24/Aug/2015 20:02:10] DEBUG [smart_manager.data_collector:351] Snapshot state updated successfully
[24/Aug/2015 20:02:10] DEBUG [smart_manager.data_collector:361] sent update information ('3.8-6', '3.8-6', [])
[24/Aug/2015 20:02:26] DEBUG [smart_manager.data_collector:299] Sysinfo has disconnected

```

**Comment by pecigonzalo** [comment]
This lines are really odd as /mnt2/centos doesnt exist, so thats why the command fails, but i cant find where its getting that /mnt/centos value from.
```
[24/Aug/2015 20:02:10] ERROR [storageadmin.middleware:35] Exception occured while processing a request. Path: /api/commands/refresh-pool-state method: POST
[24/Aug/2015 20:02:10] ERROR [storageadmin.middleware:36] Error running a command. cmd = ['/sbin/btrfs', 'fi', 'df', '/mnt2/centos']. rc = 1. stdout = ['']. stderr = ["ERROR: can't access '/mnt2/centos'", '']
```

**Comment by schakrava** [comment]
I think the root cause is btrfs device scan not running or not running soon enough. Could you update to 3.8-6, which I pushed like 5 minutes ago :) . Let me know if the issue persists after the update.

**Comment by pecigonzalo** [comment]
I am running that version, as i just did a new install. I think its reading the disk label, and appending it do the mount directory.
(the disk lable was centos) im confirming now.

**Comment by pecigonzalo** [comment]
Running ```/sbin/btrfs fi label / rockstor_rockstor``` fixed it for me. This applies when installing on top of CentOS
