### ISSUE TITLE
some snapshots cannot be deleted when nfs service is off

### ISSUE THREAD

**Issue by schakrava** [rockstor/rockstor-core#618]
This is due to visibility flag of snapshots.

**Comment by schakrava** [comment]
Unable to reproduce this problem. Originally, user reported it with the following in logs

[09/Mar/2015 12:21:32] ERROR [storageadmin.util:38] request path: /api/shares/sharebu/snapshots method: DELETE data: <QueryDict: {}>
[09/Mar/2015 12:21:32] ERROR [storageadmin.util:39] exception: A low level error occured while deleting snapshot(Snap1). Try again later.
Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/storageadmin/views/snapshot.py", line 218, in _delete_snapshot
    self._toggle_visibility(share, snapshot.real_name, on=False)
  File "/opt/rockstor/eggs/Django-1.6.2-py2.7.egg/django/db/transaction.py", line 399, in inner
    return func(*args, **kwargs)
  File "/opt/rockstor/src/rockstor/storageadmin/views/snapshot.py", line 102, in _toggle_visibility
    refresh_nfs_exports(exports)
  File "/opt/rockstor/src/rockstor/system/osi.py", line 173, in refresh_nfs_exports
    '%s:%s' % (c['client_str'], e)])
  File "/opt/rockstor/src/rockstor/system/osi.py", line 78, in run_command
    raise CommandException(out, err, rc)
CommandException: ' exportfs: 192.168.1.115:/export/sharebu/.snp_20150112193111: Function not implemented '

Starting the nfs server and trying delete again worked for the user. However, I am not able to reproduce the problem. I am able to delete snapshots with nfs turned off or on as expected.

If anyone else runs into this problem, please provide steps to reproduce.
