### ISSUE TITLE
new SMART subsystem in 3.7-8 - "[Errno 2] No such file or directory" with no storage drives

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-core#652]
Upgraded from 3.5-5 (no storage disks) to 3.7-5 and got the subject error on reboot.

From the following in the rockstor.log it looks like the new SMART additions may not deal elegantly with no storage drives attached.
Corner case but important I think especially on fresh installs.
```
[20/May/2015 08:47:14] ERROR [storageadmin.util:38] request path: /api/disks method: GET data: <QueryDict: {}>
[20/May/2015 08:47:14] ERROR [storageadmin.util:39] exception: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/rest_framework_custom/generic_view.py", line 40, in _handle_exception
    yield
  File "/opt/rockstor/src/rockstor/storageadmin/views/disk.py", line 45, in get_queryset
    self._scan()
  File "/opt/rockstor/eggs/Django-1.6.2-py2.7.egg/django/db/transaction.py", line 339, in inner
    return func(*args, **kwargs)
  File "/opt/rockstor/src/rockstor/storageadmin/views/disk.py", line 83, in _scan
    do.smart_available, do.smart_enabled = smart.available(do.name)
  File "/opt/rockstor/src/rockstor/system/smart.py", line 166, in available
    o, e, rc = run_command([SMART, '--info', ('/dev/%s' % device)])
  File "/opt/rockstor/src/rockstor/system/osi.py", line 72, in run_command
    p = subprocess.Popen(cmd, shell=shell, stdout=stdout, stderr=stderr)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1308, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by phillxnet** [comment]
The 3.7-9 update fixed this issue so closing.

**Comment by schakrava** [comment]
@phillxnet Thanks for reporting this issue! It was a silly typo bug that slipped away.

**Comment by phillxnet** [comment]
My pleasure.
