### ISSUE TITLE
Buggy NFS export management

### ISSUE THREAD

**Issue by schakrava** [rockstor/rockstor-core#713]
If exports are added while nfs server is turned off, the management seems to be buggy as per a user report. We should test NFS export management thoroughly and add functional tests. Here's the very helpful info from a user.

I then went to NFS, leaving the service disabled and adding an export for 1 or more of the shares to a single NFS Client, represented as HOSTID below and in the attached (I have just edited the below error message from the UI and the attached log, to remove the system IP Address), the export was writable and async. Zlib compression is enabled on the “project” share. When “submit” is clicked it produces the below error.

Error!

A lower level error occured while refreshing NFS exports. Error: ' exportfs: HOSTIP:/export/share_all: Function not implemented exportfs: HOSTIP:/export/images: Function not implemented exportfs: HOSTIP:/export/project: Function not implemented '. This could be due to invalid input. If so, correct your input and try again.

After removing the “share_all” share, the same error as above is produced. Which is strange since the “share_all” share no longer exists according to the UI.

After reboot:

Error!

A lower level error occured while refreshing NFS exports. Error: ' exportfs: HOSTID:/export/project: Function not implemented '. This could be due to invalid input. If so, correct your input and try again.

Now the NFS share error still exists but it is no longer caching all of the share names even when trying to only export a single share.

From the log;
[29/Jun/2015 23:36:15] DEBUG [smart_manager.data_collector:348] Started Proc Retreiver
[29/Jun/2015 23:36:27] INFO [storageadmin.views.command:103] export = {}
[29/Jun/2015 23:40:43] ERROR [storageadmin.views.nfs_exports:131] ' exportfs: HOSTID:/export/project: Function not implemented '
Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/storageadmin/views/nfs_helpers.py", line 126, in refresh_wrapper
    refresh_nfs_exports(exports)
  File "/opt/rockstor/src/rockstor/system/osi.py", line 174, in refresh_nfs_exports
    '%s:%s' % (c['client_str'], e)])
  File "/opt/rockstor/src/rockstor/system/osi.py", line 79, in run_command
    raise CommandException(out, err, rc)
CommandException: ' exportfs: HOSTID:/export/project: Function not implemented '
[29/Jun/2015 23:40:43] ERROR [storageadmin.util:38] request path: /api/nfs-exports method: POST data: {u'mod_choice': u'rw', u'host_str': u'HOSTID', u'a
[29/Jun/2015 23:40:43] ERROR [storageadmin.util:39] exception: A lower level error occured while refreshing NFS exports. Error: ' exportfs: HOSTID:/expo
Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/storageadmin/views/nfs_helpers.py", line 126, in refresh_wrapper
    refresh_nfs_exports(exports)
  File "/opt/rockstor/src/rockstor/system/osi.py", line 174, in refresh_nfs_exports
    '%s:%s' % (c['client_str'], e)])
  File "/opt/rockstor/src/rockstor/system/osi.py", line 79, in run_command
    raise CommandException(out, err, rc)
CommandException: ' exportfs: HOSTID:/export/project: Function not implemented '

**Comment by schakrava** [comment]
More user feedback related to this issue.

Allow the creation of NFS exports without NFS being enabled. Include a warning to notify the admin that NFS is currently disabled, would you like me to enable it for you <PROMPT>.
