### ISSUE TITLE
pool details page broken due to btrfs-progs changes

### ISSUE THREAD

**Issue by schakrava** [rockstor/rockstor-core#720]
After the 3.8-2 update, going to pool details page throws an error. This is due to the btrfs progs update that requires changes to srub status gathering.

[07/Jul/2015 14:03:18] ERROR [storageadmin.util:39] exception: invalid literal for int() with base 10: 'after'
Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/rest_framework_custom/generic_view.py", line 40, in _handle_exception
    yield
  File "/opt/rockstor/src/rockstor/storageadmin/views/pool_scrub.py", line 46, in get_queryset
    self._scrub_status(pool, disk)
  File "/opt/rockstor/eggs/Django-1.6.2-py2.7.egg/django/db/transaction.py", line 399, in inner
    return func(*args, **kwargs)
  File "/opt/rockstor/src/rockstor/storageadmin/views/pool_scrub.py", line 56, in _scrub_status
    cur_status = scrub_status(pool, disk.name)
  File "/opt/rockstor/src/rockstor/fs/btrfs.py", line 604, in scrub_status
    stats['duration'] = int(out[1].split()[-2])
ValueError: invalid literal for int() with base 10: 'after'

**Comment by phillxnet** [comment]
@schakrava #752 has a collection of info that may relate to this, including a recent workaround, but not sure. Also Rockstor version difference, I am assuming we are on a successive approximation to a fix.

**Comment by schakrava** [comment]
Also fixed by #760
