### ISSUE TITLE
scrub status parsing error on pools page "invalid literal for int() ..."

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-core#752]
As reported by sirhcjw in forum post:- http://forum.rockstor.com/t/error-when-clicking-on-pool/225/3
and assisted by @gkadillak 

Pools page showing:-
Error!
invalid literal for int() with base 10: 'after'"

```
[18/Jul/2015 17:10:37] ERROR [storageadmin.util:38] request path: /api/pools/pool01/scrub method: GET data:
[18/Jul/2015 17:10:37] ERROR [storageadmin.util:39] exception: invalid literal for int() with base 10: 'after'
Traceback (most recent call last):
File "/opt/rockstor/src/rockstor/rest_framework_custom/generic_view.py", line 40, in handleexception
yield
File "/opt/rockstor/src/rockstor/storageadmin/views/pool_scrub.py", line 46, in get_queryset
self.scrubstatus(pool, disk)
File "/opt/rockstor/eggs/Django-1.6.2-py2.7.egg/django/db/transaction.py", line 399, in inner
return func(*args, **kwargs)
File "/opt/rockstor/src/rockstor/storageadmin/views/pool_scrub.py", line 56, in scrubstatus
cur_status = scrub_status(pool, disk.name)
File "/opt/rockstor/src/rockstor/fs/btrfs.py", line 627, in scrub_status
stats['duration'] = int(out[1].split()[-2])
ValueError: invalid literal for int() with base 10: 'after'
```

sirhcjw diagnosed as scrub status related:-
```
btrfs scrub status /mnt2/pool01
scrub status for cdc962b5-f6f6-45b4-bfc0-17316b3c1d7f
scrub started at Mon Jul 13 22:03:23 2015 and finished after 01:03:48
total bytes scrubbed: 1.30TiB with 1632 errors
error details: read=4 csum=1628
corrected errors: 1632, uncorrectable errors: 0, unverified errors: 0

Returns this.

I kicked off another scrub as from looking at the code and the error I figured it was not handling what was being returned and presto fixed.

So there is a bug.

Can this please be looked at and addressed.

Thanks

Chris
```

**Comment by phillxnet** [comment]
Please update original forum post 
http://forum.rockstor.com/t/error-when-clicking-on-pool/225/5 on this issues resolution.

**Comment by phillxnet** [comment]
Additional info and finding from KarstenV on the same forum thread:- http://forum.rockstor.com/t/error-when-clicking-on-pool/225/10

"... The command was "btrfs scrub start -B -d /dev/sdx".
The -B tells the btrfs scrub, to not run in the background. Then you can exit out by doing Ctrl-c.
After having run a partial scrub and exiting out this way, the pool was accessible in the web interface again.
This is not a fix to the original problem, but it does make it possible to access the pool, and add/remove disks / do other maintenance. ..."

Copying here to add to the know examples of triggers and workarounds.
Thanks to KarstenV for this find.

**Comment by phillxnet** [comment]
linking to #720 as same error but not sure if same cause.
